### ISSUE TITLE
功能支持

### ISSUE THREAD

**Issue by FenghenHome** [p4gefau1t/trojan-go#1]
大佬好
可否支持mysql或者api的方式用户管理和流量统计

**Comment by p4gefau1t** [comment]
正在实现，计划是和原版trojan的mysql的统计兼容，也支持sqlite等其他常见数据库

**Comment by FenghenHome** [comment]
对于mysql支持建议采用定时缓存用户策略，不然单mysql多节点部署会有远程数据库校验延迟问题，现在官方c语言版本就存在这个问题，希望改进

**Comment by p4gefau1t** [comment]
好的，感谢建议，之后的开发会注意这个问题

**Comment by FenghenHome** [comment]
还有一个c语言版本的多线程一直未解决，如果可以希望大佬帮忙看看go语言版本是否ok

**Comment by p4gefau1t** [comment]
可以具体说一下是什么问题吗

**Comment by FenghenHome** [comment]
https://github.com/trojan-gfw/trojan/pull/179

**Comment by p4gefau1t** [comment]
看了以下pr，这个似乎只是boost依赖的问题
trojan-go并不依赖boost，编译也只需要golang编译器。而且得到的也是静态链接的单个可执行文件，而不依赖其他动态链接库，所以应该不会有这类问题

**Comment by FenghenHome** [comment]
官方端口复用，fast tcp什么都能支持吗

**Comment by p4gefau1t** [comment]
目前还没有实现，预计下一个版本可以实现

**Comment by FenghenHome** [comment]
期待中

**Comment by p4gefau1t** [comment]
已经支持MySQL流量统计和配额限制

**Comment by FenghenHome** [comment]
有tg吗
