### ISSUE TITLE
有没有计划自动获取 letsencrypt 证书？

### ISSUE THREAD

**Issue by yjsslab** [p4gefau1t/trojan-go#10]

**Comment by p4gefau1t** [comment]
自动申请证书的功能，Caddy等Web服务器已经支持。而且申请签名需要实现一个Web服务器进行交互认证，实现后会使程序比较臃肿。Trojan-Go只是一个代理，这类事情交给专门的程序做比较好。

**Comment by p4gefau1t** [comment]
目前没有计划，如果这方面的需求比较多，会考虑实现自签发证书的功能，但应该不会实现letsencrypt之类的证书申请

**Comment by FenghenHome** [comment]
自动申请证书能实现的太多了，一键化脚本也有很多

**Comment by p4gefau1t** [comment]
https://pkg.go.dev/golang.org/x/crypto/acme/autocert?tab=doc
似乎可以基于acme自动申请证书，可以考虑这个功能

**Comment by p4gefau1t** [comment]
已经实现，这个issue关闭
