### ISSUE TITLE
新版本0.7.4使用配置文件无法启动

### ISSUE THREAD

**Issue by jinwyp** [p4gefau1t/trojan-go#102]
1 [Unit]
      2 Description=trojan-go
      3 After=network.target
      4 
      5 [Service]
      6 Type=simple
      7 PIDFile=/root/trojan-go/src/trojan-go.pid
      8 ExecStart=/root/trojan-go/src/trojan-go -config "/root/trojan-go/src/server.json"
      9 ExecReload=/bin/kill -HUP $MAINPID
     10 Restart=on-failure
     11 RestartSec=10
     12 RestartPreventExitStatus=23
     13 
     14 [Install]
     15 WantedBy=multi-user.target
~                                          

无法启动 
是配置文件改动什么了吗？  
报错
而使用0.6则运行没问题

trojan.service - trojan-go
   Loaded: loaded (/usr/lib/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-06-14 19:17:36 CST; 9s ago
  Process: 10363 ExecStart=/root/trojan-go/src/trojan-go -config /root/trojan-go/src/server.json (code=exited, status=1/FAILURE)
 Main PID: 10363 (code=exited, status=1/FAILURE)

Jun 14 19:17:36 fantastic-light-2.localdomain systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Jun 14 19:17:36 fantastic-light-2.localdomain systemd[1]: Unit trojan.service entered failed state.
Jun 14 19:17:36 fantastic-light-2.localdomain systemd[1]: trojan.service failed.

还有建议 把命令行的参数能写个readme 说明一下吗？  很多参数都和原版trojan不一样，而且还没有说明

**Comment by p4gefau1t** [comment]
1. 请自行查看systemd日志进行排错。如果没有相关运维知识，不建议自行部署服务。

2. 命令行参数请使用-h/--help查看帮助说明，传入任何无效参数也可以触发显示帮助。且readme和文档均有中文说明。

**Comment by jinwyp** [comment]
> 1. 请自行查看systemd日志进行排错。如果没有相关运维知识，不建议自行部署服务。
> 2. 命令行参数请使用-h/--help查看帮助说明，传入任何无效参数也可以触发显示帮助。且readme和文档均有中文说明。

命令行参数 不管是readme 还是 https://p4gefau1t.github.io/trojan-go/developer/overview/ 都没有说明啊 

直接运行./trojan-go -config ./server.json  出现 下面的提示 
[INFO]  2020/06/14 19:30:04 trojan-go v0.7.4 initializing

这是运行成功还是不成功？

**Comment by i553041** [comment]
> (*Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use

(*Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use ＜－－－看这句错误讯息看来是你的443端口被其他程序占用，令trojan-go不能监听443啊。

**Comment by InnocenseYu** [comment]
> > 1. 请自行查看 systemd 日志进行排错。如果没有相关运维知识，不建议自行部署服务。
> > 2. 命令行参数请使用 - h/--help 查看帮助说明，传入任何无效参数也可以触发显示帮助。且 readme 和文档均有中文说明。
> 
> 命令行参数 不管是 readme 还是 https://p4gefau1t.github.io/trojan-go/developer/overview/ 都没有说明啊
> 
> 直接运行./trojan-go -config ./server.json 出现 下面的提示 [INFO] 2020/06/14 19:30:04 trojan-go v0.7.4 initializing
> 
> 这是运行成功还是不成功？
> 
> trojan-go 的 log
> 
> [WARN] 2020/06/14 19:22:13 empty fallback address [WARN] 2020/06/14 19:22:13 empty fallback port [FATAL] 2020/06/14 19:22:13 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:27 cannot verify hostname without sni [WARN] 2020/06/14 19:22:23 empty fallback address [WARN] 2020/06/14 19:22:23 empty fallback port [FATAL] 2020/06/14 19:22:23 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:27 cannot verify hostname without sni [INFO] 2020/06/14 19:22:37 Websocket enabled [INFO] 2020/06/14 19:22:37 Websocket obfuscation enabled [WARN] 2020/06/14 19:22:37 Empty SNI field. Server will not verify the SNI in client hello request [WARN] 2020/06/14 19:22:37 Empty double TLS settings, using global TLS settings [INFO] 2020/06/14 19:22:38 Trojan-Go server is listening on 0.0.0.0:443 [FATAL] 2020/06/14 19:30:04 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use
> 
> 这文档还是老的 根本没说 SNI https://p4gefau1t.github.io/trojan-go/advance/websocket/

你好，问题解决了吗，我下载的trojan-go 0.10.6版本，在Ubuntu 18上启动，报错问题跟你一致
*Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use

**Comment by cwyin7788** [comment]
> 你好，问题解决了吗，我下载的trojan-go 0.10.6版本，在Ubuntu 18上启动，报错问题跟你一致
> 
> *Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use

有程序在占用着443端口，而你的trojan配置档又配置了使用443，所以就出现这个错误了

listen tcp 0.0.0.0:443: bind: address already in use

把trojan-go的端口改为其他的，不要用443看看

**Comment by InnocenseYu** [comment]
> > 你好，问题解决了吗，我下载的 trojan-go 0.10.6 版本，在 Ubuntu 18 上启动，报错问题跟你一致
> > *Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use
> 
> 有程序在占用着 443 端口，而你的 trojan 配置档又配置了使用 443，所以就出现这个错误了
> 
> listen tcp 0.0.0.0:443: bind: address already in use
> 
> 把 trojan-go 的端口改为其他的，不要用 443 看看

谢谢你的回复。作者不是强烈建议使用443端口吗，我使用的是gcp搞的，查看端口占用情况是google和nginx在使用，如果关闭的话可以关闭哪个，关闭后如何补上漏洞呢

root@sg1:~# lsof -i:443
 COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
google_os  1625     root    6u  IPv4 671920      0t0  TCP sg1.asia-southeast1-c.c.vps265.internal:39990->sm-in-f95.1e100.net:https (ESTABLISHED)
google_gu  1791     root    6u  IPv4 671165      0t0  TCP sg1.asia-southeast1-c.c.vps265.internal:39988->sm-in-f95.1e100.net:https (ESTABLISHED)
nginx      9442     root   15u  IPv4 205450      0t0  TCP *:https (LISTEN)
nginx     16988 www-data   15u  IPv4 205450      0t0  TCP *:https (LISTEN)
nginx     16989 www-data   15u  IPv4 205450      0t0  TCP *:https (LISTEN)

**Comment by sjush** [comment]
> > 你好，问题解决了吗，我下载的trojan-go 0.10.6版本，在Ubuntu 18上启动，报错问题跟你一致
> > *Option).Handle:option.go:36 listen tcp 0.0.0.0:443: bind: address already in use
> 
> 有程序在占用着443端口，而你的trojan配置档又配置了使用443，所以就出现这个错误了
> 
> listen tcp 0.0.0.0:443: bind: address already in use
> 
> 把trojan-go的端口改为其他的，不要用443看看

443端口不是用来开https服务的吗，为什么trojan也要运行在443呢，不是一定会冲突么
