### ISSUE TITLE
最新 release 流量统计完全不准确

### ISSUE THREAD

**Issue by betaxab** [p4gefau1t/trojan-go#103]
经测试，最新版流量统计完全不准确，大概差了 30 倍。

下载 1GiB 的测试文件前，流量使用量是 1.19GiB，下载完 1GiB 测试文件后，流量使用量是 31.43GiB。

**Comment by p4gefau1t** [comment]
@betaxab 请提供一下流量测量方式（api/mysql）和日志

**Comment by betaxab** [comment]
不好意思。我再调一下API。issue 先关掉
