### ISSUE TITLE
服务端不改，直接用不了吗？

### ISSUE THREAD

**Issue by duronxx** [p4gefau1t/trojan-go#11]
![image](https://user-images.githubusercontent.com/33643555/77503313-47fbf380-6e98-11ea-8720-1c26e4b70d08.png)

**Comment by duronxx** [comment]
D:\software\trojan-cli_hk>trojan-go  -config config.json
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:41 [0mTrojan-Go initializing...
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:41 [0mrunning client at 127.0.0.1:1080
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).checkAndNewMuxClient:client.go:53 [0mfailed to dial mux conn | cannot dial to the remote server | x509: cannot validate certificate for 35.241.70.89 because it doesn't contain any IP SANs
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:41 [0mconn from 127.0.0.1:57043 tunneling to docs.google.com:443
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).proxyToMuxConn:client.go:86 [0minvalid mux conn
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).checkAndNewMuxClient:client.go:53 [0mfailed to dial mux conn | cannot dial to the remote server | x509: cannot validate certificate for 35.241.70.89 because it doesn't contain any IP SANs
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:41 [0mconn from 127.0.0.1:57057 tunneling to docs.google.com:443
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).proxyToMuxConn:client.go:86 [0minvalid mux conn
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).checkAndNewMuxClient:client.go:53 [0mfailed to dial mux conn | cannot dial to the remote server | x509: cannot validate certificate for 35.241.70.89 because it doesn't contain any IP SANs
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:41 [0mconn from 127.0.0.1:57046 tunneling to clients6.google.com:443
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).proxyToMuxConn:client.go:86 [0minvalid mux conn
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).checkAndNewMuxClient:client.go:53 [0mfailed to dial mux conn | cannot dial to the remote server | x509: cannot validate certificate for 35.241.70.89 because it doesn't contain any IP SANs
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:41 [0mconn from 127.0.0.1:57052 tunneling to clients6.google.com:443
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:41 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).proxyToMuxConn:client.go:86 [0minvalid mux conn
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:42 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).checkAndNewMuxClient:client.go:53 [0mfailed to dial mux conn | cannot dial to the remote server | x509: cannot validate certificate for 35.241.70.89 because it doesn't contain any IP SANs
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:42 [0mconn from 127.0.0.1:57063 tunneling to clients6.google.com:443
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:42 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).proxyToMuxConn:client.go:86 [0minvalid mux conn
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:42 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).checkAndNewMuxClient:client.go:53 [0mfailed to dial mux conn | cannot dial to the remote server | x509: cannot validate certificate for 35.241.70.89 because it doesn't contain any IP SANs
[0;32m[INFO]  [0m[0;34m2020/03/25 12:53:42 [0mconn from 127.0.0.1:57067 tunneling to clients6.google.com:443
[0;31m[ERROR] [0m[0;34m2020/03/25 12:53:42 [0m[0;33mgithub.com/p4gefau1t/trojan-go/proxy.(*Client).proxyToMuxConn:client.go:86 [0minvalid mux conn

**Comment by p4gefau1t** [comment]
这个应该是配置文件缺少了SNI字段

**Comment by p4gefau1t** [comment]
因为域名认证默认是开启的，所以不提供SNI会导致证书检验失败。你可以选择提供一个与服务器证书CN相同的SNI（通常是域名），或者关闭证书认证

**Comment by p4gefau1t** [comment]
这个是客户端证书校验的问题，和服务端是否使用trojan-go没有太大关系

**Comment by p4gefau1t** [comment]
哦对了，即使正确配置了你的SNI，你的客户端配置开启了多路复用，原版Trojan并不支持这个特性，所以也无法连接

**Comment by duronxx** [comment]
哦，好的，谢谢

**Comment by duronxx** [comment]
就是要把trojan服务端改成trojan-go版本的？

**Comment by p4gefau1t** [comment]
如果你需要使用多路复用，必须使用trojan-go，其他情况下都是兼容的

**Comment by p4gefau1t** [comment]
顺带一提，新的版本已经修复了windows输出乱码的问题
