### ISSUE TITLE
请问，创建证书出错，怎么解决

### ISSUE THREAD

**Issue by limobai2333** [p4gefau1t/trojan-go#111]
输入sudo trojan-go -autocert request    就出现这个了，一开始以为64位不支持，换32位，也是同样问题
![photo_2020-06-18_10-34-03](https://user-images.githubusercontent.com/65392605/84971351-1c16a400-b14f-11ea-8371-d4ed6043b92a.jpg)

**Comment by tomxiang1** [comment]
> 输入sudo trojan-go -autocert request 就出现这个了，一开始以为64位不支持，换32位，也是同样问题
> ![photo_2020-06-18_10-34-03](https://user-images.githubusercontent.com/65392605/84971351-1c16a400-b14f-11ea-8371-d4ed6043b92a.jpg)

兄弟别纠结了，证书还是用acme.sh脚本生成吧，用专业工具做专业的事。个人建议，仅供参考。

**Comment by p4gefau1t** [comment]
1. 请检查你下载的可执行文件的目标平台是否和你的机器操作系统和架构相同

2. 证书申请已经不再被支持
