### ISSUE TITLE
[BUG] 升级后出现这个问题  旧版是可以用的

### ISSUE THREAD

**Issue by cutepan** [p4gefau1t/trojan-go#113]
[ERROR] 2020/06/21 15:55:09 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:99 tls client hello with wrong sni from | sni mismatched: null, expected:

**Comment by p4gefau1t** [comment]
配置不当，错误提示已经足够清晰。请自行查阅文档。
