### ISSUE TITLE
[Future] 希望SSL Report能达到A+

### ISSUE THREAD

**Issue by tomxiang1** [p4gefau1t/trojan-go#114]
![image](https://user-images.githubusercontent.com/45867336/85257234-15ae6200-b498-11ea-9dd2-ed2766ad3859.png)
![image](https://user-images.githubusercontent.com/45867336/85257376-5908d080-b498-11ea-9919-4f4b481cf697.png)
检测地址https://www.ssllabs.com/ssltest/index.html

**Comment by i553041** [comment]
> ![image](https://user-images.githubusercontent.com/45867336/85257234-15ae6200-b498-11ea-9dd2-ed2766ad3859.png)
> ![image](https://user-images.githubusercontent.com/45867336/85257376-5908d080-b498-11ea-9919-4f4b481cf697.png)
> 检测地址https://www.ssllabs.com/ssltest/index.html

HSTS是在webserver里例如nginx内设置的，

至於Session resumption (caching) | No (IDs empty)

和是否A+是无关的，因为我的也是No，但我的网站是A+，要A+，请将ssllab test里侦测出来，不安全的cipher suite拿掉(橙色的)，只剩下绿色的：

![image](https://user-images.githubusercontent.com/53026952/85485879-34c60480-b5fc-11ea-90f9-25bb2b1fb1d4.png)

但就算A+ ，Key Exchange和Cipher Strength，都还不能拿到全满分。

以前用trojan-gfw时，我能拿到A+所有绿色条全满分，但要这样做：

1.)网站证书的长度ECC的要384 ／ RSA要4096

2.)用openssl gen一个dhparam.pem出来，长度要4096的

3.)在nginx或其他web server加上类似选项：

ssl_ecdh_curve secp384r1;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;

4.)最主要是要拿走这个TLS 1.3 cipher suite : TLS_AES_128_GCM_SHA256

=====================================================

ssllab test应该是认为这个TLS_AES_128_GCM_SHA256在Key Exchange和Cipher suite不够强，所以尽管拿到A+，但如果有使用这个cipher suite的话，还是会在这两项扣分。

顺便留言一下给trojan-go的开发者大人，trojan-gfw使用TLS 1.3能容许不执行这个cipher suite：TLS_AES_128_GCM_SHA256，但trojan-go，尽管我只是设置了TLS_CHACHA20_POLY1305_SHA256 / TLS_AES_256_GCM_SHA384，但这个cipher suite还是预设执行的，所以我的网站也拿不到A+加全满分了。

![image](https://user-images.githubusercontent.com/53026952/85486798-efa2d200-b5fd-11ea-9c3b-4a9e5475fe79.png)

我觉得trojan-go比原版更好用，如果可以给我们这个小小的方便，让网站能拿到A+加全满分，那就完美了。

先谢过所有trojan-go的开发者了。

**Comment by p4gefau1t** [comment]
@i553041 如果你在配置文件在cipher13填写的套件名，请改成在cipher字段填写

**Comment by i553041** [comment]
> @i553041 如果你在配置文件在cipher13填写的套件名，请改成在cipher字段填写

感谢开发者大人的快速回覆，我试过您的建议了，做过这2个改动：

1.)将"cipher_tls13": "",里的TLS 1.3字段清空，将这两个强一些的ciphers：TLS_CHACHA20_POLY1305_SHA256 / TLS_AES_256_GCM_SHA384加在"cipher":里，但不成。

2.)和上面步骤差不多，但我将"cipher_tls13":这一句完全删除，也一样不成。

1，2两个步骤完成后，都再执行了ssllab test (Clear cache)，重测一次，但TLS 1.3这个差一些的cipher suite TLS_AES_128_GCM_SHA256 ，还是会被预设执行。

网站还是达不到A+加全满分。

**Comment by tomxiang1** [comment]
经过实测nginx增加以下配置后已经可以达到A+
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; ";
![image](https://user-images.githubusercontent.com/45867336/87512098-068e8e80-c6a9-11ea-9774-2664cc362c39.png)
