### ISSUE TITLE
[BUG]0.7.x IP数限制失效

### ISSUE THREAD

**Issue by doraeden** [p4gefau1t/trojan-go#118]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
0.7.x重构代码以后服务端IP数限制失效，首先在把IP记录进去的时候是"IP:源端口"这种的格式，而不是IP，在自行修复以后还发现了其它的问题。
如果正常的退出客户端，TCP连接就能正常的关闭，并记录消耗的流量，删除在线的IP，如果客户端没有正常的退出或者客户端IP地址变了，就不会记录消耗的流量和删除在线的IP，导致用户在变更几次IP后无法使用。

# 如何复现这个 Bug：
更换客户端的公网的IP，并且非正常的退出客户端

### 服务端和客户端日志

粘贴**故障发生时**，服务端和客户端日志

### 服务端和客户端配置文件

可以复现该问题的客户端和服务端的完整配置

### 服务端和客户端版本信息
v0.7.6

### 其他信息

你认为对我们修复bug有帮助的任何信息都可以在这里写出来

**Comment by p4gefau1t** [comment]
> 首先在把IP记录进去的时候是"IP:源端口"这种的格式

这是一个bug，dev上的版本已经修复

> 如果正常的退出客户端，TCP连接就能正常的关闭，并记录消耗的流量，删除在线的IP，如果客户端没有正常的退出或者客户端IP地址变了，就不会记录消耗的流量和删除在线的IP，导致用户在变更几次IP后无法使用。

修复之后本地调试没有复现。因为不清楚你修改了哪里的代码，我猜测你可能没有在tunnel/trojan/server.Close处做处理。

**Comment by doraeden** [comment]
谢谢，确实没有问题了，是我没处理Close
