### ISSUE TITLE
[BUG] v0.7.7版client端配置了的cipher和cipher_tls13属性无效果。

### ISSUE THREAD

**Issue by tomxiang1** [p4gefau1t/trojan-go#120]
v0.7.7版client端配置了的cipher和cipher_tls13属性无效果。
![image](https://user-images.githubusercontent.com/45867336/85973896-b788fe00-ba06-11ea-8235-867e1b89f538.png)
client hello 抓包结果

![image](https://user-images.githubusercontent.com/45867336/85974140-54e43200-ba07-11ea-8f59-ae9a4f3d35df.png)
client的实际配置

**Comment by p4gefau1t** [comment]
@tomxiang1 请阅读文档关于fingerprint的说明

**Comment by tomxiang1** [comment]
> fingerprint

![image](https://user-images.githubusercontent.com/45867336/85978954-3f283a00-ba12-11ea-9405-315c49e5bb21.png)
![image](https://user-images.githubusercontent.com/45867336/85979217-a0e8a400-ba12-11ea-8458-c26ee34b3dcb.png)

增加了"fingerprint":""属性，但cipher_tls13属性没效果，并且tls13的协议没有靠前。

**Comment by p4gefau1t** [comment]
cipher_tls13已经和cipher合并，请仔细阅读文档

**Comment by i553041** [comment]
> > fingerprint
> 
> ![image](https://user-images.githubusercontent.com/45867336/85978954-3f283a00-ba12-11ea-9405-315c49e5bb21.png)
> ![image](https://user-images.githubusercontent.com/45867336/85979217-a0e8a400-ba12-11ea-8458-c26ee34b3dcb.png)
> 
> 增加了"fingerprint":""属性，但cipher_tls13属性没效果，并且tls13的协议没有靠前。

我在你另一个issue，不就说过了吗？TLS 1.3有这个小问题：

https://github.com/p4gefau1t/trojan-go/issues/114#issuecomment-648531093

<img width="749" alt="截图 2020-06-30 上午7 41 55" src="https://user-images.githubusercontent.com/53026952/86066637-4e0bfc80-baa5-11ea-8740-cfa5a4a35fcf.png">

我相信开发者正在处理这个问题，因为你那个issue还没关闭。

如果你只想SSLLAB test的测试结果好看，那你就暂时用回trojan-gfw吧，trojan-gfw是可以独立指定执行这两个TLS_CHACHA20_POLY1305_SHA256 / TLS_AES_256_GCM_SHA384 TLS1.3的ciphers suite。那你的网站就能A+，再加上4条绿色条全满分了。

以前用trojan-gfw时的截图：

![image](https://user-images.githubusercontent.com/53026952/86066863-e609e600-baa5-11ea-8a7a-976380f1c1aa.png)

**Comment by tomxiang1** [comment]
@i553041 厉害呀兄弟，Trojan-go功能比Trojan-gfw强大很多，就是配置变化太快我都跟不上了，的确把tls1.3的协议配置到cipher属性中也是无效的，应该是BUG。

**Comment by i553041** [comment]
> @i553041 厉害呀兄弟，Trojan-go功能比Trojan-gfw强大很多，就是配置变化太快我都跟不上了，的确把tls1.3的协议配置到cipher属性中也是无效的，应该是BUG。有图有真相
> ![image](https://user-images.githubusercontent.com/45867336/86076703-2032b200-babd-11ea-80d7-e3fb1294dbd1.png)
> ![image](https://user-images.githubusercontent.com/45867336/86075953-c7aee500-babb-11ea-8346-8a9a7d65c5f2.png)

所以暂时的方案就只有等开发者修正这个问题，或者是用回trojan-gfw了。

我觉得开发者应该知道这个小问题的啦，已经在处理的了。

**Comment by p4gefau1t** [comment]
配置了一项cipher之后其他tls1.3的cipher被一并附加上，这个有可能是上游的tls库的问题

**Comment by i553041** [comment]
> 配置了一项cipher之后其他tls1.3的cipher被一并附加上，这个有可能是上游的tls库的问题

请问上游TLS库是指？

同样环境，只是套件不同，trojan-gfw不会“配置了一项cipher之后其他tls1.3的cipher被一并附加上”啊。

trojan-go却会这样啊。

如果是“上游TLS库”的问题，要怎么解决了呢？

谢！

**Comment by p4gefau1t** [comment]
@i553041 指go官方tls库。这个和trojan原版没有关系，因为trojan原版是基于openssl，而trojan-go用的是go官方tls库，和utls库（客户端）
