### ISSUE TITLE
API开启TLS双向认证

### ISSUE THREAD

**Issue by yyq582922811** [p4gefau1t/trojan-go#121]
在我没开启API双向认证时，其它的Trojan-go实例可以通过IP加端口访问到我的用户信息，但在我开启TLS双向认证后，请问是否需要配置nginx，当我想使用另一个Trojan-Go实例控制它时,出现connection closed错误，请问是需要添加客户端的-cert和-key么，可以请为我提供一个正确的写法。

**Comment by p4gefau1t** [comment]
api客户端还没实现tls相关功能

**Comment by yyq582922811** [comment]
@p4gefau1t 请问目前是服务端开启API双向认证后，不支持其他Trojan-go实例控制它么

**Comment by p4gefau1t** [comment]
@yyq582922811 目前不支持，不过稍作修改就能支持

**Comment by yyq582922811** [comment]
@p4gefau1t 非常感谢您及时的答复，我发现在api动态管理用户的说明中，添加用户信息有点问题，是否应该改为 ./trojan-go -api-addr 127.0.0.1:10000 -api set -add-profile -target-password password  修改为set可以添加新用户，但我不知道这些用户加在了哪里，这个profile的位置
![1593506580(1)](https://user-images.githubusercontent.com/50658837/86104712-00b57c80-baf1-11ea-90f4-eda0e4f62da4.jpg)

**Comment by p4gefau1t** [comment]
这个是笔误，感谢指出

**Comment by yyq582922811** [comment]
@p4gefau1t 请问在升级0.8版本后，服务端开启双向认证其他trojan-go实例无法控制它，Trojan-Go实例该如何配置证书才能控制这个Trojan-Go服务器。
![1594709926(1)](https://user-images.githubusercontent.com/50658837/87394879-f8763a80-c5e2-11ea-81f3-4b6a4bbf6062.png)
![1594710037(1)](https://user-images.githubusercontent.com/50658837/87394882-fa3ffe00-c5e2-11ea-8411-033f458e12ab.jpg)
![1594709999(1)](https://user-images.githubusercontent.com/50658837/87394886-fc09c180-c5e2-11ea-9b62-a934eabdcf37.png)
