### ISSUE TITLE
Use project as Go library

### ISSUE THREAD

**Issue by maddie** [p4gefau1t/trojan-go#123]
Is it possible to use this project as a library? I'm trying to use this library as a Trojan client, but it seems it isn't very straightforward to do so.

It would be great to have some instructions about this.

Thanks!

**Comment by Qv2ray-dev** [comment]
cgo might be a good choice if you are developing in c/cpp
Note that a special hack is required to link cgo object file togetger with msvc .obj.

For other languages (except go). Directly bundle the binary is my suggested idea.

**Comment by maddie** [comment]
I'm developing in Go, what I mean is importing this project and use it as a library.

What I'm planning is using a Trojan client as an HTTP client transport and make requests via the proxy.

**Comment by maddie** [comment]
Okay, I kinda figured out how it works, but with the below example code, the HTTP request simply returns `io.EOF`, and it seems the Trojan client wasn't connected to the server-side.

```
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"net"
	"net/http"
	"strconv"
	"time"

	"github.com/p4gefau1t/trojan-go/config"
	"github.com/p4gefau1t/trojan-go/statistic/memory"
	"github.com/p4gefau1t/trojan-go/tunnel"
	"github.com/p4gefau1t/trojan-go/tunnel/freedom"
	"github.com/p4gefau1t/trojan-go/tunnel/trojan"
)

type ConnWrap struct {
	c *trojan.Client
}

func (cw *ConnWrap) DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
	host, port, err := net.SplitHostPort(addr)
	if err != nil {
		return nil, err
	}

	p, err := strconv.Atoi(port)
	if err != nil {
		return nil, err
	}

	return cw.c.DialConn(&tunnel.Address{
		DomainName:  host,
		Port:        p,
		AddressType: tunnel.DomainName,
	}, nil)
}

func main() {
	freedomConfig := &freedom.Config{}
	freedomCtx := config.WithConfig(context.Background(), freedom.Name, freedomConfig)
	freedomClient, err := freedom.NewClient(freedomCtx, nil)
	if err != nil {
		panic(err)
	}
	defer freedomClient.Close()

	authConfig := &memory.Config{Passwords: []string{"hunter2"}}
	authCtx := config.WithConfig(context.Background(), memory.Name, authConfig)

	trojanConfig := &trojan.Config{
		LocalHost:  "",
		LocalPort:  0,
		RemoteHost: "example.com",
		RemotePort: 443,
	}
	trojanCtx := config.WithConfig(authCtx, trojan.Name, trojanConfig)

	c, err := trojan.NewClient(trojanCtx, freedomClient)
	if err != nil {
		panic(err)
	}
	defer c.Close()


	http.DefaultClient.Transport = &http.Transport{
		Proxy:                 http.ProxyFromEnvironment,
		DialContext:           (&ConnWrap{c}).DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
	}

	resp, err := http.DefaultClient.Get("https://www.google.com")
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	b, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s\n", b)
}
```

Is there anything I've done wrong here?

**Comment by p4gefau1t** [comment]
Here's an example

```
p, err := proxy.NewProxyFromConfigData(configBytes, true)
p.Run()
```

where package "proxy" is from "github.com/p4gefau1t/trojan-go/proxy"

And don't forget to import  "client" and "memory" modules

```
	_ "github.com/p4gefau1t/trojan-go/proxy/client"
	_ "github.com/p4gefau1t/trojan-go/statistic/memory"
```

**Comment by maddie** [comment]
Hmm, I was thinking I could just let the HTTP client use the Trojan's proxied connection instead of creating a Trojan server and connect to it. Is this possible?

**Comment by p4gefau1t** [comment]
It's possible, technically speaking. But you should figure out how the protocol stack works before doing this (see proxy.go). The simplest way is launching a complete trojan-go client instance.

**Comment by maddie** [comment]
Thanks for the pointer, I'll look into it.

The reason why I'm reluctant to launching a complete instance is that it would have to listen to a port. I don't want it to be exposed to any external access (even 127.0.0.1).
