### ISSUE TITLE
0.7.8版本UDP出现错误unable to read ATYPE | EOF

### ISSUE THREAD

**Issue by fyhqycom** [p4gefau1t/trojan-go#129]
2边都是0.7.8版本
客户端日记
`[DEBUG] 2020/07/10 09:58:37 github.com/p4gefau1t/trojan-go/tunnel/adapter.(*Server).acceptConnLoop:server.go:49 socks5 connection
[INFO]  2020/07/10 09:58:37 socks connection from 192.168.50.160:64748 metadata www.baidu.com:80
[DEBUG] 2020/07/10 09:58:38 github.com/p4gefau1t/trojan-go/tunnel/adapter.(*Server).acceptConnLoop:server.go:49 socks5 connection
[INFO]  2020/07/10 09:58:38 socks connection from 192.168.50.160:64749 metadata 0.0.0.0:0
[ERROR] 2020/07/10 09:58:38 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 192.168.50.91:51837->192.168.50.160:64748: read: connection reset by peer
[DEBUG] 2020/07/10 09:58:38 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:87 conn relay ends
[INFO]  2020/07/10 09:58:38 connection to www.baidu.com:80 closed sent: 0 B recv: 2.00 KiB
[DEBUG] 2020/07/10 09:58:38 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).packetDispatchLoop:server.go:128 socks recv udp packet from 192.168.50.160:63490
[INFO]  2020/07/10 09:58:38 socks new udp session from 192.168.50.160:63490
[DEBUG] 2020/07/10 09:58:38 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*PacketConn).WriteWithMetadata:packet.go:51 udp packet remote 18.162.47.12:1221 metadata 114.114.114.114:53 size 27
[DEBUG] 2020/07/10 09:58:41 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).acceptLoop.func1:server.go:230 socks udp session ends
[DEBUG] 2020/07/10 09:58:41 github.com/p4gefau1t/trojan-go/tunnel/adapter.(*Server).acceptConnLoop:server.go:49 socks5 connection
[INFO]  2020/07/10 09:58:41 socks connection from 192.168.50.160:64750 metadata 0.0.0.0:0
[DEBUG] 2020/07/10 09:58:41 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).packetDispatchLoop:server.go:128 socks recv udp packet from 192.168.50.160:63492
[INFO]  2020/07/10 09:58:41 socks new udp session from 192.168.50.160:63492
[DEBUG] 2020/07/10 09:58:41 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*PacketConn).WriteWithMetadata:packet.go:51 udp packet remote 18.162.47.12:1221 metadata 8.8.8.8:53 size 28
[INFO]  2020/07/10 09:58:43 socks udp session timeout, closed
[ERROR] 2020/07/10 09:58:43 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 socks packet conn closed
[DEBUG] 2020/07/10 09:58:43 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:147 packet relay ends
[INFO]  2020/07/10 09:58:43 connection to UDP_CONN:0 closed sent: 0 B recv: 0 B
[DEBUG] 2020/07/10 09:58:44 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).acceptLoop.func1:server.go:230 socks udp session ends
[DEBUG] 2020/07/10 09:58:44 github.com/p4gefau1t/trojan-go/tunnel/adapter.(*Server).acceptConnLoop:server.go:49 socks5 connection
[INFO]  2020/07/10 09:58:44 socks connection from 192.168.50.160:64751 metadata 0.0.0.0:0
[DEBUG] 2020/07/10 09:58:44 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).packetDispatchLoop:server.go:128 socks recv udp packet from 192.168.50.160:63494
[INFO]  2020/07/10 09:58:44 socks new udp session from 192.168.50.160:63494
[DEBUG] 2020/07/10 09:58:44 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*PacketConn).WriteWithMetadata:packet.go:51 udp packet remote 18.162.47.12:1221 metadata 208.67.222.222:53 size 31
[INFO]  2020/07/10 09:58:46 socks udp session timeout, closed
[ERROR] 2020/07/10 09:58:46 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 socks packet conn closed
[DEBUG] 2020/07/10 09:58:46 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:147 packet relay ends
[INFO]  2020/07/10 09:58:46 connection to UDP_CONN:0 closed sent: 0 B recv: 0 B
[DEBUG] 2020/07/10 09:58:47 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).acceptLoop.func1:server.go:230 socks udp session ends
[DEBUG] 2020/07/10 09:58:47 github.com/p4gefau1t/trojan-go/tunnel/adapter.(*Server).acceptConnLoop:server.go:49 socks5 connection
[INFO]  2020/07/10 09:58:47 socks connection from 192.168.50.160:64752 metadata 0.0.0.0:0
[DEBUG] 2020/07/10 09:58:47 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).packetDispatchLoop:server.go:128 socks recv udp packet from 192.168.50.160:63496
[INFO]  2020/07/10 09:58:47 socks new udp session from 192.168.50.160:63496
[DEBUG] 2020/07/10 09:58:47 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*PacketConn).WriteWithMetadata:packet.go:51 udp packet remote 18.162.47.12:1221 metadata 223.5.5.5:53 size 26
[INFO]  2020/07/10 09:58:49 socks udp session timeout, closed
[ERROR] 2020/07/10 09:58:49 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 socks packet conn closed
[DEBUG] 2020/07/10 09:58:49 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:147 packet relay ends
[INFO]  2020/07/10 09:58:49 connection to UDP_CONN:0 closed sent: 0 B recv: 0 B
[DEBUG] 2020/07/10 09:58:50 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).acceptLoop.func1:server.go:230 socks udp session ends
[DEBUG] 2020/07/10 09:58:50 github.com/p4gefau1t/trojan-go/tunnel/adapter.(*Server).acceptConnLoop:server.go:49 socks5 connection
[INFO]  2020/07/10 09:58:50 socks connection from 192.168.50.160:64753 metadata 0.0.0.0:0
[DEBUG] 2020/07/10 09:58:50 github.com/p4gefau1t/trojan-go/tunnel/socks.(*Server).acceptLoop.func1:server.go:230 socks udp session ends
[INFO]  2020/07/10 09:58:52 socks udp session timeout, closed
[ERROR] 2020/07/10 09:58:52 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 socks packet conn closed
[DEBUG] 2020/07/10 09:58:52 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:147 packet relay ends
[INFO]  2020/07/10 09:58:52 connection to UDP_CONN:0 closed sent: 0 B recv: 0 B`

服务端日记
`[ERROR] 2020/07/10 09:58:48 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYPE | EOF
[ERROR] 2020/07/10 09:58:51 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYPE | EOF
[ERROR] 2020/07/10 09:58:54 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYPE | EOF
[ERROR] 2020/07/10 09:58:57 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYPE | EOF
User(34bb104c29a6f61586408a0866e333b81c2a8a1bed2ea8be3f0e7829): Inband: 8192, Outband: 497`

**Comment by p4gefau1t** [comment]
判断udp会话是否断开只能依靠超时机制，当超过一定时间无活跃udp包流过隧道，隧道会被强制关闭，打印一个错误日志，这个不是bug
