### ISSUE TITLE
是否能够对ip limit、speed limit等进行持久化？

### ISSUE THREAD

**Issue by kyoa** [p4gefau1t/trojan-go#131]
如题，这些设置一旦重启trojan-go就失效了

**Comment by p4gefau1t** [comment]
@kyoa 不能。这是有意设计的。数据的持久化和更新应该由外部数据库和对接的API客户端完成，以保持最大的灵活性。

**Comment by kyoa** [comment]
> @kyoa 不能。这是有意设计的。数据的持久化和更新应该由外部数据库和对接的API客户端完成，以保持最大的灵活性。

好吧，能不能不通过命令行来调用这些设置

**Comment by p4gefau1t** [comment]
@kyoa 不太明白。你可以使用gRPC进行对接。

**Comment by kyoa** [comment]
> @kyoa 不太明白。你可以使用gRPC进行对接。

看来得学习一下gRPC，不是很懂这个，这个不需要通过excuteCommand函数来执行吧

**Comment by p4gefau1t** [comment]
@kyoa 和命令行没有关系。
