### ISSUE TITLE
用户登陆时是否能够从外部获取到通知

### ISSUE THREAD

**Issue by kyoa** [p4gefau1t/trojan-go#135]
如题，可以了解用户的在线状态等

**Comment by p4gefau1t** [comment]
目前的模型是通过轮询取得状态

**Comment by kyoa** [comment]
> 目前的模型是通过轮询取得状态

那外部调用的话能获得状态吗

**Comment by p4gefau1t** [comment]
可以取得用户相关状态信息，参见文档

**Comment by kyoa** [comment]
好的，谢谢

**Comment by kyoa** [comment]
> 可以取得用户相关状态信息，参见文档

看了一下文档，你是指通过api list轮询来进行用户状态维护吧

**Comment by p4gefau1t** [comment]
gRPC的接口参见api/service/api.proto，list只是其中之一
