### ISSUE TITLE
双网卡客户端局域网共享问题

### ISSUE THREAD

**Issue by mchlwang** [p4gefau1t/trojan-go#138]
客户端有两张网卡，IP分别为192.168.\*.\*和10.0.\*.\*，local_addr设置为0.0.0.0开启局域网共享，结果只有192.168.\*.\*的局域网设备共享成功。测试shadowsocks-windows两个局域网都是可以共享的。

**Comment by p4gefau1t** [comment]
无法复现，请提供故障时日志和配置文件信息，并详细描述网络环境和连接设备

**Comment by mchlwang** [comment]
我检查了防火墙设置，另外一张网卡的网络配置从公共改为专用后局域网共享就成功了
