### ISSUE TITLE
kill 掉进程之后，再启动报错

### ISSUE THREAD

**Issue by thinker007** [p4gefau1t/trojan-go#15]
kill 掉进程之后报错
unexpected fault address 0x0
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x0 pc=0x110021d0001761]

goroutine 1 [running, locked to thread]:
runtime.throw(0x5da897, 0x5)
	/snap/go/5569/src/runtime/panic.go:1114 +0x54 fp=0x400005edb0 sp=0x400005ed80 pc=0x40a24
runtime.sigpanic()
	/snap/go/5569/src/runtime/signal_unix.go:692 +0x424 fp=0x400005ede0 sp=0x400005edb0 pc=0x57184
go.starlark.net/starlark.init()
	/home/p4gefau1t/go/pkg/mod/go.starlark.net@v0.0.0-20190225160109-1174b2613e82/starlark/int.go:161 +0x58 fp=0x400005ee50 sp=0x400005edf0 pc=0x4770e8
runtime: unexpected return pc for runtime.doInit called from 0x0

**Comment by p4gefau1t** [comment]
日志看起来似乎不是很完整，看起来似乎是依赖的bug
可以提供一下配置和平台信息吗

**Comment by thinker007** [comment]
平台：asus AC86u
正常可以启动，就是kill掉进程不能再次启动，报错线程锁定。

**Comment by p4gefau1t** [comment]
有更详细的配置信息和日志信息吗，这份日志信息太少了

**Comment by thinker007** [comment]
再次碰到的时候给你哈，后面就没有复现了

**Comment by p4gefau1t** [comment]
好的
