### ISSUE TITLE
QUIC support

### ISSUE THREAD

**Issue by pram991** [p4gefau1t/trojan-go#150]
It would be great to support QUIC as a transportation protocol for torjan.
https://www.v2ray.com/chapter_02/transport/quic.html

**Comment by p4gefau1t** [comment]
目前没有计划支持。Trojan-Go 传输层必须基于常见的传输协议（如 TLS）以混入正常网络流量，QUIC 目前并不普及，不符合这一基本要求。如果必须使用 QUIC 进行传输，请参考文档的“可插拔传输层”一节进行插件开发。
