### ISSUE TITLE
关于api的使用

### ISSUE THREAD

**Issue by hahaleyile** [p4gefau1t/trojan-go#152]
您好，我仔细读了您的文档好几遍，发现关于api这一部分有点不太清楚。
比如，api添加的用户信息放在哪？如果需要自己配置是否在配置文件中指定了数据库就可以了？
还有api的命令用法感觉不是很清楚，添加一个用户只有密码没有用户名吗？
感谢您能抽空解答

**Comment by Wanhos** [comment]
我有同样的疑问，并且我在设置api中ssl的enabled参数为true时，无法使用其他trojan-go实例去控制它。

**Comment by p4gefau1t** [comment]
1. 全部在内存中。Trojan-Go 的 API 被设计为仅处理和存储尽可能少的数据，持久化工作以及管理逻辑全部交由外部处理，以期保持尽可能高的灵活性。

2. Trojan 协议鉴权仅需密码（的散列值），如果需要维护用户名和密码的映射关系，请在对接程序中自行维护，理由同上

3. API 服务端可以正常使用 TLS，但由于集成的 API 客户端还未支持 TLS ，所以 API 客户端无法与服务端通讯，未来可能追加这个功能。

**Comment by Wanhos** [comment]
@p4gefau1t 请问是目前API 服务端开启 TLS，可以使用其它Trojan-go服务端去控制它吗

**Comment by hahaleyile** [comment]
> 1. 全部在内存中。Trojan-Go 的 API 被设计为仅处理和存储尽可能少的数据，持久化工作以及管理逻辑全部交由外部处理，以期保持尽可能高的灵活性。
> 
> 2. Trojan 协议鉴权仅需密码（的散列值），如果需要维护用户名和密码的映射关系，请在对接程序中自行维护，理由同上
> 
> 3. API 服务端可以正常使用 TLS，但由于集成的 API 客户端还未支持 TLS ，所以 API 客户端无法与服务端通讯，未来可能追加这个功能。
> 

明白了，谢谢。不过如果不能持久化，那么获取用户信息api会不会就比较鸡肋了

**Comment by p4gefau1t** [comment]
@hahaleyile 不会。trojan-go 还维护着流量等用户信息。外界通过 API 才能方便获取。
