### ISSUE TITLE
[BUG]UDP forward或者透明代理有bug

### ISSUE THREAD

**Issue by nebulabox** [p4gefau1t/trojan-go#155]
通过设置trojan go nat模式，试图直接在路由器上进行xbox游戏udp包转发，如果trojan go配置包含route，100%丢包失败。删除route部分，可以成功转发upd包。

**Comment by p4gefau1t** [comment]
route 部分应当被禁止在 nat 和 forward 模式下使用，下个版本会加上检查

**Comment by quyunet** [comment]
> route 部分应当被禁止在 nat 和 forward 模式下使用，下个版本会加上检查

那只能坐等新版本了，加油，支持！

**Comment by quyunet** [comment]
> route 部分应当被禁止在 nat 和 forward 模式下使用，下个版本会加上检查

最新版本0.8.2不支持NAT模式使用路由了吗？将路由设为启用后trojan-go无法正常启动了。

**Comment by widewind2015** [comment]
> > route 部分应当被禁止在 nat 和 forward 模式下使用，下个版本会加上检查
> 
> 最新版本0.8.2不支持NAT模式使用路由了吗？将路由设为启用后trojan-go无法正常启动了。

在 NAT模式时删除route 部分配置即可。
