### ISSUE TITLE
[BUG]trojan go服务器端重启，导致udp通道不能连接

### ISSUE THREAD

**Issue by nebulabox** [p4gefau1t/trojan-go#158]
不确定是trojan go的bug，还是tinyfecvpn的bug。
tinfecvpn client -> trojan go forward -> trojan go server -> tinfecvpn server 
正常联通之后ping可以通。但是一旦restart trojan go server, 马上整个通路就断了。ping会block无限期。
尝试restart tinfecvpn client，无效。 尝试restart trojan go forward，马上网络恢复。

**Comment by p4gefau1t** [comment]
没有提供有效信息。issue 关闭。
