### ISSUE TITLE
请问配置文件中如何使用环境变量

### ISSUE THREAD

**Issue by deeyi2000** [p4gefau1t/trojan-go#159]

**Comment by nebulabox** [comment]
一个方法是启动服务之前，通过脚本修改配置文件。

**Comment by deeyi2000** [comment]
是否可以增加json配置文件里的环境变量支持？

**Comment by p4gefau1t** [comment]
没有包含足够的信息。同时我无法理解你们的对话。

**Comment by alvinwangs** [comment]
我也有同样的需求，我期望通过环境变量来指定证书的路径。
期望如下：
![image](https://user-images.githubusercontent.com/43318274/102594328-00697600-4151-11eb-8290-65c596af9796.png)
