### ISSUE TITLE
X86版本CPU负载很高

### ISSUE THREAD

**Issue by ju0594** [p4gefau1t/trojan-go#16]
![X86_CPU负载高.png](https://i.loli.net/2020/04/13/yvdrQFmxg4N6XHu.png)

因为VPS的内存小,想尽可能的优化内存占用,在Debian 7 X86下,trojan-go跑200M带宽占用了80%的CPU.
然后在Debian 8 X64试了下,发现X64版没有这个问题,占用只在20%左右.
这个是因为32位性能不如64位吗?

**Comment by ju0594** [comment]
似乎和默认配置的SSL加密方式有关

这是我的配置

```
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "123456"
    ],
    "ssl": {
        "cert": "/root/ssl/cert.pem",
        "key": "/root/ssl/key.pem"
    }
}

```

**Comment by p4gefau1t** [comment]
不填写cipher的情况下，使用的加密方式是按照机器平台自动选择的

从你的描述来看，应该是Golang的密码学库没有使用硬件AES加速，而是用软件方法进行相关计算，因此效率比较低

密码学库没有使用AES指令集的原因有可能是你选择了x86操作系统，或是你的硬件平台不支持相关硬件加速功能

**Comment by ju0594** [comment]
> 不填写cipher的情况下，使用的加密方式是按照机器平台自动选择的
> 
> 从你的描述来看，应该是Golang的密码学库没有使用硬件AES加速，而是用软件方法进行相关计算，因此效率比较低
> 
> 密码学库没有使用AES指令集的原因有可能是你选择了x86操作系统，或是你的硬件平台不支持相关硬件加速功能

反复测试了,VPS是支持AES的,改了改配置也还是那样,然后我拿官方源码试着编译了32位,Debian7和8,32位和64位系统下测试了,CPU使用率差距都在两倍以上,本地也用虚拟机测了,一样的结果,也不知道是什么蜜汁问题哈哈,最后还是决定放弃32位系统了...
