### ISSUE TITLE
trojan-go转发v2 websocket流量给nginx后，nginx / v2的log全都是127.0.0.1

### ISSUE THREAD

**Issue by i553041** [p4gefau1t/trojan-go#161]
我现时在一台机器上并存了trojan-go / v2及nginx
次序如下：

trojan-go(443) -> Nginx(80) -> v2 (ws : 17989)

即是将trojan-go的local 端口设为443、remote端口设为 80

使用上正常，但trojan-go将v2数据分流给nginx 80，nginx再转发给v2后，v2日志档里的客户端IP，nginx日志档里的client IP，全都变成是127.0.0.1。

基本上我在网络上能搜寻的，令nginx显示real-IP的方法，我全都试过了，试无可试了，无论用什么方法，v2 / nginx的日志档，客户端的IP永远都是127.0.0.1，例如我在nginx基木上用尽下列设定了，

    set_real_ip_from 127.0.0.1;
    set_real_ip_from ::;
    set_real_ip_from 10.0.1.2;
    real_ip_header X-Forwarded-For;
    real_ip_header X-Real-IP;
    real_ip_recursive on;

location /xxxxx {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:17989;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

可惜日志档的客戶端IP都是127.0.0.1

我试过将trojan-go关闭，只使用v2 + tls + ws + nginx反代，那就没问题了，日志档里的客户端IP能正确显示，那问题就应该是出在trojan-go了。

请问trojan-go有没有什么设定，能令后端的nginx，接收v2的ws数据，都能在日志档里显示出客户端正确的IP？

谢谢。

**Comment by qiangxinglin** [comment]
#160

**Comment by p4gefau1t** [comment]
这是 feature 而不是 bug。这是一个常识性的问题，请先确保你掌握了基础的网络和运维知识。

trojan-go 接收到无效流量后将创建一个新的 socket 向 fallback 服务器转发 TCP 流量，因而本地 IP 必然是 127.0.0.1。

v2ray 之所以能取得 nginx 转发的连接的 IP，是**因为 nginx 解析并插入了 X-Real-IP 等 HTTP 头部**。而 trojan-go 被设计为仅做传输层的转发，不去解析应用层协议内容以保证足够的透明性。

如果必须要取得原始 IP，可以使用 sni 进行分流，或使 nginx 监听 443 端口并接管 TLS，将 trojan 流量转发给使用明文模式的 trojan-go。

**Comment by qiangxinglin** [comment]
明文模式是transport_plugin 的 plaintext type?

**Comment by XuuKoo** [comment]
> 
> 
> 这是 feature 而不是 bug。这是一个常识性的问题，请先确保你掌握了基础的网络和运维知识。
> 
> trojan-go 接收到无效流量后将创建一个新的 socket 向 fallback 服务器转发 TCP 流量，因而本地 IP 必然是 127.0.0.1。
> 
> v2ray 之所以能取得 nginx 转发的连接的 IP，是**因为 nginx 解析并插入了 X-Real-IP 等 HTTP 头部**。而 trojan-go 被设计为仅做传输层的转发，不去解析应用层协议内容以保证足够的透明性。
> 
> 如果必须要取得原始 IP，可以使用 sni 进行分流，或使 nginx 监听 443 端口并接管 TLS，将 trojan 流量转发给使用明文模式的 trojan-go。

trojan-go是否支持proxy protocol呢？
