### ISSUE TITLE
[Feature Request] Homebrew formula (for easy installation on macOS)

### ISSUE THREAD

**Issue by xiruizhao** [p4gefau1t/trojan-go#168]
I have written a [Homebrew formula](https://github.com/xiruizhao/homebrew-trojan-go) for trojan-go based on v2ray's formula.

You may invite others to test it first and add it to your README. 
```
# Usage on macOS
# install
brew tap xiruizhao/trojan-go
brew install trojan-go
# start trojan-go and register it to launch at login
brew services start trojan-go
# for more commands run `brew services --help`
```

**Comment by Loyalsoldier** [comment]
Trojan-Go has been in Homebrew-core https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/trojan-go.rb
