### ISSUE TITLE
x86 64 openwrt 无法运行 amd64 linux 版本

### ISSUE THREAD

**Issue by thinker007** [p4gefau1t/trojan-go#17]
./trojan-go-linux-amd64 -version
-ash: ./trojan-go-linux-amd64: not found

显示 not found ，执行权限都已经提供。

**Comment by t66y100** [comment]
动作真快，我正准备发，哈哈，确实是这样的。

**Comment by p4gefau1t** [comment]
386版本可以运行吗

**Comment by t66y100** [comment]
> 386版本可以运行吗

也不行。

**Comment by thinker007** [comment]
> 386版本可以运行吗

/trojan-go-linux-386 -version
./trojan-go-linux-386: line 1: ELF?=: not found
./trojan-go-linux-386: line 2: syntax error: unexpected "("

不能

**Comment by p4gefau1t** [comment]
原因已经确定，openwrt自带的Libc库缺少__fprintf_chk和__vfprintf_chk导致ELF加载失败

**Comment by p4gefau1t** [comment]
目前除了注释掉输入输出相关模块之外似乎没有找到更好的解决方法

**Comment by thinker007** [comment]
> 目前除了注释掉输入输出相关模块之外似乎没有找到更好的解决方法

能否静态编译，将libc库打包进二进制文件。

**Comment by p4gefau1t** [comment]
似乎可以通过设定extflag的方式静态链接，但是这可能导致兼容性方面的问题

**Comment by bigbighill** [comment]
docker 底包中 amd64/alpine  运行 trojan-go-linux-amd64 同样 not found 
trojan-go-linux-32 没有问题

**Comment by bigbighill** [comment]
apk add --no-cache \
      unzip \
      tzdata \
 && cd /tmp/repo \
 && wget --no-check-certificate https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.31-r0/glibc-2.31-r0.apk \
 && apk add --repositories-file=/dev/null --allow-untrusted --no-network --no-cache /tmp/repo/glibc-2.31-r0.apk \ 
问题解决

**Comment by ccssyybb** [comment]
> && cd /tmp/repo
> && wget --no-check-certificate https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.31-r0/glibc-2.31-r0.apk
> && apk add --repositories-file=/dev/null --allow-untrusted --no-network --no-cache /tmp/repo/glibc-2.31-r0.apk \
> 问题解决

LEDE不支持APK命令，怎么添加APK支持

**Comment by tomxiang1** [comment]
最新的Trojan-Go 0.5.1，在openwer上还是无法运行，大神们怎么办呢？

**Comment by herozzm** [comment]
v0.5.1 版本不支持 openwrt x86 为什么关闭这个issues呢?

**Comment by tomxiang1** [comment]
> @herozzm 不是trojan-go不支持openwrt x86。。是openwrt x86不支持trojan-go，它的libc库太老了。。我也没办法

openwrt x86现在是翻墙网关标配，希望大神们想想有没有解决办法。

**Comment by shynome** [comment]
好像加上 `CGO_ENABLED=0` 就可以编译出 openwrt-x86 可以运行的可执行文件了

这是我用来编译 v2ray 的命令, 没加 `CGO_ENABLED=0` 也是出现 `-ash: ./v2ray: not found` 的错误, 加上就好了
```sh
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o v2ray ./main
```
