### ISSUE TITLE
[Feature Request] Deprecate TLSv1.1 and TLSv1.0

### ISSUE THREAD

**Issue by xiruizhao** [p4gefau1t/trojan-go#170]
It's being deprecated by major browsers.
<img width="534" alt="Screen Shot 2020-08-18 at 18 35 53" src="https://user-images.githubusercontent.com/35286069/90503222-a7c5a480-e181-11ea-8377-894855c9f32e.png"> (source: [Wikipedia](https://en.wikipedia.org/wiki/Transport_Layer_Security))

**Comment by p4gefau1t** [comment]
It's deprecated in golang net/tls library
