### ISSUE TITLE
[Question] Recommended way to fix User=nobody in trojan-go.service

### ISSUE THREAD

**Issue by xiruizhao** [p4gefau1t/trojan-go#171]
Two problems with `User=nobody`
1. `nobody` cannot bind 443 unless `AmbientCapabilities=CAP_NET_BIND_SERVICE` is added in `trojan-go.service`
2. `nobody` shouldn't have access to SSL certificates

My suggestion is to add a system user for trojan-go:
1. `sudo adduser --system --group --home /nonexistent --no-create-home --disabled-password trojan-go`
2. `chown -R trojan-go:trojan-go /etc/trojan-go`, `chmod -R g=,o= /etc/trojan-go` since `config.json` contains a plain password.
3. Change to `User=trojan-go` in `trojan-go.service`
4. Grant `trojan-go` access to SSL certificates by adding it to an appropriate system group.
For example, for certificates obtained via `certbot`
```
sudo addgroup --system certbot
sudo chgrp -R certbot /etc/letsencrypt
# add group read permission to /etc/letsencrypt
# set setgid for directories so that new certificates' group is `certbot` rather than `root`
sudo find /etc/letsencrypt -type f chmod g+r {} \; -o -type d -exec g+rxs {} \; 
# add user `trojan-go` to group `certbot`
sudo adduser trojan-go certbot
# this setup does not interfere with certbot's automatic renewal
```
Do you think the setup above is reasonable? What other recommendation do you have?

**Comment by xiruizhao** [comment]
1. Linux客户端不需要 CAP_NET_BIND_SERVICE（端口1080大于1024），
2. AmbientCapabilities是授权（本来没有权限），CapabilityBoundingSet是限制（本来有包括其他权限），鉴于User还是nobody，应该用AmbientCapabilities。
3. CAP_NET_BIND_SERVICE就能监听443端口，CAP_NET_ADMIN应该没有必要？见https://man7.org/linux/man-pages/man7/capabilities.7.html

不过这些问题还是留给packager而不是作者来解决更好。等我研究下怎么做一个Ubuntu package。

**Comment by p4gefau1t** [comment]
@xiruizhao 这是我直接抄的v2ray..如果有更好的方案的话欢迎pr

**Comment by unknowndev233** [comment]
> 2. AmbientCapabilities是授权（本来没有权限），CapabilityBoundingSet是限制（本来有包括其他权限），鉴于User还是nobody，应该用AmbientCapabilities。

CapabilityBoundingSet 是限制最多可以获取的，大多数情况下 CapabilityBoundingSet 没有额外限制，也就是说任何用户都可以用 AmbientCapabilities 可以拿到没有的

> 3. CAP_NET_BIND_SERVICE就能监听443端口，CAP_NET_ADMIN应该没有必要？见https://man7.org/linux/man-pages/man7/capabilities.7.html

CAP_NET_ADMIN 用于透明代理

**Comment by XuuKoo** [comment]
我感觉大多数情况都需要安装nginx等http服务器，他们是可以访问ssl证书的，那用nginx的账户和组是否可以呢。

**Comment by moralrebuild** [comment]
> 
> 
> Two problems with `User=nobody`
> 
>     1. `nobody` cannot bind 443 unless `AmbientCapabilities=CAP_NET_BIND_SERVICE` is added in `trojan-go.service`
> 
>     2. `nobody` shouldn't have access to SSL certificates
> 
> 
> My suggestion is to add a system user for trojan-go:
> 
>     1. `sudo adduser --system --group --home /nonexistent --no-create-home --disabled-password trojan-go`
> 
>     2. `chown -R trojan-go:trojan-go /etc/trojan-go`, `chmod -R g=,o= /etc/trojan-go` since `config.json` contains a plain password.
> 
>     3. Change to `User=trojan-go` in `trojan-go.service`
> 
>     4. Grant `trojan-go` access to SSL certificates by adding it to an appropriate system group.
>        For example, for certificates obtained via `certbot`
> 
> 
> ```
> sudo addgroup --system certbot
> sudo chgrp -R certbot /etc/letsencrypt
> # add group read permission to /etc/letsencrypt
> # set setgid for directories so that new certificates' group is `certbot` rather than `root`
> sudo find /etc/letsencrypt -type f chmod g+r {} \; -o -type d -exec g+rxs {} \; 
> # add user `trojan-go` to group `certbot`
> sudo adduser trojan-go certbot
> # this setup does not interfere with certbot's automatic renewal
> ```
> 
> Do you think the setup above is reasonable? What other recommendation do you have?

Still have the problem. Verify your idea first before bring it up. B.T.W. following command have typo:
"sudo find /etc/letsencrypt -type f chmod g+r {} \; -o -type d -exec g+rxs {} \; "
