### ISSUE TITLE
[Question] How to use plaintext mode?

### ISSUE THREAD

**Issue by qiangxinglin** [p4gefau1t/trojan-go#173]
如何使nginx接管ssl, 进行plaintext mode的流量转发?
我尝试如下

    server {
        listen 443 ssl reuseport;
        server_name xxx;
        ssl_settings ...;

        location / {
            proxy_pass          http://127.0.0.1:local_port/;
            proxy_set_header    Host                $host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        }
    }

但是所有流量都会被转发到 `remote_addr:remote_port` 上
客户端配置跟正常一样, 启用ssl

**Comment by XuuKoo** [comment]
> 
> 
> @phlinhng 是的, 但是由于web服务需要客户ip, 用stream的话就需要proxy_protocol, 但是trojan就没法用了, 你有什么好办法么?

用haproxy，可以不用proxy protocol
