### ISSUE TITLE
有重新reload证书命令么

### ISSUE THREAD

**Issue by oldthreefeng** [p4gefau1t/trojan-go#179]
类似 `trojan`一样
```
killall -s SIGUSR1 trojan
```
因为证书是acme自动renew的.  所以

**Comment by p4gefau1t** [comment]
有，请理解上述命令的含义再提问

**Comment by blip** [comment]
现在自动重载证书的方式好像是通过使用文档没有提及的`cert_check_rate`参数，轮询比较证书文件。

如果通过signal来重载，可以在acme更新证书后由外部一次重载，没有性能浪费。
