### ISSUE TITLE
最新的0.1.3版本 trojan-go -version 显示 0.1.2

### ISSUE THREAD

**Issue by bigbighill** [p4gefau1t/trojan-go#18]
![Screenshot_2020-04-16-20-08-45-476_com server auditor ssh client](https://user-images.githubusercontent.com/26495337/79454681-3da7c200-801e-11ea-82e5-cbe1307cf7c7.jpg)

**Comment by p4gefau1t** [comment]
这个是忘记改了..下个版本会修正

**Comment by p4gefau1t** [comment]
这个是忘记改了..下个版本会修正

**Comment by p4gefau1t** [comment]
已经修复
