### ISSUE TITLE
怎么关闭Trojan-Go的TLS部分 ?

### ISSUE THREAD

**Issue by lxhao61** [p4gefau1t/trojan-go#183]
怎么关闭Trojan-Go的TLS部分，不由它处理的 ?如要此定制的，是否需要自己编译？如定制编译，命令参数怎么弄？

**Comment by h31105** [comment]
> 怎么关闭Trojan-Go的TLS部分，不由它处理的 ?如要此定制的，是否需要自己编译？如定制编译，命令参数怎么弄？

https://p4gefau1t.github.io/trojan-go/basic/full-config/
transport_plugin传输层插件选项
“plaintext”，使用明文传输。选择此项，trojan-go不会修改任何地址配置(remote_addr/remote_port/local_addr/local_port)，也不会启动command中插件，仅移除最底层的TLS传输层并使用TCP明文传输。此选项目的为支持nginx等接管TLS并进行分流，以及高级用户进行调试测试。请勿直接使用明文传输模式穿透防火墙。

**Comment by lxhao61** [comment]
@h31105 谢谢告知！之前没注意到这个介绍。
