### ISSUE TITLE
api batch operation

### ISSUE THREAD

**Issue by clashthe** [p4gefau1t/trojan-go#184]
在开启了api以后
./trojan-go -api-addr remotehost:port -api set -add-profile -target-password “pwd1”
可以添加用户
那么有没有方式能批量进行这个操作？比如
./trojan-go -api-addr remotehost:port -api set -add-profile -target-password “pwd1” “pwd2” “pwd3”
目的是减少建立连接的消耗

**Comment by p4gefau1t** [comment]
请自行对接基于 gRPC 的 API 实现高效的用户管理，文档中有介绍
