### ISSUE TITLE
套用cdn的安全性问题

### ISSUE THREAD

**Issue by channingbox** [p4gefau1t/trojan-go#185]
假若vps服务器是小厂不确定其安全性，但套用cdn是安全厂商（cloudflare），只启用WebSocket+tls+cdn，不使用其他加密套件，传输过程中哪些信息对vps是透明的？

**Comment by h31105** [comment]
这个问题很有意思，我觉得你可以假设 VPS=车 CDN=路 用户=驾驶员和乘客 来重新思考这个问题。
