### ISSUE TITLE
[BUG]trojan-go 做 client 的时候 ssl 连接失败,报 tls failed to handshake with remote server

### ISSUE THREAD

**Issue by iakuf** [p4gefau1t/trojan-go#187]
使用 trojan-go 做的服务器和客户端， 使用 trojan-go 客户端连接的时候， 发现 ssl 创建连接的时候一直报错， 所以不能正常的通信。但使用小火箭可以连接正常并使用。
报错如下
``` go
[INFO]  2020/09/27 07:13:44 socks connection from 127.0.0.1:55746 metadata d27xxe7juh1us6.cloudfront.net:443
[ERROR] 2020/09/27 07:13:44 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | tls failed to handshake with remote server | x509: certificate signed by unknown authority
```
我的服务器端配置如下
``` go
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80, 
    "password": ["2a87a7ad"],
    "fallback_port": 443,
    "ssl": {
        "cert": "/root/.acme.sh/t.test.com/t.test.cer",
        "key": "/root/.acme.sh/t.test.com/t.test.key",
        "sni": "t.test.com"
    },  
    "router": {
        "enabled": true,
        "block": [
            "geoip:private"
        ],  
        "geoip": "./geoip.dat",
        "geosite": "./geosite.dat"
    }   
}
~         
```
在本地是跑在 mac os 上的， mac os 的版本是 10.15.6. 本地的客户端配置如下
``` go
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "t.php-oa.com",
    "remote_port": 443,
    "password": [
        "2a87a7ad"
    ],
    "ssl": {
	"verify": true,
        "sni": "t.test.com"
    },
    "mux": {
        "enabled": false
    },
    "router": {
        "enabled": true,
        "bypass": [
            "geoip:cn",
            "geoip:private",
            "geosite:cn",
            "geosite:geolocation-cn"
        ],
        "block": [
            "geosite:category-ads"
        ],
        "proxy": [
            "geosite:geolocation-!cn"
        ],
        "default_policy": "proxy",
        "geoip": "./geoip.dat",
        "geosite": "./geosite.dat"
    }
}

```
软件的版本如下
./trojan-go --version
Trojan-Go v0.8.2
Go Version: go1.15.1
OS/Arch: darwin/amd64
Git Commit: d051cf4c8852d708769ca1c4e514306a88da830b

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:	https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:	https://p4gefau1t.github.io/trojan-go/

证书是直接使用 acme.sh 下载的。

**Comment by hm1715000** [comment]
经过我反复测试重新编译openssl和nginx重新卸载重新安装 发现这个问题 是证书的问题 
        "cert": "/root/data/xxx/fullchain.crt",
        "key": "/root/data/xxx/privkey.key",

acme.sh --installcert -d 域名 --fullchainpath /文件夹/域名/fullchain.crt --keypath /文件夹/域名/privkey.key --ecc --force 
这样子生成下证书替换进去config就OK了

**Comment by wlnirvana** [comment]
我遇到了类似的问题，确实替换成fullchain证书就可以解决了。但仍然有点奇怪，因为

1. 访问https://my.domain可以正常得到80端口的内容
2. 访问http://my.domain:443可以“正常”得到`fallback_port`端口的内容

既然这样，感觉证书配置得应该没有什么问题了才对。但这时如果利用trojan协议访问代理，就会报错。客户端跟楼主相同，服务器端是`tls handshake failed | remote error: tls: bad certificate`

**Comment by obeho** [comment]
你好，我不懂中文，对不起。我想找这个域名的信息，只有这个页面有参考。请您解释一下该域名的用途？d27xxe7juh1us6.cloudfront.net @iakuf

**Comment by buboi** [comment]
有同样的问题，但是出现在openwrt版本上，trojan-go的windows版本完全正常。

**Comment by ImMrMa** [comment]
我和 @buboi 一样，我在openwrt编译的armv8上也报这个错了，但linux x86和mac上正常的

**Comment by Loyalsoldier** [comment]
需要安装 `ca-certificates` 的包。

**Comment by xxholly32** [comment]
@Loyalsoldier 这个怎么安装？

**Comment by vpei** [comment]
这个问题解决了吗？

**Comment by yann0001** [comment]
搜linux 安装ca-certificates，centos 和 redhat 的安装方式不一样

**Comment by hqm19** [comment]
docker 基础镜像，用 busybox 有这个问题。 用 alpine 就没这个问题了。 alpine 里面包含了 ca-certificates
