### ISSUE TITLE
[ERROR] 后台一直报错acceptLoop:server.go:123 trojan failed to accept conn | websocket is disabled.

### ISSUE THREAD

**Issue by airwzz999** [p4gefau1t/trojan-go#188]
错误日志如下，请教大神如何解决？
Sep 28 11:41:29  trojan[393]: [ERROR] 2020/09/28 11:41:29 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:123 trojan failed to accept conn | websocket is disabled. redirecting http request from 35.236.182.170:35272

**Comment by p4gefau1t** [comment]
服务端没有开启 websocket

**Comment by airwzz999** [comment]
> 服务端没有开启 websocket

config.json里面配置了websocket，但很奇怪的是运行一段时间之后config.json文件里面添加和修改的内容都没了，测试几次都是这样

**Comment by p4gefau1t** [comment]
> > 服务端没有开启 websocket
> 
> config.json里面配置了websocket，但很奇怪的是运行一段时间之后config.json文件里面添加和修改的内容都没了，测试几次都是这样

有可能是你的一键脚本干的(

**Comment by garywu520** [comment]
> 服务端没有开启 websocket

解决了我的疑问，感谢

**Comment by GentleWine** [comment]
> > 服务端没有开启 websocket
> 
> 解决了我的疑问，感谢

请问怎么开启啊

**Comment by onemapl3** [comment]
同问

**Comment by jl1014171068** [comment]
将/etc/ssh/sshd_config 中的
#AllowTcpForwarding yes
改为
AllowTcpForwarding yes

**Comment by 1650987523** [comment]
你好怎么开启 websocket ，比如我这边系统是ubuntu 是 trojan 的 配置文件配置还是 ubuntu 开启 websocket
