### ISSUE TITLE
Trojan-go v0.8.2在Windows 10 1909 64位 专业版中被windows defender报毒

### ISSUE THREAD

**Issue by proxysu** [p4gefau1t/trojan-go#189]
有其他人遇到这种情况吗？还是只有我的系统问题？这应该是误报，如何解决？以前v2ray也曾经遇到过，这个微软的东西，真不靠谱。看这个版本，发布了25天了，也没有人反馈这个问题，难道真的是个例？刚查看了一下，病毒库，是今天上午(10.1)刚更新的。不知道其他们有遇到这种情况吗？

**Comment by p4gefau1t** [comment]
v2ray 此前也遇到过这种情况，最后的解决方法是联系微软..

trojan-go 的 release 版本是由 github action自动部署编译和发布的，如果你对发布的二进制文件存疑，可以自行审查源代码和编译

**Comment by DuckSoft** [comment]
手动提交给微软吧，请。

**Comment by proxysu** [comment]
> v2ray 此前也遇到过这种情况，最后的解决方法是联系微软..
> 
> trojan-go 的 release 版本是由 github action自动部署编译和发布的，如果你对发布的二进制文件存疑，可以自行审查源代码和编译

没有存疑，我知道是误报，所以现在我是直接强制允许运行，我是担心不懂技术的人，会受到影响。所以，还是想办法，把这个解决了。当初v2ray被误报时，是直接电子邮件联系微软。下面的是V2Ray被报毒后，处理过程。可以参考一下。
https://github.com/v2ray/v2ray-core/issues/2546

**Comment by proxysu** [comment]
这个页面里有向相关杀毒软件提交错误报毒的链接。多几个人提交会有作用。
https://github.com/v2ray/v2ray-core/issues/2622

**Comment by pongfcnkl** [comment]
https://www.microsoft.com/en-us/wdsi/submission/7010543f-3487-424b-9213-b2f37bc91432

**Comment by proxysu** [comment]
已经不再报毒了！我在想，是不是微软就是简单的，依据软件名字来判断的？如果真是这样，那真是比较搞笑了，哈！！

**Comment by kslr** [comment]
下个版本依旧会报毒，不去管就好了

**Comment by p4gefau1t** [comment]
我估计是有人用 go 写木马，然后 defender 把 go 的运行库一些代码当特征码来处理了。。

**Comment by kslr** [comment]
虽然微软要求手动报告，但要不要写个脚本来自动发邮件

**Comment by MarksonHon** [comment]
@proxysu 其实 Golang 自己也被报毒过，所以这事，只能人工找阿三微软解决。
