### ISSUE TITLE
如何禁用配置文件中的密码

### ISSUE THREAD

**Issue by EKDJ** [p4gefau1t/trojan-go#19]
原版在使用数据库的情况下将password设置为null即可仅使用数据库的密码

go版这样设置的话启动时会报错  提示无密码 

这点文档里好像都没提过   不知道是不是我配置有问题

**Comment by p4gefau1t** [comment]
这个情况没考虑过，下个版本修正，感谢建议。可以暂时先填入一个随意的密码。

**Comment by p4gefau1t** [comment]
已经修复
