### ISSUE TITLE
[BUG][FATAL] 2020/10/04 09:18:15 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair

### ISSUE THREAD

**Issue by xiayanzheng** [p4gefau1t/trojan-go#192]
- [ ☑️ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

## 简单描述这个 Bug
将Letsencrypt生成的fullchain.pem和privkey.pem复制到映射到docker中的目录并chmod 777后使用docker run -d --network host --name trojan-go --restart=always -v 「映射到docker中的目录」:/etc/trojan-go teddysun/trojan-go启动容器出现以下报错[FATAL] 2020/10/04 09:18:15 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair

## 如何复现这个 Bug

在此描述复现这个Bug所需要的操作步骤
将Letsencrypt生成的fullchain.pem和privkey.pem复制到映射到docker中的目录并chmod 777后使用docker run -d --network host --name trojan-go --restart=always -v 「映射到docker中的目录」:/etc/trojan-go teddysun/trojan-go启动容器

## 服务器和客户端环境信息

在此描述你的服务器和客户端所处的网络环境，系统架构，以及其他信息
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-66-generic x86_64)

## 服务端和客户端日志

粘贴**故障发生时**，服务端和客户端日志
docker logs --since 30m a04fbe557a90
[INFO]  2020/10/04 09:18:08 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:08 empty tls fallback address
[FATAL] 2020/10/04 09:18:08 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
[INFO]  2020/10/04 09:18:08 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:08 empty tls fallback address
[FATAL] 2020/10/04 09:18:08 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
[INFO]  2020/10/04 09:18:08 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:08 empty tls fallback address
[FATAL] 2020/10/04 09:18:08 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
[INFO]  2020/10/04 09:18:09 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:09 empty tls fallback address
[FATAL] 2020/10/04 09:18:09 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
[INFO]  2020/10/04 09:18:10 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:10 empty tls fallback address
[FATAL] 2020/10/04 09:18:10 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
[INFO]  2020/10/04 09:18:12 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:12 empty tls fallback address
[FATAL] 2020/10/04 09:18:12 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
[INFO]  2020/10/04 09:18:15 trojan-go v0.8.2 initializing
[WARN]  2020/10/04 09:18:15 empty tls fallback address
[FATAL] 2020/10/04 09:18:15 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
## 服务端和客户端配置文件

可以复现该问题的客户端和服务端的完整配置（请隐去域名和IP等隐私信息）
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "域名",
    "remote_port": 80,
    "password": [
        "密码"
    ],
    "ssl": {
        "cert": "fullchain.pem",
        "key": "privkey.pem",
        "sni": "域名",
        "fallback_port": 8099
    }
}
## 服务端和客户端版本信息

请执行./trojan-go -version并将输出完整粘贴在此处
「teddysun/trojan-go   latest」

## 其他信息

你认为对我们修复bug有帮助的任何信息都可以在这里写出来

**Comment by p4gefau1t** [comment]
配置错误，并非 bug

**Comment by xiahe-debug** [comment]
> 只要将证书和密钥的权限设为755就可以了

兄弟们，注意不能跨目录，实测必须放到配置文件目录下，修改权限755无用
