### ISSUE TITLE
大佬，有没有代码的详细解读呀？求分享

### ISSUE THREAD

**Issue by xiran2018** [p4gefau1t/trojan-go#193]
代码的详细解读，求各位大佬分享

**Comment by p4gefau1t** [comment]
@jingquanliang 求别解读了，就是个能跑的屎山

**Comment by jingquanliang** [comment]
您太谦虚了，非常想学习一下您的编码思路，如果熟悉了，也希望可以为开源贡献一份力量

**Comment by jingquanliang** [comment]
Tunnel文件夹下的几个协议，调用关系是怎么的，可否说明一下，感觉看起来有点乱，一时没看明白

**Comment by p4gefau1t** [comment]
> Tunnel文件夹下的几个协议，调用关系是怎么的，可否说明一下，感觉看起来有点乱，一时没看明白

具体的协议栈的构造在 proxy 文件夹下

**Comment by jingquanliang** [comment]
请教一下代码的问题：
针对tunnel中的代码，我有一个疑问，在tls这个tunnel的server.go代码中调用了common.NewRewindConn方法生成了一次RewindConn，当trojan这个tunnel拿到tls中的conn（该conn通过tls中的connChan管道传输）之后，这个拿到的conn已经是tls中放进来的RewindConn类型了，为什么还要调用common.NewRewindConn，而不是直接用拿到的这个conn呢？

**Comment by jingquanliang** [comment]
![IMG_20201010_181126](https://user-images.githubusercontent.com/8544622/95652594-dc702f80-0b24-11eb-9859-0668f5e77430.jpg)
这是我理解的一个关系，不知道是否正确，请大佬帮忙解答一下疑惑

**Comment by jingquanliang** [comment]
![IMG_20201010_181126](https://user-images.githubusercontent.com/8544622/95652631-12adaf00-0b25-11eb-8bb2-317f985deb43.jpg)

**Comment by p4gefau1t** [comment]
rewind 只是方便进行协议回落而已，至于包了几层我其实也太不清楚（

**Comment by jingquanliang** [comment]
谢谢您的回复，我还有一个问题不太懂，就是关于tunnel的发送数据，如下图所示，按照多路复用作用说明，当发送数据到trojan服务端时，client端应该按照协议组装数据，然后通过io.Copy数据复制，组装数据时我看到了simpleSocks写了write方法，那么是不是write发送会链式调用，如图所示：SimpleSocks(Write方法)--->smux(Write方法) --->Trojan(Write方法)--->底层协议
![image](https://user-images.githubusercontent.com/8544622/95827358-357ad600-0d66-11eb-81ae-3605dd0184a7.png)

**Comment by froest2012** [comment]
> 请教一下代码的问题：
> 针对tunnel中的代码，我有一个疑问，在tls这个tunnel的server.go代码中调用了common.NewRewindConn方法生成了一次RewindConn，当trojan这个tunnel拿到tls中的conn（该conn通过tls中的connChan管道传输）之后，这个拿到的conn已经是tls中放进来的RewindConn类型了，为什么还要调用common.NewRewindConn，而不是直接用拿到的这个conn呢？

重写RewindConn已经把协议头部写入到buf中，方便对协议头进行校验，可以看下socks/server.go的handshake方法，里面的conn.Read方法中的conn其实是RewindConn，读取的数据其实是从RewindConn中的buf来的；如果直接拿conn，数据读取完之后，流里面就不存在了，相当于破坏了原始分组数据
