### ISSUE TITLE
py

### ISSUE THREAD

**Issue by FenghenHome** [p4gefau1t/trojan-go#2]
大佬有tg吗，方便交流
以下是别人go语言的实现，可以看看有没有值得学习地方
https://github.com/Dreamacro/clash/commit/b562f28c1be869337224a88d4342abbd169882a6
https://github.com/saito-mayumi/trojan-go

**Comment by p4gefau1t** [comment]
1. 有，可以留下你的邮箱，我们私下交流
2. 看了一下他的实现，似乎完成度还不是很高？

**Comment by FenghenHome** [comment]
s.sunfeihu@gmail.com
