### ISSUE TITLE
udp 怎么使用？

### ISSUE THREAD

**Issue by yjsslab** [p4gefau1t/trojan-go#20]
启动后，只发现 tcp 443 ，没有监听 udp 443

**Comment by p4gefau1t** [comment]
Trojan协议规定服务端只接收TLS隧道传输，客户端的UDP包会通过TLS隧道发送给服务器

如果运行客户端，你可以发现该端口上的TCP和UDP都被监听了

**Comment by yjsslab** [comment]
> Trojan协议规定服务端只接收TLS隧道传输，客户端的UDP包会通过TLS隧道发送给服务器
> 
> 如果运行客户端，你可以发现该端口上的TCP和UDP都被监听了

明白，刚试了一下
@p4gefau1t 在客户端 dig qq.com @1.1.1.1 时，服务端一直 i/o timeout 是什么问题呢？服务端 dig 却很快。

**Comment by p4gefau1t** [comment]
这里的UDP支持是说的支持socks5协议中的UDP Associate指令建立UDP隧道，但是从你的描述来看你似乎用dig来直接向socks5端口发包？

**Comment by p4gefau1t** [comment]
如果你想实现DNS的隧道，应该使用forward而不是client，参考这里
https://p4gefau1t.github.io/trojan-go/advance/forward/

**Comment by yjsslab** [comment]
@p4gefau1t thx
