### ISSUE TITLE
请问下丢包会影响启用多路复用时的连接稳定性吗？

### ISSUE THREAD

**Issue by XuuKoo** [p4gefau1t/trojan-go#200]
是否存在“要丢一起丢”，相比不开启多路复用，数据包被丢的更严重的情况？

**Comment by p4gefau1t** [comment]
多路复用基于 TLS 流的， TLS 是基于 TCP 可靠连接的，丢包是在 TCP 层面的问题，和多路复用本身没有关系

**Comment by XuuKoo** [comment]
> 
> 
> 多路复用基于 TLS 流的， TLS 是基于 TCP 可靠连接的，丢包是在 TCP 层面的问题，和多路复用本身没有关系

多路复用确实是不会影响丢包。

我本来的理解是“某些本来独立的数据包在多路复用下会打包在一起发送，打包后的这个包如果丢失，则造成这几个在一起的数据包全部丢失”，我就是想问我这样理解对不对。

**Comment by p4gefau1t** [comment]
> > 多路复用基于 TLS 流的， TLS 是基于 TCP 可靠连接的，丢包是在 TCP 层面的问题，和多路复用本身没有关系
> 
> 多路复用确实是不会影响丢包。
> 
> 我本来的理解是“某些本来独立的数据包在多路复用下会打包在一起发送，打包后的这个包如果丢失，则造成这几个在一起的数据包全部丢失”，我就是想问我这样理解对不对。

多路复用(smux)是**应用层**的协议，它假定了下层的传输流是可靠的。而 TCP 本身就是可靠的传输流。丢包问题是传输层协议进行处理，而非应用层协议。

所以讨论多路复用和丢包的关系没有意义。因为多路复用协议不会遇到丢包的情况。丢包只在传输层发生。

如果你对多路复用的协议实现有疑问，可以参考 smux 仓库的源代码。

**Comment by XuuKoo** [comment]
> 
> 
> > > 多路复用基于 TLS 流的， TLS 是基于 TCP 可靠连接的，丢包是在 TCP 层面的问题，和多路复用本身没有关系
> > 
> > 
> > 多路复用确实是不会影响丢包。
> > 我本来的理解是“某些本来独立的数据包在多路复用下会打包在一起发送，打包后的这个包如果丢失，则造成这几个在一起的数据包全部丢失”，我就是想问我这样理解对不对。
> 
> 多路复用(smux)是**应用层**的协议，它假定了下层的传输流是可靠的。而 TCP 本身就是可靠的传输流。丢包问题是传输层协议进行处理，而非应用层协议。
> 
> 所以讨论多路复用和丢包的关系没有意义。因为多路复用协议不会遇到丢包的情况。丢包只在传输层发生。
> 
> 如果你对多路复用的协议实现有疑问，可以参考 smux 仓库的源代码。

那在一定丢包的线路上使用多路复用，网络连接质量会更好还是更差呢？

我的测试开了多路复用后 ，gv打电话反而音质要差一些。
