### ISSUE TITLE
[BUG] 使用几个小时后所有客户端都连接不上服务端，但服务端仍在运行

### ISSUE THREAD

**Issue by dzhl** [p4gefau1t/trojan-go#203]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

## 服务器和客户端环境信息
服务器是ubuntu18.04，客户端是安卓、openwrt中ssrp，以及windows中calsh和QV2ray

## 服务端和客户端日志

服务端日志如下：日志中100.204.12.26为匿名的服务器IP，100.204.12.25为匿名的家中路由IP
[log.log](https://github.com/p4gefau1t/trojan-go/files/5362641/log.log)

## 服务端和客户端配置文件

服务端配置文件：
~~~
{
  "run_type": "server",
  "local_addr": "0.0.0.0",
  "local_port": 443,
  "remote_addr": "127.0.0.1",
  "remote_port": 80,
  "log_level": 1,
  "log_file": "/usr/src/trojan-go/log.log",
  "password": ["mima"],
  "disable_http_check": false,
  "udp_timeout": 60,
  "ssl": {
    "verify": false,
    "verify_hostname": false,
    "cert": "/usr/src/trojan-cert/fullchain.cer",
    "key": "/usr/src/trojan-cert/private.key",
    "key_password": "",
    "cipher": "",
    "curves": "",
    "prefer_server_cipher": false,
    "sni": "绑定的域名",
    "alpn": [
      "http/1.1"
    ],
    "session_ticket": true,
    "reuse_session": true,
    "plain_http_response": "",
    "fallback_addr": "",
    "fallback_port": 0,
    "fingerprint": "firefox"
  },
  "tcp": {
    "no_delay": true,
    "keep_alive": true,
    "prefer_ipv4": false
  },
  "mux": {
    "enabled": false,
    "concurrency": 8,
    "idle_timeout": 60
  },
  "router": {
    "enabled": false,
    "bypass": [],
    "proxy": [],
    "block": [],
    "default_policy": "proxy",
    "domain_strategy": "as_is",
    "geoip": "$PROGRAM_DIR$/geoip.dat",
    "geosite": "$PROGRAM_DIR$/geosite.dat"
  },
  "websocket": {
    "enabled": false,
    "path": "",
    "host": ""
  },
  "shadowsocks": {
    "enabled": false,
    "method": "AES-128-GCM",
    "password": ""
  },
  "transport_plugin": {
    "enabled": false,
    "type": "",
    "command": "",
    "option": "",
    "arg": [],
    "env": []
  },
  "forward_proxy": {
    "enabled": false,
    "proxy_addr": "",
    "proxy_port": 0,
    "username": "",
    "password": ""
  },
  "mysql": {
    "enabled": false,
    "server_addr": "localhost",
    "server_port": 3306,
    "database": "",
    "username": "",
    "password": "",
    "check_rate": 60
  },
  "api": {
    "enabled": false,
    "api_addr": "",
    "api_port": 0,
    "ssl": {
      "enabled": false,
      "key": "",
      "cert": "",
      "verify_client": false,
      "client_cert": []
    }
  }
}
~~~

服务端启动service文件：
~~~
[Unit]  
Description=Trojan-Go
After=network.target nss-lookup.target 
   
[Service]
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true  
ExecStart=/usr/src/trojan-go/trojan-go -config "/usr/src/trojan-go/config.json"    
Restart=on-failure
RestartSec=10s  
[Install]  
WantedBy=multi-user.target

~~~
## 服务端和客户端版本信息
服务端：
Trojan-Go v0.8.2
Go Version: go1.15.1
OS/Arch: linux/amd64
Git Commit: d051cf4c8852d708769ca1c4e514306a88da830b

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:	https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:	https://p4gefau1t.github.io/trojan-go/
客户端：
我用到很多客户端，都是同时不能连接，应该不是客户端问题
## 其他信息

你认为对我们修复bug有帮助的任何信息都可以在这里写出来

**Comment by p4gefau1t** [comment]
请提供一下**服务端和客户端**的**Debug级别**的日志

**Comment by dzhl** [comment]
好的，不过要等几个小时出错后提供了

**Comment by dzhl** [comment]
客户端又连接不上客户端了，
服务端日志：
[服务端日志.log](https://github.com/p4gefau1t/trojan-go/files/5363963/default.log)
客户端QV2ray日志：
[Qv2ray日志.txt](https://github.com/p4gefau1t/trojan-go/files/5363966/Qv2ray.txt)

**Comment by p4gefau1t** [comment]
> 客户端又连接不上客户端了，
> 服务端日志：
> [服务端日志.log](https://github.com/p4gefau1t/trojan-go/files/5363963/default.log)
> 客户端QV2ray日志：
> [Qv2ray日志.txt](https://github.com/p4gefau1t/trojan-go/files/5363966/Qv2ray.txt)

这个是客户端同时打开了太多连接导致服务端 fd 耗尽而无法接受更多连接

因为客户端比较多，可能是可能是其中一个客户端持有大量连接而没有释放导致的，也可能是 trojan-go 某些地方泄漏了 socket（但是就目前来看没有复现），也有可能单纯的客户端太多导致的

**Comment by dzhl** [comment]
我在日志里确实也看到了过多连接。目前我最多同时使用4个客户端连接，其中一个是openwrt中ssrp保持一直连接，如果有连接释放不掉，最有可能出问题的客户端就是它了，不知你在openwrt中使用的什么客户端

**Comment by ckbkdj** [comment]
我也遇到了这个问题，使用trojan-go出现过一段时间需要重启的问题，就是最近更新出现的，以前都没有

**Comment by ckbkdj** [comment]
我的客户端就是trojan-Android跟小火箭

**Comment by MoeGrid** [comment]
同问题……跑了几次speedtest就连不上了，服务端运行的好好的也没挂，重启一下就好了

**Comment by MoeGrid** [comment]
在服务器和路由器上netstat看了一下，同IP有一大堆ESTABLISHED连接，客户端用的是lean的openwrt固件trojan 1.16.0

**Comment by hunao0221** [comment]
same issue.

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/p4gefau1t/trojan-go/pull/313
