### ISSUE TITLE
[功能建议]LOG增加服务器支持

### ISSUE THREAD

**Issue by Error996** [p4gefau1t/trojan-go#207]
LOG增加服务器支持~而非只有文件

**Comment by DuckSoft** [comment]
FIlebeat / Logstash 等方案了解一下？

**Comment by d1ves** [comment]
不管磁盘了呗?

**Comment by d1ves** [comment]
我建议是直接走网络,用专门的服务器来承载,毕竟文件日志需要读写硬盘,会长时间读写会有损耗,不适合长期部署

**Comment by DuckSoft** [comment]
`/tmp` 了解一下？logrotate 了解一下？

**Comment by d1ves** [comment]
假设有集群A共计50台服务器,每台都做独立的日志,然后在用一套技术方案去搞,为啥不直接用tcp来部署到独立的服务器呢?
而且便于管理

**Comment by DuckSoft** [comment]
因为 Trojan-Go 本体不是干这个的。

现有的分布式日志采集仓储方案已经非常成熟了，你没必要再向 Trojan-Go 作者请求这些功能。

**Comment by d1ves** [comment]
ok
