### ISSUE TITLE
github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 invalid redirect address. check your http server: 127.0.0.1:80 | dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by matianhe** [p4gefau1t/trojan-go#208]
OS : Debian 10
trojan-go v0.8.2
github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 invalid redirect address. check your http server: 127.0.0.1:80 | dial tcp 127.0.0.1:80: connect: connection refused

config:
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        ""
    ],
    "ssl": {
        "cert": "",
        "key": "",
        "sni": ""
    },
    "router": {
        "enabled": true,
        "block": [
            "geoip:private"
        ],
        "geoip": "/root/trojan-go/geoip.dat",
        "geosite": "/root/trojan-go/geosite.dat"
    }
}

![image](https://user-images.githubusercontent.com/24929062/97100654-998b8b80-16d0-11eb-9067-92c3b76c288b.png)
群组进不去。

**Comment by hulisang** [comment]
需要在80端口运行一个caddy or nginx

**Comment by ningman** [comment]
我也遇到这个问题，怎么解决的

**Comment by mohsentaleb** [comment]
Run `netstat -plnat` to see which process/app is listening on port `80` and then kill/stop that process.
