### ISSUE TITLE
尝试走cloudflare的cdn失败?

### ISSUE THREAD

**Issue by txdywy** [p4gefau1t/trojan-go#21]
[DEBUG] 2020/04/18 13:44:46 github.com/p4gefau1t/trojan-go/proxy/client.DialTLSToServer:client.go:44 TLS handshaked cipher: TLS_AES_128_GCM_SHA256 resume: false
[ERROR] 2020/04/18 13:44:47 github.com/p4gefau1t/trojan-go/proxy/client.(*Client).handleSocksConn:client.go:165 failed to dail to remote server | failed to start websocket connection | x509: certificate signed by unknown authority

服务端配置好了证书

**Comment by p4gefau1t** [comment]
可以提供一下你的配置文件吗

**Comment by p4gefau1t** [comment]
将log_level调节到0，看一下输出日志

**Comment by txdywy** [comment]
日志
Server Log:
[INFO]  2020/04/18 10:22:02 Trojan-Go v0.1.4 initializing
[INFO]  2020/04/18 10:22:02 Loading config file from server.json
[INFO]  2020/04/18 10:22:02 websocket enabled
[INFO]  2020/04/18 10:22:02 server is running at 0.0.0.0:443
[DEBUG] 2020/04/18 10:22:13 github.com/p4gefau1t/trojan-go/protocol/trojan.NewInboundWebsocket.func2:websocket.go:158 websocket url /r origin https://xxx.xxx.com
[DEBUG] 2020/04/18 10:22:13 github.com/p4gefau1t/trojan-go/protocol/trojan.NewInboundWebsocket.func1:websocket.go:151 websocket obtained
[WARN]  2020/04/18 10:22:13 remote 162.158.243.115:11778 invalid websocket conn
[ERROR] 2020/04/18 10:22:13 github.com/p4gefau1t/trojan-go/proxy/server.(*Server).handleConn:server.go:110 dial tcp 127.0.0.1:80: connect: connection refused
[INFO]  2020/04/18 10:22:13 user INVALID_HASH conn to 127.0.0.1:80 closed sent: 0 B recv: 0 B

Client Log:
[DEBUG] 2020/04/18 18:22:12 github.com/p4gefau1t/trojan-go/proxy/client.DialTLSToServer:client.go:44 TLS handshaked cipher: TLS_AES_128_GCM_SHA256 resume: false
[ERROR] 2020/04/18 18:22:13 github.com/p4gefau1t/trojan-go/proxy/client.(*Client).handleSocksConn:client.go:165 failed to dail to remote server | failed to start websocket connection | x509: certificate signed by unknown authority

**Comment by txdywy** [comment]
配置:

Server:

{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "xxxx"
    ],
    "log_level":0,
    "ssl": {
        "cert": "xxx.cer",
        "key": "xxx.key"
    },
    "websocket": {
        "enabled": true,
        "path": "/r",
        "hostname": "xxx.xxx.com",
        "password": "xxxx",
        "double_tls": true
    }
}


Client:
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1078,
    "remote_addr": "xxx.xxx.com",
    "remote_port": 443,
    "log_level": 0,
    "password": [
        "xxxx"
    ],
    "ssl": {
        "sni": "xxx.xxx.com",
        "verify": false
    },
    "router":{
        "enabled": true,
        "bypass": [
            "geoip:cn",
            "geosite:cn",
            "geosite:private"
        ],
        "block": [
            "geosite:category-ads"
        ],
        "proxy": [],
        "route_by_ip_on_nonmatch": true
    },
    "websocket": {
        "enabled": true,
        "path": "/r",
        "hostname": "xxx.xxx.com",
        "password": "xxxx",
        "double_tls": true
    }
}

**Comment by txdywy** [comment]
有websocket时貌似证书验证不行,不走cdn直接连的也不行

**Comment by p4gefau1t** [comment]
我看到你把verify关了，你的证书是自己签发的吗

**Comment by txdywy** [comment]
关了貌似不管用？


证书是letsencrypt的。

自签的证书也试过，直连没有ws时可以，加了ws也不行。


搜了一下那个报错貌似是跟golang有关系？看到一些别的项目也有这个报错。

Page Fault <notifications@github.com> 于 2020年4月18日周六 下午10:57写道：

**Comment by txdywy** [comment]
https://github.com/v2ray/v2ray-core/issues/988

感觉跟这个差不多，对证书有要求？

但是verify设置为false貌似没想allowinscure一样生效？

wei yi <genius.ron@gmail.com> 于 2020年4月18日周六 下午11:02写道：

**Comment by txdywy** [comment]
另外一开始想用trojan-go签证书，因为想走cdn，所以域名托管给cloudflare，想用proxy模式走cdn，但是tg申请证书会报错（已经配了cloudflare的token环境变量，可能需要支持一下）

**Comment by txdywy** [comment]
解决了.发现是websocket里面double_tls默认是开启,但是针对letsencrypt证书貌似证书链验证有问题,会报错.double_tls=false就ok了.看起来v2ray里面也有这个问题,通过设置allowinsecure解决

**Comment by p4gefau1t** [comment]
双重tls的第二层的证书认证是被强制打开的，这个是有意为之

**Comment by txdywy** [comment]
https://github.com/matrix-org/synapse/issues/4764

mark一下,需要fullchain.cer,不能只是子域名的cer.有些系统上会出现问题
