### ISSUE TITLE
verifying github.com/shadowsocks/go-shadowsocks2@v0.1.0/go.mod: checksum mismatch

### ISSUE THREAD

**Issue by hzjnet** [p4gefau1t/trojan-go#217]
在centos 7系统使用golang go version go1.15.2 linux/amd64 编译openwrt 17源码中的trojan-go 0.8.2出现以下错误：
verifying github.com/shadowsocks/go-shadowsocks2@v0.1.0/go.mod: checksum mismatch
        downloaded: h1:SiGEqep4n+bS5wCZwi6ZgX1MAGRV9erk0zsVOXZ7QvA=
        go.sum:     h1:/0aFGbhK8mtOX4J/6kTJsPLZlEs9KnzKoWCOCvjd7vk=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

系统设置了：
export GO111MODULE=on
export GOPROXY=https://goproxy.io,direct

编译选择中选取goproxy选项也会出现以上错误！

如果取消系统关于goproxy的设置会出现：
go: github.com/shadowsocks/go-shadowsocks2@v0.1.0: Get "https://proxy.golang.org/github.com/shadowsocks/go-shadowsocks2/@v/v0.1.0.mod": dial tcp 172.217.24.17:443: i/o timeout

而GOSUMDB不管是OFF还是sum.golang.google.cn，错误是一样的，而SiGEqep4n+bS5wCZwi6ZgX1MAGRV9erk0zsVOXZ7QvA
或者/0aFGbhK8mtOX4J/6kTJsPLZlEs9KnzKoWCOCvjd7vk=在编译源码和临时文件中都找不到！
同时清除系统的go.sum也不能解决问题！

请教如何处理这checksum mismatch

谢谢！

靠，今天下午测试发现：系统设置成：export GOPROXY=https://goproxy.cn,direct,同时编译选项取消goproxy的设置就正常了

**Comment by cooolinx** [comment]
相同现象，已解决。

首先执行`go env`确认`GOPROXY`是否配置了一些国内代理，例如我的：
```
GOPROXY="https://goproxy.io,direct"
```

如果没有可能不是同一个case。如果有，解决方案，执行：

```sh
go env -w GOPRIVATE=github.com/shadowsocks
go clean -modcache 
go mod tidy
```

**Comment by Yofo-me** [comment]
> 相同现象，已解决。
> 
> 首先执行`go env`确认`GOPROXY`是否配置了一些国内代理，例如我的：
> 
> ```
> GOPROXY="https://goproxy.io,direct"
> ```
> 
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> 如果没有可能不是同一个案例。如果有，解决方案：
> 
> 1. 先编辑`go.sum`文件，搜索`shadowsocks`，删除两行
> 2. 执行：
> 
> go env -w GOPRIVATE=github.com/shadowsocks
> go clean -modcache 
> go mod tidy
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

### 同样的问题
![image](https://user-images.githubusercontent.com/55388087/101446292-fb8d1100-395d-11eb-8602-37e00917626f.png)

**Comment by Yofo-me** [comment]
> 相同现象，已解决。
> 
> 首先执行`go env`确认`GOPROXY`是否配置了一些国内代理，例如我的：
> 
> ```
> GOPROXY="https://goproxy.io,direct"
> ```
> 
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> 如果没有可能不是同一个案例。如果有，解决方案：
> 
> 1. 先编辑`go.sum`文件，搜索`shadowsocks`，删除两行
> 2. 执行：
> 
> go env -w GOPRIVATE=github.com/shadowsocks
> go clean -modcache 
> go mod tidy
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

## 图中的这两个都要修改吗
![image](https://user-images.githubusercontent.com/55388087/101446448-558dd680-395e-11eb-8444-05812be72263.png)

**Comment by cooolinx** [comment]
> 相同现象，已解决。
> 
> 首先执行go env确认GOPROXY是否配置了一些国内代理，例如我的：
> 
> GOPROXY="https://goproxy.io,direct"
> 
> 如果没有可能不是同一个案例。如果有，解决方案：
> 
> 先编辑go.sum文件，搜索shadowsocks，删除两行
> 执行：
> go env -w GOPRIVATE=github.com/shadowsocks
> go clean -modcache
> go mod tidy
> 
> 
> 图中的这两个都要修改吗
> 
> 
> 这个需要执行go mod init吗？

你是不是不在项目目录中？确保自己在go.mod同一目录中
