### ISSUE TITLE
请问下trojan-go的透明代理是只可以在路由器上使用吗?可不可以在本地创建虚拟网卡?

### ISSUE THREAD

**Issue by Walkerby** [p4gefau1t/trojan-go#218]
使用的是ubuntu,不知道透明代理能否在本地设置

**Comment by flyawayazure** [comment]
@Walkerby 啊透明代理不会创建虚拟网卡，他的原理和TUN完全不同。
具体可以看这个https://github.com/springzfx/cgproxy
在本地设置完全没问题，我这里有一篇中文入门教程，希望有所帮助

**Comment by flyawayazure** [comment]
https://github.com/flyawayazure/cgproxy-install-and-deploy-tutor

**Comment by Walkerby** [comment]
> https://github.com/flyawayazure/cgproxy-install-and-deploy-tutor

好的，感谢！
