### ISSUE TITLE
将trojan-go添加到openwrt的源代码中编译总是报错

### ISSUE THREAD

**Issue by Tonkercke** [p4gefau1t/trojan-go#220]
如题，在编译的时候总是出现如下报错：

# github.com/p4gefau1t/trojan-go/tunnel/tls/fingerprint
../../tunnel/tls/fingerprint/tls.go:237:9: undefined: "crypto/tls".CipherSuites
note: module requires Go 1.15

Cleaning module download cache (golang/go#27455)
代码中提示需要go 1.15版本的语言环境，不过go语言环境已经安装好，运行go version会显示 go version go1.15.4 linux/amd64,我也尝试更换1.15、1.15.1等版本也一样报错。不知出现此错误是因为什么问题，希望回复一下。（本人代码小白）

还有，使用的系统是ubuntu18.4.4，一开始也用过ubuntu 20.4都是一样的问题。openwrt用的是官方版的github源代码，版本是19.07.4。 系统挂了全局代理。

**Comment by douo** [comment]
确保 `golang/host` 的版本大于 > 1.15
可以在 `feeds/packages/lang/golang/golang-version.mk` 或 `feeds/packages/lang/golang/golang/Makefile` 中找到。

现在官方的最新版本版本已经是 [1.15](https://github.com/openwrt/packages/blob/master/lang/golang/golang/Makefile#L10) 了，注意升级。

**Comment by Tonkercke** [comment]
非常感谢，按照你说的修改了版本号就可以了。
