### ISSUE TITLE
[错误] 报错 ： tls handshake TLS_AES_256_GCM_SHA384 false

### ISSUE THREAD

**Issue by allen-tsu** [p4gefau1t/trojan-go#224]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

##我按手册配置了一个服务，有时候打不开，有时候很慢，总出现“tls handshake TLS_AES_256_GCM_SHA384 false”，请教下该如何正确配置。如果用 p4gefau1t的docker 文件运行则没有问题。请教一下这个问题会处在哪里

## 服务器和客户端环境信息

trojan-go version：v.0.8.2
server: Linux raspberry 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux(是Debian 10)
client: shadowrocket 2.1.52(iPhone), trojan-QT5 1.4.0(mac)
证书：Let's Encrypt

## 服务端和客户端日志

![log](https://user-images.githubusercontent.com/28680873/99042374-94cb4080-25c7-11eb-85e8-eeced8d81323.png)

## 服务端和客户端配置文件

![屏幕快照 2020-11-13 15 35 28](https://user-images.githubusercontent.com/28680873/99042388-9c8ae500-25c7-11eb-948c-7f11f06af137.png)

## 服务端和客户端版本信息

Trojan-Go v0.8.2
Go Version: go1.15.1
OS/Arch: linux/amd64
Git Commit: d051cf4c8852d708769ca1c4e514306a88da830b

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:      https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:    https://p4gefau1t.github.io/trojan-go/

**Comment by p4gefau1t** [comment]
这是用于调试的 trace 信息，并非报错
