### ISSUE TITLE
when I use trojan-go as a client to access http websites(any), will get below ERRORS

### ISSUE THREAD

**Issue by istanleyyaw** [p4gefau1t/trojan-go#226]
[ERROR] 2020/11/16 14:31:07 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 io: read/write on closed pipe
[DEBUG] 2020/11/16 14:31:07 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:87 conn relay ends
[ERROR] 2020/11/16 14:31:07 github.com/p4gefau1t/trojan-go/tunnel/http.(*Server).acceptLoop.func1:server.go:161 http failed to the read request from local | EOF

my trojan-go version is 0.8.2, even if the domain is in the bypass list of the router, it still have above error.

**Comment by istanleyyaw** [comment]
however, the website can be opened, but it have above errors.
one moe issue for me is, after used it for a while(few mins), looks like the trojan-go client does not accept new request, and existing request is pending for the response even if the domain in the bypass list of the router, if I force close the trojan-go client and then start it again, it back to normal.

**Comment by istanleyyaw** [comment]
当我在windows上用Qv2ray做客户端，速度就很快，可是如果直接跑trojan-go 做客户端，跑了一会就会停顿在那里。
windows 上跑trojan-go 客户端也有上面的错误。

**Comment by Loyalsoldier** [comment]
Maybe fixed by https://github.com/p4gefau1t/trojan-go/pull/313
