### ISSUE TITLE
[BUG]使用API创建用户, 重启trojan-go用户消失

### ISSUE THREAD

**Issue by ermaozi** [p4gefau1t/trojan-go#227]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

## 简单描述这个 Bug

使用API创建用户, 重启trojan-go用户消失

## 如何复现这个 Bug

1. 安装并启动trojan-go, 配置文件参考文档配置
2. 使用api命令 `./trojan-go -api-addr 127.0.0.1:10000 -api set -add-profile -target-password 123asd`创建用户, 创建成功
3. 使用api命令: `./trojan-go -api-addr 127.0.0.1:10000 -api list`查看, 用户存在
4. 重启trojan-go
5. 使用api命令: `./trojan-go -api-addr 127.0.0.1:10000 -api list`查看, 用户不存在

## 服务器和客户端环境信息

CentOS 8.1

## 服务端和客户端日志

N/A

## 服务端和客户端配置文件

``` json
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "log_level": 1,
    "log_file": "",
    "password": [
        "pwd01"
    ],
    "ssl": {
        "cert": "/root/.acme.sh/tj03.***.net_ecc/fullchain.cer",
        "key": "/root/.acme.sh/tj03.***.net_ecc/tj03.***.net.key",
        "sni": "tj03.***.net"
    },
    "api": {
        "enabled": true,
        "api_addr": "127.0.0.1",
        "api_port": 10000
    },
    "router": {
        "enabled": true,
        "block": [
            "geoip:private"
        ],
        "geoip": "/usr/share/trojan-go/geoip.dat",
        "geosite": "/usr/share/trojan-go/geosite.dat"
    }
}
```
## 服务端和客户端版本信息

Trojan-Go v0.8.2
Go Version: go1.15.1
OS/Arch: linux/amd64
Git Commit: d051cf4c8852d708769ca1c4e514306a88da830b

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:      https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:    https://p4gefau1t.github.io/trojan-go/

## 其他信息

N/A

**Comment by h31105** [comment]
@ermaozi 我印象中，这个不是bug，用户信息的持久化需要通过后端数据库实现。

**Comment by ermaozi** [comment]
> @ermaozi 我印象中，这个不是bug，用户信息的持久化需要通过后端数据库实现。

 确实没装数据库, 还以为trojan-go有一套自己的后端存储呢.

**Comment by p4gefau1t** [comment]
> @ermaozi 我印象中，这个不是bug，用户信息的持久化需要通过后端数据库实现。

确实如此，这个是 feature 不是 bug

**Comment by YangAnLin** [comment]
后端怎么统计比较好了,因为获取的流量是叠加的
