### ISSUE TITLE
按照教程来的这种报错怎么解决？不能初始化

### ISSUE THREAD

**Issue by beiyuqu** [p4gefau1t/trojan-go#235]
trojan-go v0.8.2 initializing
[WARN]  2020/12/03 15:42:33 empty tls fallback address
[FATAL] 2020/12/03 15:42:33 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 invalid fallback address | dial tcp 127.0.0.1:1234: connect: connection refused

**Comment by chenmingxing-demo** [comment]
一样，求解决办法。

**Comment by jinwyp** [comment]
fallback的端口必须有监听，例如80端口 用nginx架设个网站
