### ISSUE TITLE
客户端启用多路复用功能后，连接错误[BUG]

### ISSUE THREAD

**Issue by garywu520** [p4gefau1t/trojan-go#236]
## 简单描述这个 Bug
客户端启用多路复用功能后，连接错误。Log: github.com/p4gefau1t/trojan-go/tunnel/simplesocks.(*Server).acceptLoop:server.go:41 simplesocks server faield to read header | EOF
## 如何复现这个 Bug
trojan-go客户端添加如下代码(服务端不配置多路复用)
```
"mux": {
    "enabled": true,
    "concurrency": 8,
    "idle_timeout": 60
}
```
## 服务端和客户端日志
```
github.com/p4gefau1t/trojan-go/tunnel/simplesocks.(*Server).acceptLoop:server.go:41 simplesocks server faield to read header | EOF
```
请执行./trojan-go -version并将输出完整粘贴在此处
```
Trojan-Go v0.8.2
Go Version: go1.15.1
OS/Arch: linux/amd64
Git Commit: d051cf4c8852d708769ca1c4e514306a88da830b

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:	https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:	https://p4gefau1t.github.io/trojan-go/

```

**Comment by McDull-GitHub** [comment]
```
"mux": {
    "enabled": true,
    "concurrency": 8,
    "idle_timeout": 60
}
```
去看下[文檔](https://p4gefau1t.github.io/trojan-go/advance/mux/)

**Comment by garywu520** [comment]
> ```
> "mux": {
>     "enabled": true,
>     "concurrency": 8,
>     "idle_timeout": 60
> }
> ```
> 
> 去看下[文檔](https://p4gefau1t.github.io/trojan-go/advance/mux/)

idle_timeout配置60也不行啊，你要我看哪部分？

**Comment by McDull-GitHub** [comment]
`"enabled": enable` -> `"enabled": true` and close the issue...

**Comment by garywu520** [comment]
> `"enabled": enable` -> `"enabled": true` and close the issue...

感谢指正，是这里手误，配置文件是true。经过多次测试，linux客户端可以连接，但是服务端报错如下：
