### ISSUE TITLE
trojan可以跟tor结合吗？如果不可以，是否有别的方案？

### ISSUE THREAD

**Issue by lkjhgfdsa20200802** [p4gefau1t/trojan-go#237]
我有一个想法，telegram能否配合trojan+tor使得IP也不无法被嗅探。
telegram的ip是知道的，能不能使trojan遇到telegram的ip时自动转发到tor代理？其他的数据则正常请求目标？

**Comment by p4gefau1t** [comment]
这是个伪需求，你只要连接任何服务器，服务器就能拿到你代理服务器 IP

如果希望匿名访问，应该让所有的流量走 tor
