### ISSUE TITLE
使用docker方式启动server端报错

### ISSUE THREAD

**Issue by wangwii** [p4gefau1t/trojan-go#242]
报错内容：
<img width="991" alt="Screen Shot 2020-12-16 at 9 46 39 PM" src="https://user-images.githubusercontent.com/1000834/102356481-38a17500-3fe8-11eb-92f3-0aa9e4f1b395.png">
配置文件内容如下：
<img width="313" alt="Screen Shot 2020-12-16 at 10 04 45 PM" src="https://user-images.githubusercontent.com/1000834/102358665-bb2b3400-3fea-11eb-8f35-0d3483f35c72.png">

检查证书文件的路径，以及访问权限都是OK的：👇
<img width="655" alt="Screen Shot 2020-12-16 at 9 49 41 PM" src="https://user-images.githubusercontent.com/1000834/102356814-a64da100-3fe8-11eb-8103-6794babeca26.png">

请问具体是哪里出错了呢？

完整的运行过程如下：
<img width="1115" alt="Screen Shot 2020-12-16 at 10 05 55 PM" src="https://user-images.githubusercontent.com/1000834/102358790-e4e45b00-3fea-11eb-8dc5-682b5375775a.png">

**Comment by p4gefau1t** [comment]
证书和key路径不对

**Comment by wangwii** [comment]
路径怎么不对？ 是因为我放在了 根目录下？ 还是文件命名有问题？

我当前是放在根目录下的，所以配置文件中是：[cert: /conn.aibaby.online.crt 和 key: /conn.aibaby.online.key]
我贴的图片中可以看到，在根目录下[ls -l]时能看到 .crt 和 .key 两个文件。
请问我要怎么修正这个路径不对的问题？

**Comment by cccRaim** [comment]
我也有这个问题，请问解决了吗

**Comment by dmcdark** [comment]
不是路径不对，就是权限不对
chmod 755 证书路径

**Comment by cccRaim** [comment]
> 不是路径不对，就是权限不对 chmod 755 证书路径

我解决了，主要新版certbot使用了软链接作为证书路径，docker读取到的文件无法指向正确的地址，导致读不到文件。
所以解决方案就是把软链接目标文件夹也映射到docker内部。
（应该和你的问题不是同一个问题）

**Comment by dmcdark** [comment]
这不就是路径不对吗？
> > 不是路径不对，就是权限不对 chmod 755 证书路径
> 
> 
> 
> 我解决了，主要新版certbot使用了软链接作为证书路径，docker读取到的文件无法指向正确的地址，导致读不到文件。
> 
> 所以解决方案就是把软链接目标文件夹也映射到docker内部。
> 
> （应该和你的问题不是同一个问题）
