### ISSUE TITLE
疑问：websocket 配置中，两端的混淆密码设置无用

### ISSUE THREAD

**Issue by bt-worm** [p4gefau1t/trojan-go#244]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

## 简单描述这个 Bug
websocket 配置中，两端的混淆密码设置无用.
无论键值名称为obfuscation_password或password，无论服务端和客户端本项密码内容是否匹配，两端均能正常建立连接。

## 服务端和客户端配置文件

"websocket": {
		"enabled": true,
		"path": "/path",
		"host": "example.com",
		"obfuscation_password": "adasdfaf",
		"double_tls": true
}
## 服务端和客户端版本信息

服务端和客户端版本均为0.8.2

**Comment by tomyang001** [comment]
@bt-worm 我服务端也是这么写的 应该还缺点啥 因为客户端不设置也能连。。

**Comment by bt-worm** [comment]
了解到 混淆和双重TLS已弃用，由shadowsocks AEAD代替
