### ISSUE TITLE
mac 系统下载哪个版本呢？

### ISSUE THREAD

**Issue by litanwei** [p4gefau1t/trojan-go#249]
请教各位，下载里面没有mac 的，请问是和linux的共用么？是哪个版本， 感谢。

**Comment by DuckSoft** [comment]
时代变了，macOS 用户都不知道自己家内核叫 darwin 了……

**Comment by dmcdark** [comment]
笑死> 时代变了，macOS 用户都不知道自己家内核叫 darwin 了……
