### ISSUE TITLE
第一步 申请证书失败了

### ISSUE THREAD

**Issue by no-bibi** [p4gefau1t/trojan-go#25]
`➜  trojan-go-darwin-amd64 sudo ./trojan-go-darwin-amd64 -cert request
Password:
[INFO]  2020/04/21 23:00:43 Trojan-Go v0.2.0 initializing
[INFO]  2020/04/21 23:00:43 loading config file from /Users/btop/Downloads/trojan-go-darwin-amd64/config.json
[ERROR] 2020/04/21 23:00:43 github.com/p4gefau1t/trojan-go/proxy.(*proxyOption).Handle:option.go:34 failed to read config file | open /Users/btop/Downloads/trojan-go-darwin-amd64/config.json: no such file or directory`
下载的release版本,按照文档说明执行了一下 提示要找config.json

**Comment by no-bibi** [comment]
找到原因了 https://p4gefau1t.github.io/trojan-go/basic/config/ 写的 `app -cert request` 
需要改为 `app -autocert request`

**Comment by p4gefau1t** [comment]
文档有误，一会修改

**Comment by p4gefau1t** [comment]
已经修复
