### ISSUE TITLE
求助：编译出错

### ISSUE THREAD

**Issue by wang20150419** [p4gefau1t/trojan-go#252]
OS: Ubuntu 18.04.5 x86_64
go version: go1.15.6 linux/amd64

编译出错：
root@ubuntu:~/trojan-go$ go build -tags "client" -ldflags="-s -w"
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading golang.org/x/crypto v0.0.0-20200709230013-948cd5f35899
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/v2ray/v2ray-core v0.0.0-20200603100350-6b5d2fed91c0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/xtaci/smux v1.5.14
go: downloading github.com/shadowsocks/go-shadowsocks2 v0.1.0
go: downloading github.com/txthinking/socks5 v0.0.0-20200531111549-252709fcb919
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/refraction-networking/utls v0.0.0-20200601200209-ada0bb9b38a0
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading github.com/txthinking/runnergroup v0.0.0-20200327135940-540a793bb997
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
go: downloading github.com/txthinking/x v0.0.0-20200330144832-5ad2416896a9
go: downloading go.starlark.net v0.0.0-20200619143648-50ca820fafb9
# runtime/internal/atomic
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:13:6: Load redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:16:24
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:19:6: Loadp redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:22:32
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:25:6: Load64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:28:26
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:30:6: Xadd redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:39:37
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:33:6: Xadd64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:42:39
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: Xadduintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:45:47
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:39:6: Xchg redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:48:36
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:42:6: Xchg64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:51:38
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:45:6: Xchguintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:54:45
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:48:6: And8 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:63:27
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:48:6: too many errors

不知道如何解决。

**Comment by p4gefau1t** [comment]
看起来似乎是官方的库的问题？
