### ISSUE TITLE
[解决方法] 关于Trojan-go nat 类型 4 以及解决办法 FULLCONE

### ISSUE THREAD

**Issue by edmund-zhao** [p4gefau1t/trojan-go#262]
## 问题描述：

- 可以使用UDP，但NAT类型为4

- 客户端如下：
![image.png](https://i.loli.net/2021/02/03/R7qZK9BPUieIEHl.png)

- 服务端日志：有部分的UDP包被丢弃

## 解决办法：

- 1.把20000以上的端口都打开
- 2. 关闭/修改 UDP规则

```shell
centos : systemctl stop firewalld
Ubuntu: systemctl stop UFW
```

**Comment by CXwudi** [comment]
写给所有尝试用trojan-go加速游戏的人:

NAT 4 就是 Symmetric NAT, 基本告别网络游戏, 因为这一类应用需要FullCone NAT, 详见[Xray的discussion](https://github.com/XTLS/Xray-core/discussions/237)

解决方法: 想要加速游戏, 可能只能换Xray了, 详见[另一个Xray的discussion](https://github.com/XTLS/Xray-core/discussions/252)
