### ISSUE TITLE
有没可能提供安卓客户端支持？

### ISSUE THREAD

**Issue by txdywy** [p4gefau1t/trojan-go#27]
或者sip003那种插件，直接用ss客户端😆

**Comment by p4gefau1t** [comment]
已经有安卓客户端，从igniter改的，只是将Trojan-GFW核心更换为了Trojan-Go，源码在https://github.com/p4gefau1t/trojan-go-android，依赖库https://github.com/p4gefau1t/trojan-go-libs

Telegram群里有编译好的apk

**Comment by txdywy** [comment]
安卓也来个actions? :P

**Comment by damonchou** [comment]
老哥，怎么进你的TG群？？有链接吗？

**Comment by tangbao818** [comment]
同求安卓安装包, 现在只能在PC上连接, GCP上使用效果非常的好.

**Comment by hak0** [comment]
请问如何编译？没有在那个repo里找到任何的说明

**Comment by zhedielj** [comment]
发个编译好的apk吧，安卓上没有能用的Trojan go客户端，Google play上的那个不行

**Comment by mmycly** [comment]
> 已经有安卓客户端，从igniter改的，只是将Trojan-GFW核心更换为了Trojan-Go，源码在https://github.com/p4gefau1t/trojan-go-android ，依赖库 https://github.com/p4gefau1t/trojan-go-libs
> 
> Telegram群里有编译好的apk

大佬求入群啊~，想下一个android客户端~~
TG入群答案不小心点错了，访问不了了

**Comment by Butterflyflower** [comment]
@mmycly https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet.plugin.trojan_go

https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet

**Comment by mmycly** [comment]
SagerNet配置了插件 websocket还是连不上服务端，不知道是哪里的问题。
想试试看igniter-go能不能连上。。。

**Comment by Butterflyflower** [comment]
@mmycly SagerNet不能跳过证书验证，是不是证书没有配置好。

**Comment by mmycly** [comment]
@Butterflyflower 太感谢了， 折腾了下连上了~

**Comment by zzwwzh** [comment]
第一次玩电报，搜索到了交流反馈群，点进去查看，然后就被屏蔽了。。。
