### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NetHeritage** [p4gefau1t/trojan-go#272]
Certificates issued by let's encrypt and zerossl will expire in 90 days. Trojan-go does not reload newly-renewed certificates automatically and fails every 90 days. This is not a problem in most circumstances and It will be better off if  trojan-go can reload new certificates automatically.

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/p4gefau1t/trojan-go/pull/338
