### ISSUE TITLE
最近go是不是很不稳定啊。经常需要重启，才能连接。一堆报错。

### ISSUE THREAD

**Issue by totodata** [p4gefau1t/trojan-go#286]
[ERROR] 2021/03/29 11:25:13 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial 8.131.70.160:33301 | dial tcp 8.131.70.160:33301: connect: connection timed out
[ERROR] 2021/03/29 11:25:13 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial 8.131.70.160:33301 | dial tcp 8.131.70.160:33301: connect: connection timed out
[ERROR] 2021/03/29 11:25:13 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial 8.131.70.160:33301 | dial tcp 8.131.70.160:33301: connect: connection timed out
[ERROR] 2021/03/29 11:25:13 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial 8.131.70.160:33301 | dial tcp 8.131.70.160:33301: connect: connection timed out
[ERROR] 2021/03/29 11:25:13 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial 8.131.70.160:33301 | dial tcp 8.131.70.160:33301: connect: connection timed out
[ERROR] 2021/03/29 11:25:13 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial 8.131.70.160:33301 | dial tcp 8.131.70.160:33301: connect: connection timed out
[ERROR] 2021/03/29 11:30:54 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:44378->31.13.75.1:443: read: connection reset by peer
[ERROR] 2021/03/29 11:31:26 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:36448->52.114.20.18:443: read: connection reset by peer
[ERROR] 2021/03/29 11:32:14 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:47188: read: connection timed out
[ERROR] 2021/03/29 11:32:16 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:48818: read: connection timed out
[ERROR] 2021/03/29 11:32:17 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:47218: read: connection timed out
[ERROR] 2021/03/29 11:32:18 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:47210: read: connection timed out
[ERROR] 2021/03/29 11:32:20 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:48028: read: connection timed out
[ERROR] 2021/03/29 11:32:22 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:47200: read: connection timed out
[ERROR] 2021/03/29 11:32:22 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:47262: read: connection timed out
[ERROR] 2021/03/29 11:32:23 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:48652: read: connection timed out
[ERROR] 2021/03/29 11:32:24 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:81 read tcp 10.0.4.9:443->117.30.160.55:47176: read: connection timed out

**Comment by Xx0101** [comment]
同感

**Comment by feixuedi** [comment]
这个和 #203 是同一个问题，linux服务器单个进程默认fd是1024，tcp连接太多拿不到空闲的fd了
粗暴的办法就是：
echo ulimit -n 40000 >> /etc/profile
source /etc/profile

**Comment by hunao0221** [comment]
> 这个和 #203 是同一个问题，linux单个进程默认fd是1024，tcp连接太多拿不到空闲的fd了
> 粗暴的办法就是：
> echo ulimit -n 40000 >> /etc/profile
> source /etc/profile

thanks but this is not working on my side.

**Comment by StephenAnboer** [comment]
[ERROR] 2021/04/19 11:32:24 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 read tcp 10.0.4.9:443->117.30.160.55:47176: read: connection timed out

也是这种问题，但是很奇怪，用小火箭在手机端使用没问题，windows端使用的稳定版的qv2ray就一直报错用不了

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/p4gefau1t/trojan-go/pull/313

**Comment by iSteveyang** [comment]
大佬，最近还是总断链，重启后一段时间又是这样，满屏log基本上同一个错。这log里面ip都不是用户ip，我是直接一键安装的，没改过配置，不知道到底哪里有问题
`[ERROR] 2021/07/11 00:58:40 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:14828->40.126.35.80:443: read: connection reset by peer
[ERROR] 2021/07/11 00:58:42 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:14826->40.126.35.80:443: read: connection reset by peer
[ERROR] 2021/07/11 00:58:45 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:38572->20.190.163.18:443: read: connection reset by peer
[ERROR] 2021/07/11 00:58:47 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:9762->40.126.35.64:443: read: connection reset by peer
[ERROR] 2021/07/11 00:58:48 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:8752->20.190.163.19:443: read: connection reset by peer`

**Comment by ShoukakuChuuCC** [comment]
> 大佬，最近还是总断链，重启后一段时间又是这样，满屏log基本上同一个错。这log里面ip都不是用户ip，我是直接一键安装的，没改过配置，不知道到底哪里有问题
> `[ERROR] 2021/07/11 00:58:40 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:14828->40.126.35.80:443: read: connection reset by peer [ERROR] 2021/07/11 00:58:42 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:14826->40.126.35.80:443: read: connection reset by peer [ERROR] 2021/07/11 00:58:45 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:38572->20.190.163.18:443: read: connection reset by peer [ERROR] 2021/07/11 00:58:47 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:9762->40.126.35.64:443: read: connection reset by peer [ERROR] 2021/07/11 00:58:48 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:80 read tcp 10.0.0.9:8752->20.190.163.19:443: read: connection reset by peer`

https://www.v2ex.com/t/788719，我也经常断，联通宽带，从websocket换成tcp，就好很多

**Comment by iSteveyang** [comment]
我的网络应该是走CN2的，测试应该是，和163扩容有关系吗？
