### ISSUE TITLE
建议在systemd模板中设定LimitNOFILE

### ISSUE THREAD

**Issue by Urliuo** [p4gefau1t/trojan-go#306]
直接按照systemd模板，在同时连接数过多的情况下会出现无法连接的问题
其原因应该是 file descriptor 超限了
很多人知道修改 ulimit -n，很多服务商的默认配置也做了修改
但是有不少人没有意识到，systemd不会遵循PAM模块的配置，需要另行处理
所以建议直接在trojan-go.service设定LimitNOFILE，以免新手遇到问题

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/p4gefau1t/trojan-go/pull/313
