### ISSUE TITLE
［问题］使用 fail2ban 屏蔽多次验证失败的 ip 是否会增加被检测的可能性

### ISSUE THREAD

**Issue by zoenglinghou** [p4gefau1t/trojan-go#309]
我最近想使用如下的 fail2ban 规则屏蔽多次验证失败的 ip 地址。
```
failed to perform tls handshake with <HOST>:\d.*, redirecting | tls: first record does not look like a TLS handshake
```
多次验证失败的访问基本可以被确定是主动探测的流量。
- 用 fail2ban + 防火墙屏蔽的方式，主动探测方得到的回应是否与 Shadowsocks [断开链接](https://p4gefau1t.github.io/trojan-go/basic/trojan/)一致？
- 如果不一致（即与一般代理服务器行为模式不同），这样做是否会增加被主动探测的可能性/特征？

**Comment by Loyalsoldier** [comment]
需要防主动探测的话，建议在 Trojan-Go 前使用 Nginx 等 Web server。

**Comment by zoenglinghou** [comment]
我有使用 Nginx，只是好奇这样的配置会不会改变被探测到的几率

**Comment by NetHeritage** [comment]
> 
> 
> 需要防主动探测的话，建议在 Trojan-Go 前使用 Nginx 等 Web server。

trojan-go在web server后面吗？

**Comment by zoenglinghou** [comment]
> > 需要防主动探测的话，建议在 Trojan-Go 前使用 Nginx 等 Web server。
> 
> trojan-go在web server后面吗？
在
