### ISSUE TITLE
feature request: 动态修改某些配置

### ISSUE THREAD

**Issue by fregie** [p4gefau1t/trojan-go#326]
现在如果需要修改某些服务端配置，如remote_addr,证书路径等，需要修改配置后重启服务，这可能导致客户端无预兆的断开连接，希望能提供动态修改某些配置的grpc接口。
我可以进行这项修改，并提交PR。
@p4gefau1t

**Comment by qiuzi** [comment]
@fregie 有api面板项目推荐吗？

**Comment by fregie** [comment]
> @fregie 有api面板项目推荐吗？

没，我没用过trojan的dashboard

**Comment by Loyalsoldier** [comment]
欢迎 PR。

**Comment by fregie** [comment]
发现证书已经有定期更新的功能，暂时不需要动态更新了。
