### ISSUE TITLE
[BUG]这个库在ios的packettunnel里使用会内存爆炸

### ISSUE THREAD

**Issue by Yewenyu** [p4gefau1t/trojan-go#327]
你好，我想在ios中使用这个库，但是由于ios的packettunnel内存限制，内存超过15M就会崩掉
请问有什么方法加快这个库的内存释放

**Comment by LaoHuan** [comment]
我也准备在ios中使用。你也用的tun2socks来做的吗？

**Comment by Yewenyu** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LaoHuan ***@***.***&gt;
发送时间: 2021年5月18日 20:16
收件人: p4gefau1t/trojan-go ***@***.***&gt;
抄送: Yewenyu ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[p4gefau1t/trojan-go] [BUG]这个库在ios的packettunnel里使用会内存爆炸 (#327)





 
我也准备在ios中使用。你也用的tun2socks来做的吗？

**Comment by Loyalsoldier** [comment]
> 你好，我想在ios中使用这个库，但是由于ios的packettunnel内存限制，内存超过15M就会崩掉
> 请问有什么方法加快这个库的内存释放

去掉某些不需要的模块，应该有所改善。

**Comment by 594810899** [comment]
> 你好，我想在ios使用这个库，但但由于ios的packettunnel内存限制，内存超过15M会崩掉> 请问有什么方法加快这个库的内存释放


你好， 请问一下，你是用的哪个库来接入trojan的？期待你的回复，谢谢！

**Comment by 594810899** [comment]
> 我也准备在ios中使用。你也用的tun2socks来做的吗？

你好， 请问你在ios中实现了trojan功能了吗？
