### ISSUE TITLE
希望trojan-go支持proxy protocol

### ISSUE THREAD

**Issue by lxhao61** [p4gefau1t/trojan-go#337]
希望trojan-go支持proxy protocol，特别是支持proxy protocol接收，这样nginx SNI分流就可以开启proxy protoco发送了（nginx SNI分流的proxy protoco发送是全局模式的）。

**Comment by aglent** [comment]
支持
现在只能在xray里的trojan用上proxy protocol

**Comment by lxhao61** [comment]
> 支持
> 现在只能在xray里的trojan用上proxy protocol
是的。

**Comment by onlyJinx** [comment]
+1，nginx前置后使用SNI分流，因为想要获取真实IP所以希望trojan-go能添加proxy_protocol支持

**Comment by h2ch** [comment]
支持，这样nginx stream分流就不用再多一个server脱掉proxy protocol
