### ISSUE TITLE
关于自动 ssl

### ISSUE THREAD

**Issue by josh-chan** [p4gefau1t/trojan-go#34]
简单看了一下代码，发现 ssl 自动那个不太自动。
是否可以实现像 caddy 那样的？提供域名就行，启动caddy后就自动获取证书了。

好像有些难度，我不了解 trojan 协议，能否这样改：
 
用 http 监听端口，用 certmagic 或者 autocert 获取证书，然后在 http.Handler 里面 hijack 拿到 connection， 再处理 trojan 协议。
这样再外层就是一个 http server, 不是现在的 trojan tcp server. 不知道是否可行。
@p4gefau1t

**Comment by p4gefau1t** [comment]
不太明白用http监听端口的含义

本来使用ACME就是需要监听80和443的呀

**Comment by josh-chan** [comment]
@p4gefau1t 这个有实现 https://github.com/liberal-boy/tls-shunt-proxy
比我上面说明的好像更好些。

**Comment by colachg** [comment]
据我所知：还可以通过验证域名的txt记录，来确认域名的所有权。这是cloudflare的[例子](https://go-acme.github.io/lego/dns/cloudflare/)。

可以在配置文件中（或者环境变量指定参数值），程序在运行的时候，检查`/etc/trojan-go`下面是否有对应的证书文件。没有则自动申请，有则检查下有效期，判断是否更新。

@josh-chan 是不是这个需求？

**Comment by p4gefau1t** [comment]
证书申请不再被支持，可能考虑另开一个项目做这件事
