### ISSUE TITLE
[BUG] 版本 0.10.2 ECC 证书支持错误 

### ISSUE THREAD

**Issue by itspig** [p4gefau1t/trojan-go#349]
更新 v0.10.2 版本后，服务器无法连接，程序提示如下错误

> [ERROR] 2021/05/27 11:35:42 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | tls: unsupported certificate curve (P-256)

证书是利用 Letsencrypt 颁发的 ecc 证书

重装 v0.10.0 版本后，服务器恢复正常

系统 Ubuntu 20.04.2 LTS，在 GCP，ORACLE CLOUD 等服务器上都复现过

麻烦 @Loyalsoldier 大佬有空检查下，感谢 😊

**Comment by kongbai39** [comment]
一样
[ERROR] 2021/05/27 11:47:01 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | tls: unsupported certificate curve (P-256)

**Comment by Loyalsoldier** [comment]
RSA 证书能复现吗？

**Comment by littlef0x** [comment]
Exactly the same error here. Let's encrypt certificate (SHA256withRSA) managed by Caddy.
Caddy's https service (on another port) works well. Trojan-go using the same certificate does not work with the same error log as above. Firefox returns SSL_ERROR_NO_CYPHER_OVERLAP.

**Comment by luoluodaduan** [comment]
rsa 可以 ecc不行

**Comment by ZichengLouche** [comment]
我这边一直使用的都是Let's Encrypt颁发的证书，trojan-go版本从0.8.1 - 0.9.1一路使用过来都没问题，没想到这次v0.10.2版本一更新，出现了这个重大bug，完全不能使用了，报错：[ERROR] 2021/05/29 11:05:37 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | tls: unsupported certificate curve (P-256)

**Comment by whoerau** [comment]
喜加一

**Comment by thisdk** [comment]
同款问题

**Comment by fregie** [comment]
Fixed.
作者合入修改之前，可以先使用这个仓库的代码构建修复后的版本。
https://github.com/fregie/trojan-go

**Comment by Jsongcloud** [comment]
isssue +1

Client端报错。
[ERROR] 2021/05/30 09:29:19 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | tls failed to handshake with remote server | remote error: tls: handshake failure

Server端主程序回滚到旧版 0.10.0 问题解决。

**Comment by Loyalsoldier** [comment]
已回退到 v0.10.0 的代码。
