### ISSUE TITLE
请问如何后台自启

### ISSUE THREAD

**Issue by sjnhnp** [p4gefau1t/trojan-go#35]
因为tg群 显示 无法进入，
所以只能来这里询问问题

1、如何把运行命令，后台运行+开机自启

2、如何禁用日志，我看见服务器运行后，上网会出现info，请问可以禁用不显示吗？

**Comment by p4gefau1t** [comment]
1. 关于后台和开机自启请参考trojan-go.service并配置systemd，如果没有接触过，建议搜索相关资料简单了解
2. 请设置日志等级```log_level```，具体参考文档 https://p4gefau1t.github.io/trojan-go/basic/fullconfig/

关于tg群，原因可能是加群之后没有及时进行校验导致被ban

**Comment by sjnhnp** [comment]
那如何解决 ban

**Comment by TheWanderingCoel** [comment]
@sjnhnp 你的tg昵称是？
