### ISSUE TITLE
[BUG]trojan not support arm64 machine

### ISSUE THREAD

**Issue by kilvn** [p4gefau1t/trojan-go#355]
oraclecloud 最新的ARM (VM.Standard.A1.Flex)运行提示  trojan not support arm64 machine

**Comment by sousa-chinensis** [comment]
This is very interesting. 

I tried running amd64 version of trojan-go (https://github.com/p4gefau1t/trojan-go/releases/download/v0.10.3/trojan-go-linux-amd64.zip) on aarch64 machine. 

There is an error, but it said:

```
Failed to execute process './trojan-go'. Reason:
exec: Exec format error
The file './trojan-go' is marked as an executable but could not be run by the operating system.  
```

I checked on Oracle's blog (https://blogs.oracle.com/cloud-infrastructure/moving-to-ampere-a1-compute-instances-on-oracle-cloud-infrastructure) and it says that VM.Standard.A1.Flex uses Arm64v8. 

So, please download the one for ARMv8 (https://github.com/p4gefau1t/trojan-go/releases/download/v0.10.3/trojan-go-linux-armv8.zip). 

If that does not work. Please attach your full console output.

**Comment by sousa-chinensis** [comment]
Oh, it seems that you are using the origin implementation of Trojan in C++ (https://github.com/trojan-gfw/trojan/). That does not work in ARMv8.

**Comment by Loyalsoldier** [comment]
只要机器能安装 Go，基本都能使用。还是不能使用的话，请提供系统详细信息。
