### ISSUE TITLE
[BUG]cloudflare的cdn加使用Shadowsocks AEAD进行二次加密出现这个问题

### ISSUE THREAD

**Issue by Potterli20** [p4gefau1t/trojan-go#366]
## 简单描述这个 Bug
[ERROR] 2021/06/26 07:12:47 github.com/p4gefau1t/trojan-go/tunnel/shadowsocks.(*Server).AcceptConn:server.go:37 shadowsocks failed to decrypt | EOF
[ERROR] 2021/06/26 07:12:47 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | invalid aead payload

## 如何复现这个 Bug
cloudflare 的cdn加使用Shadowsocks AEAD进行二次加密
在此描述复现这个Bug所需要的操作步骤

**Comment by marco9989** [comment]
我也出现这个问题

**Comment by a1328788808** [comment]
不用cloudflare，AEAD也是有问题的。
