### ISSUE TITLE
close

### ISSUE THREAD

**Issue by iceyear** [p4gefau1t/trojan-go#367]

**Comment by ArcCal** [comment]
用大型机翻墙的，是真大佬啊

**Comment by mritd** [comment]
[linux-s390x.tar.gz](https://github.com/p4gefau1t/trojan-go/files/6767126/linux-s390x.tar.gz)

你试试这个能运行不...

**Comment by HelloWorldWinning** [comment]
> [linux-s390x.tar.gz](https://github.com/p4gefau1t/trojan-go/files/6767126/linux-s390x.tar.gz)
> 
> 你试试这个能运行不...

谢谢。works
