### ISSUE TITLE
[BUG]使用yaml配置文件时，default_policy参数不生效

### ISSUE THREAD

**Issue by gcawliw** [p4gefau1t/trojan-go#372]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

当使用yaml配置文件时，route模块default_policy参数不生效，不管配置成bypass或block，都不生效。
当我使用json配置文件时，一切正常。

## 服务端和客户端配置文件
run-type: client
local-addr: 0.0.0.0
local-port: 8888
remote-addr: test123.com
remote-port: 443
password:
    - test123
router:
    enabled: true
    bypass: []
    block: []
    proxy: []
    default_policy: bypass

## 服务端和客户端版本信息
trojan-go v0.10.4

**Comment by tan-kuku** [comment]
在使用 YAML 配置文件的时候，`default_policy` 需要写成 `default-policy`。

请参考[Trojan-Go 文档](https://p4gefau1t.github.io/trojan-go/basic/full-config/)：

> Trojan-Go支持对人类更友好的YAML语法，配置文件的基本结构与JSON相同，效果等价。但是为了遵守YAML的命名习惯，你需要把下划线("_")转换为横杠("-")，如`remote_addr`在YAML文件中为`remote-addr`。
