### ISSUE TITLE
系统代理问题

### ISSUE THREAD

**Issue by xiran2018** [p4gefau1t/trojan-go#373]
请问代码在哪里设置的在客户端的主机上启动代理，从而可以代理主机上的所有流量？这部分没有找到呢，我看到了proxy文件夹和里面的client文件夹，但是还是没有看到启动客户端主机系统代理的代码
我上边说的可能不太清楚，我的意思是，在哪里调用的函数，从而让客户端主机的所有流量都能转发给trojan，从而让客户端的trojan转发流量到代理服务器上

**Comment by fregie** [comment]
应该是不行的，trojan只能提供socks5代理，也只能代理tcp和udp。
如果想全局代理流量的话，建议配合tun2socks使用
