### ISSUE TITLE
[BUG] trojan-go v0.10.5 SSL handshake failed error 525

### ISSUE THREAD

**Issue by wangwill** [p4gefau1t/trojan-go#378]
使用 v0.10.5-linux-arm  trojan-go 出现 SSL handshake failed error 525

回滚v0.10.4-linux-arm trojan-go 问题消失

**Comment by ArcCal** [comment]
信息也太少了，开发者都不知道怎么排查问题

**Comment by wangwill** [comment]
大致表现为前端的网页是无法打开
但是Trojan-go  websocket 流量还是可以跑

套CDN后显示的SSL handshake error 525 code   不套CDN直接访问现象是无法打开网页

**Comment by waynon** [comment]
我也更新到了v0.10.5，没有任何问题

**Comment by liuyinltemp** [comment]
发现大佬最近几次更新，经常出现ssl错误，问题出现在ssl为ecc证书的情形下，请修复。

**Comment by Loyalsoldier** [comment]
请尝试最新的 [v0.10.6](https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.6)

**Comment by wangwill** [comment]
> 请尝试最新的 [v0.10.6](https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.6)

找到造成SSL handshake ERROR的问题了

我使用的是ECC证书

在 v0.10.4  config.json 中我设置的 “alphn”: ["http/1.3"]  正常使用
可以正常访问伪装网站
------------------------------------------------------------------------
在 v0.10.6 必须把 “alphn”: ["http/1.3"] 改成 “alphn”: ["http/1.1"]
否则访问伪装网站 显示 SSL handshake ERROR

错误日志:
[ERROR] 2021/09/14 09:49:55 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | tls: client requested unsupported application protocols ([h2 http/1.1])

**Comment by liuyinltemp** [comment]
> > 请尝试最新的 [v0.10.6](https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.6)
> 
> 找到造成SSL handshake ERROR的问题了
> 
> 我使用的是ECC证书
> 
> ## 在 v0.10.4 config.json 中我设置的 “alphn”: ["http/1.3"] 正常使用
> 可以正常访问伪装网站
> 在 v0.10.6 必须把 “alphn”: ["http/1.3"] 改成 “alphn”: ["http/1.1"]
> 否则访问伪装网站 显示 SSL handshake ERROR
> 
> 错误日志:
> [ERROR] 2021/09/14 09:49:55 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | tls: client requested unsupported application protocols ([h2 http/1.1])

非常感谢，真的是这样，我也是ECC证书，一直限定用H2，改成Http1.1就可以了
