### ISSUE TITLE
[BUG]请问archlinux的客户端哪里能获取证书

### ISSUE THREAD

**Issue by kindusmithkindu** [p4gefau1t/trojan-go#380]
![截图_2021-09-08_16-47-06](https://user-images.githubusercontent.com/88788264/132478107-64be9e2f-9d0e-444e-a169-7795af470bbc.png)
如图,在哪里获取证书?谢谢

**Comment by nobody1919** [comment]
客户端配置参考：https://raw.githubusercontent.com/p4gefau1t/trojan-go/master/example/client.json
