### ISSUE TITLE
[BUG]tls handshake failed | EOF   v0.10.5

### ISSUE THREAD

**Issue by guhill** [p4gefau1t/trojan-go#381]
大佬,采用最新版的,运行一会google打不开,开始的时候可以打开 

服务端 :windows amd64
配置文件
{
  "run_type": "server",
  "local_addr": "0.0.0.0",
  "local_port": 443,
  "remote_addr": "127.0.0.1",
  "remote_port": 8888,
  "log_level": 1,
  "log_file": "",
  "password": [
	"xxxxxxxxxx"
   ],
  "disable_http_check": false,
  "udp_timeout": 60,
  "ssl": {
    "verify": true,
    "verify_hostname": true,
	"cert": "C:/xxxx.xxxx.com/fullchain.pem",
	"key": "C:/xxxx.xxxx.com/privkey.pem",
    "key_password": "",
    "cipher": "",
    "curves": "",
    "prefer_server_cipher": false,
    "sni": "xxxx.xxxx.com",
    "alpn": [
      "http/1.1"
    ],
    "session_ticket": true,
    "reuse_session": true,
    "plain_http_response": "",
    "fallback_addr": "xxxx.xxxx.com",
    "fallback_port": 800,
    "fingerprint": ""
  },
  "tcp": {
    "no_delay": false,
    "keep_alive": true,
    "prefer_ipv4": true
  },
  "mux": {
    "enabled": false,
    "concurrency": 4,
    "idle_timeout": 60
  },
  "router": {
    "enabled": false,
    "bypass": [],
    "proxy": [],
    "block": [],
    "default_policy": "proxy",
    "domain_strategy": "as_is",
    "geoip": "$PROGRAM_DIR$/geoip.dat",
    "geosite": "$PROGRAM_DIR$/geosite.dat"
  },
  "websocket": {
    "enabled": false,
    "path": "",
    "host": ""
  },
  "shadowsocks": {
    "enabled": false,
    "method": "AES-128-GCM",
    "password": ""
  },
  "transport_plugin": {
    "enabled": false,
    "type": "",
    "command": "",
    "option": "",
    "arg": [],
    "env": []
  },
  "forward_proxy": {
    "enabled": false,
    "proxy_addr": "",
    "proxy_port": 0,
    "username": "",
    "password": ""
  },
  "mysql": {
    "enabled": false,
    "server_addr": "localhost",
    "server_port": 3306,
    "database": "",
    "username": "",
    "password": "",
    "check_rate": 60
  },
  "api": {
    "enabled": false,
    "api_addr": "",
    "api_port": 0,
    "ssl": {
      "enabled": false,
      "key": "",
      "cert": "",
      "verify_client": false,
      "client_cert": []
    }
  }

客户端 openwrt pa$$wall

出错信息:反复报
[WARN]  2021/09/14 00:44:48 connection with invalid trojan header from xxx.xxx.xxx.xxx:59922 | failed to read hash | EOF
最后连接google连接不上时候报:
[ERROR] 2021/09/14 00:45:15 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | EOF

日志部分:
[WARN]  2021/09/14 00:44:48 connection with invalid trojan header from xxx.xxx.xxx.xxx:59942 | failed to read hash | EOF
[WARN]  2021/09/14 00:44:48 redirecting connection from xxx.xxx.xxx.xxx:59942 to 127.0.0.1:8888
[WARN]  2021/09/14 00:44:48 connection with invalid trojan header from xxx.xxx.xxx.xxx:59934 | failed to read hash | EOF
[WARN]  2021/09/14 00:44:48 redirecting connection from xxx.xxx.xxx.xxx:59934 to 127.0.0.1:8888
[INFO]  2021/09/14 00:44:48 redirection done
[INFO]  2021/09/14 00:44:48 redirection done
[INFO]  2021/09/14 00:44:48 tls connection from xxx.xxx.xxx.xxx:59952
[WARN]  2021/09/14 00:44:48 connection with invalid trojan header from xxx.xxx.xxx.xxx:59952 | failed to read hash | EOF
[WARN]  2021/09/14 00:44:48 redirecting connection from xxx.xxx.xxx.xxx:59952 to 127.0.0.1:8888
[INFO]  2021/09/14 00:44:48 redirection done
............................
.................................
[INFO]  2021/09/14 00:44:48 redirection done
[INFO]  2021/09/14 00:44:48 tls connection from xxx.xxx.xxx.xxx:59958
[INFO]  2021/09/14 00:44:48 redirection done
[WARN]  2021/09/14 00:44:48 connection with invalid trojan header from xxx.xxx.xxx.xxx:59958 | failed to read hash | EOF
[WARN]  2021/09/14 00:44:48 redirecting connection from xxx.xxx.xxx.xxx:59958 to 127.0.0.1:8888
[INFO]  2021/09/14 00:44:48 redirection done
[INFO]  2021/09/14 00:44:53 tcp connection from xxx.xxx.xxx.xxx:60022
[INFO]  2021/09/14 00:44:53 tls connection from xxx.xxx.xxx.xxx:60022
[INFO]  2021/09/14 00:44:53 user xxxxxxxx5222c5904d6925ec0ee7d85612b07xxxxxxx from xxx.xxx.xxx.xxx:59912 tunneling to 13.10
7.42.12:443 closed sent: 10.04 KiB recv: 1.57 KiB
[INFO]  2021/09/14 00:44:53 user xxxxxxxx5222c5904d6925ec0ee7d85612b07xxxxxxx from xxx.xxx.xxx.xxx:59824 tunneling to 81.90
..................................................................

0.105.16:443 closed sent: 4.47 KiB recv: 1.62 KiB
[INFO]  2021/09/14 00:44:53 user xxxxxxxx5222c5904d6925ec0ee7d85612b07xxxxxxx from xxx.xxx.xxx.xxx:59820 tunneling to 1.0.0
.2:443 closed sent: 7.49 KiB recv: 1.65 KiB
[ERROR] 2021/09/14 00:44:59 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connec
tion | freedom failed to dial 162.125.2.3:443 | dial tcp4 162.125.2.3:443: connectex: A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[INFO]  2021/09/14 00:44:59 user xxxxxxxx5222c5904d6925ec0ee7d85612b07xxxxxxx from xxx.xxx.xxx.xxx:59898 tunneling to 162.1
25.2.3:443 closed sent: 0 B recv: 0 B
[ERROR] 2021/09/14 00:45:01 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connec
tion | freedom failed to dial 162.125.2.3:443 | dial tcp4 162.125.2.3:443: connectex: A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[INFO]  2021/09/14 00:45:01 user xxxxxxxx5222c5904d6925ec0ee7d85612b07xxxxxxx from xxx.xxx.xxx.xxx:59582 tunneling to 162.1
25.2.3:443 closed sent: 0 B recv: 0 B
[INFO]  2021/09/14 00:45:15 tcp connection from xxx.xxx.xxx.xxx:60072
[ERROR] 2021/09/14 00:45:15 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | E
OF
[INFO]  2021/09/14 00:45:15 tcp connection from xxx.xxx.xxx.xxx:60078
[ERROR] 2021/09/14 00:45:15 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | E
OF
^C
请大佬修复...

**Comment by Loyalsoldier** [comment]
请尝试最新的 [v0.10.6](https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.6)

**Comment by HosseinMomeni7091** [comment]
Hi, I have changed "local-port" to a new one such as 8443 instead of 433 and finally, it has been resolved.

**Comment by iseeChenYJ** [comment]
我也是，443端口扫了下没被占用，但是莫名就不行，换了 config.json 里面 "local-port" 就可以了

> Hi, I have changed "local-port" to a new one such as 8443 instead of 433 and finally, it has been resolved.

**Comment by carasha** [comment]
> 我也是，443端口扫了下没被占用，但是莫名就不行，换了 config.json 里面 "local-port" 就可以了
> 
> > Hi, I have changed "local-port" to a new one such as 8443 instead of 433 and finally, it has been resolved.

我這幾天也是出現這個問題 , 但是 , 如果你把 local-port 443 換成別的 port , 那不就失去把 trojan 流量 隱藏 在 https 裡這個最原始的意義了嗎 ?

**Comment by leiyq123** [comment]
换个端口就好了，我操了，一直重启都恢复不了，服务器一直没动过环境，感谢
