### ISSUE TITLE
[BUG]trojan-go构建失败

### ISSUE THREAD

**Issue by kwokkakit** [p4gefau1t/trojan-go#388]
go: github.com/go-sql-driver/mysql@v1.6.0: Get "https://goproxy.io/github.com/go-sql-driver/mysql/@v/v1.6.0.mod": x509: certificate has expired or is not yet valid: current time 2021-09-26T07:19:29Z is after 2021-09-25T00:00:00Z

Building targets
go: github.com/go-sql-driver/mysql@v1.6.0: Get "https://goproxy.io/github.com/go-sql-driver/mysql/@v/v1.6.0.mod": x509: certificate has expired or is not yet valid: current time 2021-09-26T07:19:31Z is after 2021-09-25T00:00:00Z

make[3]: *** [Makefile:78: /workspace/target-mips_24kc_musl/trojan-go-0.10.6/.built] Error 1

**Comment by Loyalsoldier** [comment]
Please use the official modules proxy `proxy.golang.org`
