### ISSUE TITLE
有计划实现一套全功能API吗?

### ISSUE THREAD

**Issue by strahe** [p4gefau1t/trojan-go#4]
便于扩展例如多用户管理, Dashboard 等配套设施?

**Comment by strahe** [comment]
暂时没计划或者规划比较靠后的话, 我可以协助实现一两个模块.

**Comment by p4gefau1t** [comment]
API的具体形式是怎样的呢，可以详细描述一下吗。

目前暂时没有计划，而且trojan官方的设计思路是暴露出数据库进行交互，所以这个项目也基本是这样做，通过数据库操作来实现对用户的管理。

**Comment by strahe** [comment]
大致就是 用户不直接操作数据库, 通过API间接操作, 比如 `/api/add-user` `/api/delete-user` `/api/stats` 类似这样.

**Comment by p4gefau1t** [comment]
直接暴露http接口有可能会带来一些安全性的问题吧，以及被主动探测的可能？

**Comment by strahe** [comment]
可以`listen localhost` 以及 配合jwt或者 常规http 授权.

**Comment by FenghenHome** [comment]
go语言可以自己加，很简单的，加api的的确有被探测风险

**Comment by lidashuang** [comment]
数据库不香吗？🤔

**Comment by p4gefau1t** [comment]
感觉如果只是作为http服务器监听本地，那和直接操作数据库就没什么区别了吧
而且现在已经也有挺多的现成的面板可以对接数据库了

**Comment by FenghenHome** [comment]
是的，建议关闭吧，或者自己改下

**Comment by nesnode** [comment]
要考虑到只有512MB内存的VPS，同时运行 v2ray 与 trojan 就没多少内存去跑 MySQL 了。

**Comment by p4gefau1t** [comment]
已经初步实现
