### ISSUE TITLE
[BUG] failed to accept conn | not a valid websocket handshake request: *.*.*.*:45104

### ISSUE THREAD

**Issue by qdnice** [p4gefau1t/trojan-go#419]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

## 简单描述这个 Bug
使用一键安装trojan-go脚本 bash <(curl -sL https://s.hijk.art/trojan-go.sh)，成功完成并运行，但是用最新0.10版igniter-go连接时，服务器端log 提示如下
[INFO]  2022/02/04 01:47:38 tcp connection from 162.*.*.*:25796
[INFO]  2022/02/04 01:47:38 tls connection from 162.*.*.*:25796
[ERROR] 2022/02/04 01:47:38 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | not a valid websocket handshake request: 162.*.*.*:25796
[WARN]  2022/02/04 01:47:38 redirecting connection from 162.*.*.*:25796 to 127.0.0.1:80
[INFO]  2022/02/04 01:48:44 redirection done

客户端提示 连接 www.google.com失败 handshake failed 

## 服务器和客户端环境信息
服务器 全新ubuntu20.04 LTS
客户端  igniter-go 0.10.4-beta

在此描述你的服务器和客户端所处的网络环境，系统架构，以及其他信息

请问这是系统bug还是我的配置问题？

祝 虎年吉祥，万事如意！

**Comment by Potterli20** [comment]
这是多久没更新？

**Comment by qdnice** [comment]
> 这是多久没更新？

哦，我是小白，能请教下怎么更新吗？

**Comment by Potterli20** [comment]
> > 这是多久没更新？
> 
> 哦，我是小白，能请教下怎么更新吗？

问你的脚本作者了

**Comment by qdnice** [comment]
> > > 这是多久没更新？
> > 
> > 
> > 哦，我是小白，能请教下怎么更新吗？
> 
> 问你的脚本作者了

经过一番折腾，我把trojan-go手工升级为0.10.6，但是服务器日志依然handshake错误

Feb 04 02:49:42 localhost trojan-go[9982]: [INFO]  2022/02/04 02:49:42 trojan-go v0.10.6 initializing
Feb 04 02:51:49 localhost trojan-go[9982]: [INFO]  2022/02/04 02:51:49 tcp connection from 162.*:45388
Feb 04 02:51:49 localhost trojan-go[9982]: [INFO]  2022/02/04 02:51:49 tls connection from 162.*:45388
Feb 04 02:51:49 localhost trojan-go[9982]: [ERROR] 2022/02/04 02:51:49 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | not a valid websocket handshake request: 162.*:45388
Feb 04 02:51:49 localhost trojan-go[9982]: [WARN]  2022/02/04 02:51:49 redirecting connection from 162.*:45388 to 127.0.0.1:80

还有别的建议吗？

**Comment by Potterli20** [comment]
> > > > 这是多久没更新？
> > > 
> > > 
> > > 哦，我是小白，能请教下怎么更新吗？
> > 
> > 
> > 问你的脚本作者了
> 
> 经过一番折腾，我把trojan-go手工升级为0.10.6，但是服务器日志依然handshake错误
> 
> Feb 04 02:49:42 localhost trojan-go[9982]: [INFO] 2022/02/04 02:49:42 trojan-go v0.10.6 initializing Feb 04 02:51:49 localhost trojan-go[9982]: [INFO] 2022/02/04 02:51:49 tcp connection from 162._:45388 Feb 04 02:51:49 localhost trojan-go[9982]: [INFO] 2022/02/04 02:51:49 tls connection from 162._:45388 Feb 04 02:51:49 localhost trojan-go[9982]: [ERROR] 2022/02/04 02:51:49 github.com/p4gefau1t/trojan-go/tunnel/trojan.(_Server).acceptLoop:server.go:130 trojan failed to accept conn | not a valid websocket handshake request: 162._:45388 Feb 04 02:51:49 localhost trojan-go[9982]: [WARN] 2022/02/04 02:51:49 redirecting connection from 162.*:45388 to 127.0.0.1:80
> 
> 还有别的建议吗？

更改域名

**Comment by MergenXu** [comment]
可能是端口填写错误，看看是不是443

**Comment by minos-ty** [comment]
老哥问题解决了吗
