### ISSUE TITLE
[BUG] 启用了websocket, 但是后台wireshark捕获识别协议是TCP，这个正常吗

### ISSUE THREAD

**Issue by V0idk** [p4gefau1t/trojan-go#422]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

## 如何复现这个 Bug

在此描述复现这个Bug所需要的操作步骤

## 服务器和客户端环境信息

在此描述你的服务器和客户端所处的网络环境，系统架构，以及其他信息

## 服务端和客户端日志

粘贴**故障发生时**，服务端和客户端日志

## 服务端和客户端配置文件

可以复现该问题的客户端和服务端的完整配置（请隐去域名和IP等隐私信息）

## 服务端和客户端版本信息

请执行./trojan-go -version并将输出完整粘贴在此处

## 其他信息

你认为对我们修复bug有帮助的任何信息都可以在这里写出来

**Comment by mostend** [comment]
有没有一种可能，websocket是基于tcp的呢？或者有没有另外一种可能，wireshark上可以筛选websocket报文呢？

**Comment by Potterli20** [comment]
有没有一种可能，websocket是基于https(tcp)的呢？或者有没有另外一种可能，wireshark上可以筛选websocket报文呢？

**Comment by V0idk** [comment]
> 有没有一种可能，websocket是基于tcp的呢？或者有没有另外一种可能，wireshark上可以筛选websocket报文呢？

就是没有显示websocket报文，我看网上的wireshark都是直接把协议显示出来了，所以我才纳闷

**Comment by V0idk** [comment]
需解密才显示
