### ISSUE TITLE
建议 go.mod 中对 v2ray 依赖的版本升级

### ISSUE THREAD

**Issue by teddysun** [p4gefau1t/trojan-go#43]
go.mod 中对 v2ray 依赖的版本依然是老版本的 4.19.1

`v2ray.com/core v4.19.1+incompatible`

建议在最后添加如下 replace，替换为最新版

`replace v2ray.com/core => github.com/v2ray/v2ray-core v4.23.1+incompatible`

参考链接：
https://github.com/v2ray/v2ray-core/issues/1983

**Comment by p4gefau1t** [comment]
已修改，感谢提醒

不过其实这个问题不是很大，因为只是用了v2ray的protobuf格式

**Comment by p4gefau1t** [comment]
还是改回来了，go mod tidy需要把gosumdb关了，而且使用replace的方式绕过这个问题感觉太hack了，其他用户编译可能会遇到不必要的困难

**Comment by teddysun** [comment]
> 还是改回来了，go mod tidy需要把gosumdb关了，而且使用replace的方式绕过这个问题感觉太hack了，其他用户编译可能会遇到不必要的困难

请参考以下项目中对 v2ray 的依赖写法：
https://github.com/shadowsocks/v2ray-plugin/blob/master/go.mod

实际上 replace 并不会产生影响，而是 v2ray 的历史包袱造成的。

**Comment by p4gefau1t** [comment]
我的意思是，直接替换，在不修改GOSUMDB的情况下，会导致这样的问题

```
go: github.com/v2ray/v2ray-core@v4.23.1+incompatible/go.mod: verifying module: github.com/v2ray/v2ray-core@v4.23.1+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/v2ray/v2ray-core@v4.23.1+incompatible: 410 Gone
        server response: not found: github.com/v2ray/v2ray-core@v4.23.1+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

当然把GOSUMDB=off能正常编译。

本人钻研不深，还不太能理解这个错误产生的原因，以及“历史包袱”的含义，希望能了解更多信息。

目前不太想替换，主要是考虑到replace之后，go build，写dockerfile和用户自己编译都会遇到麻烦，而且仅仅只是使用了protobuf生成的文件，只要geoip和geosite格式不变其实基本不会有什么影响。

**Comment by teddysun** [comment]
经过测试确实在开启 `GOSUMDB="sum.golang.org"` 的情况下执行 `go mod tidy`  会出错。
这是因为 v2ray 所使用的 module  名是 v2ray.com/core，从而导致了这样的现象。
我已经提交了一个 pull request 到 dev 分支，可以升级 v2ray 到最新版本。
https://github.com/p4gefau1t/trojan-go/pull/51

**Comment by p4gefau1t** [comment]
感谢，已经合并。
v2ray有无计划在未来修改包名呢，这样的确不方便。

**Comment by teddysun** [comment]
v2ray 估计是不会改了，所以说是历史包袱。
不过基本上也不影响使用，go.sum 里对 v2ray 依赖部分事先计算出来 sum 就不会影响编译。
