### ISSUE TITLE
在使用clash配置时客户端无法连接，是只能使用trojan-go客户端吗

### ISSUE THREAD

**Issue by golowper** [p4gefau1t/trojan-go#443]
这是我服务端docker报错：
>[ERROR] 2022/05/09 16:21:53 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | remote error: tls: bad certificate

**Comment by golowper** [comment]
成功解决，配置文件需要加入字段
![image](https://user-images.githubusercontent.com/77011000/167399984-a77b0c2c-f0ee-4980-82a3-fc9477e7c3ed.png)

**Comment by monk279** [comment]
> 成功解决，配置文件需要加入字段 ![image](https://user-images.githubusercontent.com/77011000/167399984-a77b0c2c-f0ee-4980-82a3-fc9477e7c3ed.png)

您好，这是哪个客户端的配置文件呢？我现在好像找不到能用的客户端了。
