### ISSUE TITLE
Freebsd crash

### ISSUE THREAD

**Issue by littlesum** [p4gefau1t/trojan-go#444]
root@dnscrypt:~ # ./trojan-go -config example/client.json
[INFO]  2022/05/10 19:15:44 trojan-go v0.10.6 initializing
[FATAL] 2022/05/10 19:15:44 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:78 invalid character '"' after object key:value pair

root@dnscrypt:~ # uname -ar
FreeBSD dnscrypt 12.2-RELEASE-p14 FreeBSD 12.2-RELEASE-p14 325282c09a5(HEAD) TRUENAS  amd64

**Comment by HenryLogic** [comment]
Hello, Could you tell me how to solve this problem? I meet this problem too.
