### ISSUE TITLE
[BUG] trojan-go的websocket无法通过AWS Cloudfront CDN, 通过Cloudflare CDN却没问题

### ISSUE THREAD

**Issue by CXwudi** [p4gefau1t/trojan-go#447]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

## 简单描述这个 Bug

服务器和客服端开启websocket实现CDN中转, CDN采用AWS Cloudfront  
但客服端显示错误:

```
[INFO]  2022/05/11 21:12:22 adapter listening on tcp/udp: 0.0.0.0:1080
[WARN]  2022/05/11 21:12:22 tls sni is unspecified
[INFO]  2022/05/11 21:12:22 cert is unspecified, using default ca list
[WARN]  2022/05/11 21:12:22 empty websocket hostname
[ERROR] 2022/05/11 21:12:48 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket failed to handshake with server | bad status
[ERROR] 2022/05/11 21:12:54 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket failed to handshake with server | bad status
[ERROR] 2022/05/11 21:13:01 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket failed to handshake with server | bad status
```

服务端显示错误:

```
[WARN]  2022/05/11 21:12:05 empty tls fallback port
[WARN]  2022/05/11 21:12:05 empty tls http response
[INFO]  2022/05/11 21:12:05 tcp connection from 192.168.176.4:43918
[INFO]  2022/05/11 21:12:05 tcp connection from 192.168.176.4:43914
[INFO]  2022/05/11 21:12:05 tls connection from 192.168.176.4:43914
[INFO]  2022/05/11 21:12:05 tcp connection from 192.168.176.4:43916
[INFO]  2022/05/11 21:12:05 tls connection from 192.168.176.4:43918
[INFO]  2022/05/11 21:12:05 tls connection from 192.168.176.4:43916
[INFO]  2022/05/11 21:12:05 tcp connection from 192.168.176.4:43922
[INFO]  2022/05/11 21:12:05 tls connection from 192.168.176.4:43922
[INFO]  2022/05/11 21:12:05 tcp connection from 192.168.176.4:43920
[INFO]  2022/05/11 21:12:05 tls connection from 192.168.176.4:43920
[INFO]  2022/05/11 21:12:06 tcp connection from 192.168.176.4:43924
[INFO]  2022/05/11 21:12:06 tls connection from 192.168.176.4:43924
[ERROR] 2022/05/11 21:12:12 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[ERROR] 2022/05/11 21:12:19 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[ERROR] 2022/05/11 21:12:26 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[INFO]  2022/05/11 21:12:31 tcp connection from 192.168.176.4:43942
[INFO]  2022/05/11 21:12:31 tls connection from 192.168.176.4:43942
[INFO]  2022/05/11 21:12:32 tcp connection from 192.168.176.4:43946
[INFO]  2022/05/11 21:12:32 tls connection from 192.168.176.4:43946
[INFO]  2022/05/11 21:12:32 tcp connection from 192.168.176.4:43948
[INFO]  2022/05/11 21:12:32 tls connection from 192.168.176.4:43948
[INFO]  2022/05/11 21:12:33 tcp connection from 192.168.176.4:43950
[INFO]  2022/05/11 21:12:33 tls connection from 192.168.176.4:43950
[INFO]  2022/05/11 21:12:33 tcp connection from 192.168.176.4:43952
[INFO]  2022/05/11 21:12:33 tls connection from 192.168.176.4:43952
[ERROR] 2022/05/11 21:12:33 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[ERROR] 2022/05/11 21:12:40 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[ERROR] 2022/05/11 21:12:47 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[INFO]  2022/05/11 21:12:48 tcp connection from 192.168.176.4:43960
[INFO]  2022/05/11 21:12:48 tls connection from 192.168.176.4:43960
[ERROR] 2022/05/11 21:12:54 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket failed to handshake
[INFO]  2022/05/11 21:12:55 tcp connection from 192.168.176.4:43966
[INFO]  2022/05/11 21:12:55 tls connection from 192.168.176.4:43966
```

## 如何复现这个 Bug

如前文描述

## 服务器和客户端环境信息

客服端 WIn 10使用官方Trojan-go,
服务端Ubuntu 20.04使用Docker版Trojan-go

## 服务端和客户端日志

见上文

## 服务端和客户端配置文件

客服端配置:

``` YAML
run-type: client
local-addr: 0.0.0.0 
local-port: 1080
remote-addr: <AWS Cloudfront分配过来的地址>
remote-port: 443
log-level: 1
log-file: ./trojan-go.log
password: 
  - my-password
websocket:
  enabled: true
  path: /my-path
```
服务端配置:

``` YAML
run-type: server
local-addr: 0.0.0.0
local-port: 443
remote-addr: <my fake website for trojan-go>
remote-port: 80
log-level: 1
log-file: /var/log/trojan-go.log
password: 
  - my-password
ssl: 
  cert: /path/to/my/lets-encrypt-cert
  key: /path/to/my/lets-encrypt-key
websocket:
  enabled: true
  path: /my-path
```
## 服务端和客户端版本信息

双方均使用Trojan-Go v0.10.6, 服务端通过watchtower定期更新VPS里所有的docker镜像, 包括Trojan-go

## 其他信息

事实上, 以上配置亲测在使用Cloudflare做CDN中转时没有问题, 我用的是https://github.com/p4gefau1t/trojan-go/issues/362#issuecomment-876403780 里的nginx设定, 但换成AWS Cloudfront就出现此问题. 

不仅如此, 在使用AWS Cloudfront的情况下, 用浏览器访问trojan-go能看到我设置的网址, 说明AWS Cloudfront能够顺利访问到服务端配置里的`remote-addr`, 但就是websocket无法正常链接. 这是我怀疑是不是因为Trojan-go没有按照[AWS Cloudfront的要求](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-working-with.websockets.html)进行websocket连接而导致websocket连接失败, 比如说未发送[AWS Cloudfront要求的](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-working-with.websockets.html)第一个HTTP请求, 但如果是的话, trojan-go没按要求来很可能又是为了加强GFW隐蔽性, 因为那个请求暴露了origin网址, 所以这可能是个无解的问题...

**Comment by hronro** [comment]
你的 hostname 始终会被泄露，这个和隐蔽性应该没有关系

**Comment by CXwudi** [comment]
@hronro 总之AWS Cloudfront的CDN中转无效, 另一种可能性就跟AWS Cloudfront自身有关了. 因为其他CDN比如说Cloudflare是通过把DNS record弄成自己的IP而实现中转的, 但AWS Cloudfront不需要DNS, 它是通过提供一个链接, AWS Cloudfront收到请求后直接转发到设置好的目的地. 也许是因为新的链接跟原本hostname不一致导致握手失败, 也有可能是AWS Cloudfront转发拆包的时候破坏了哪个header导致握手失败, 但这我就不清楚了

**Comment by asa-dong-9** [comment]
需要在 Cloudfront  自定义一个`源请求策略`，允许这两个header  `Sec-Websocket-Key`、 `Sec-Websocket-Version`  就正常了

具体看下面两个截图。


1. 创建策略
![创建策略](https://user-images.githubusercontent.com/106099520/169857185-b434333f-6171-468d-b60b-942b32cdc025.png)

2. 指定此策略
![指定自己的策略](https://user-images.githubusercontent.com/106099520/169857038-e9c019ae-f7c8-4b3d-a0ea-33b46c5253e2.png)

**Comment by CXwudi** [comment]
@asa-dong-9 感谢分享, 我有时间测一下

**Comment by CXwudi** [comment]
已亲测@asa-dong-9 的解决方案可行

**Comment by CXwudi** [comment]
通过一位youtuber的[视频](https://youtu.be/MHFYRRo1Q8E?t=352)也发现了下面这个亲测可行的配置
![image](https://user-images.githubusercontent.com/17377423/186051396-a48e4507-ebf1-404c-8fd5-631038581f84.png)
虽然不是best practice, 但至少在AWS还没有删除这个legacy setting之前, 这个设置还一直可以用

**Comment by loganleon** [comment]
> 通过一位youtuber的[视频](https://youtu.be/MHFYRRo1Q8E?t=352)也发现了下面这个亲测可行的配置
> ![image](https://user-images.githubusercontent.com/17377423/186051396-a48e4507-ebf1-404c-8fd5-631038581f84.png)
> 虽然不是best practice, 但至少在AWS还没有删除这个legacy setting之前, 这个设置还一直可以用

请问具体其他的cloudfront配置和视频里一样吗，为什么我这边尝试总是刚开始能ping通过一会就连不上了

**Comment by CXwudi** [comment]
> > 通过一位youtuber的[视频](https://youtu.be/MHFYRRo1Q8E?t=352)也发现了下面这个亲测可行的配置
> > ![image](https://user-images.githubusercontent.com/17377423/186051396-a48e4507-ebf1-404c-8fd5-631038581f84.png)
> > 虽然不是best practice, 但至少在AWS还没有删除这个legacy setting之前, 这个设置还一直可以用
> 
> 请问具体其他的cloudfront配置和视频里一样吗，为什么我这边尝试总是刚开始能ping通过一会就连不上了

需要原版trojan-go才行

**Comment by loganleon** [comment]
> 

是说客户端吗 服务端用的是trojan-go的 客户端用的是v2rayN的
