### ISSUE TITLE
[BUG]github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:78 listen tcp 0.0.0.0:443: bind: permission denied

### ISSUE THREAD

**Issue by aimixsaka** [p4gefau1t/trojan-go#451]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

## 问题
运行`./trojan-go -config ./server.json`时出现了permission denied问题

## 服务器和客户端环境信息

服务器：azure
系统版本：Linux (ubuntu 20.04)

## 补充
控制台开放了443端口，且没有其他应用占用443端口

## server.json配置
```json
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "xxxxxx"
    ],
    "ssl": {
        "cert": "/etc/letsencrypt/live/yfaimisaka.xyz/cert.pem",
        "key": "/etc/letsencrypt/live/yfaimisaka.xyz/privkey.pem",
        "sni": "我的网址"
    },
    "router": {
        "enabled": true,
        "block": [
            "geoip:private"
        ],
        "geoip": "/home/taiga/vpn/trojan/geoip.dat",
        "geosite": "/home/taiga/vpn/trojan/geosite.dat"
    }
}
```

**Comment by aimixsaka** [comment]
权限问题。。。

**Comment by imsinolam** [comment]
我在相同的地方遇到问题，但不是权限问题。
[FATAL] 2023/01/06 00:48:40 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:78 invalid character 'â' looking for beginning of value
github文件上无效的特殊字符？难道是要在哪里设置编码格式？

**Comment by imsinolam** [comment]
> 我在相同的地方遇到问题，但不是权限问题。 [FATAL] 2023/01/06 00:48:40 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:78 invalid character 'â' looking for beginning of value github文件上无效的特殊字符？难道是要在哪里设置编码格式？

已解决。vi直接编辑的json文件编码格式不对，在finalshell文件管理里新建文件直接编辑就没问题了。
