### ISSUE TITLE
[BUG]doesnt support LAN proxy?

### ISSUE THREAD

**Issue by Arryboom** [p4gefau1t/trojan-go#458]
trojan-go version:[v0.10.6](latest)
on windows 10 1906

I have a phone(192.168.0.5) in the same LAN with the PC desktop(192.168.0.10),and running trojan-go on desktop with client listen on local address 0.0.0.0:1080,but I can't access proxy from my phone with 192.168.0.10:1080,the other proxy software like ss works fine,on the desktop tried to set browser to use trojan-go's proxy 192.168.0.10:1080 everything seems fine,Is Lan Proxy supported?

**Comment by BoyuGuan** [comment]
So how to support LAN mode? Should change the local address?
