### ISSUE TITLE
trojan-go或许已经落后甚至不如vmess/vless+tls 

### ISSUE THREAD

**Issue by ghost** [p4gefau1t/trojan-go#461]
原因如下
1.trojan系列长期不维护，可能已被GFW掌握漏洞。
2.trojan-go的传输协议只支持TCP和ws，而v2ray、xray可自定义协议栈，相比之下trojan-go灵活性不足。
3.支持trojan多路复用的客户端少，很多机场的服务段端也不支持多路复用，很多人也不会开启。
4.trojan的shadowsocks加密可以被vmess的加密替代。

**Comment by hudingwen** [comment]
用了几年了也没啥问题啊

**Comment by 70599** [comment]
可能、或许、甚至

**Comment by Potterli20** [comment]
源是开源的，你可以维护。xray原维护人都不在维护了，这还能说明什么。能用就行

**Comment by 0x9579** [comment]
不建议换着花样搭了几个梯子就乱猜吧🤔

**Comment by fireinrain** [comment]
代码就在这里 作者没有精力维护 老哥可以来自己维护

**Comment by sjush** [comment]
> 用了几年了也没啥问题啊

我的用了半年，最近一到晚上就几k/s，服务器16m/s很稳定。感觉像是被人占用了带宽

**Comment by onlyJinx** [comment]
依据呢？还是全凭猜想？

**Comment by chinant** [comment]
> 



> > 用了几年了也没啥问题啊
> 
> 我的用了半年，最近一到晚上就几k/s，服务器16m/s很稳定。感觉像是被人占用了带宽



> > 用了几年了也没啥问题啊
> 
> 我的用了半年，最近一到晚上就几k/s，服务器16m/s很稳定。感觉像是被人占用了带宽

我也有这种情况,不太确定是晚高峰线路带宽的问题还是别的原因,也懒得去探查了...

**Comment by wander3r** [comment]
最近几台服务器不能用，换了端口才能用。

**Comment by xyanrch** [comment]
我优化的版本
https://github.com/xyanrch/overplus

**Comment by yyuurrii34** [comment]
现在所有使用tls的协议包括trojan/xray/v2ray都面临一样的问题，似乎tls的指纹已被识别。10月份出现大规模被封情况。

**Comment by xzkeee** [comment]
我的torjan go刚被封了一个ip

**Comment by h1orz** [comment]
> 现在所有使用tls的协议包括trojan/xray/v2ray都面临一样的问题，似乎tls的指纹已被识别。10月份出现大规模被封情况。

同样遭遇。

**Comment by CrazyBoyFeng** [comment]
> 现在所有使用tls的协议包括trojan/xray/v2ray都面临一样的问题，似乎tls的指纹已被识别。10月份出现大规模被封情况。

不一定是因为协议特征被识别。可能的原因有：
* 廉价机房被封杀。
* 免费域名和廉价域名被大规模 sni 阻断。
* 探测到免费证书和自签证书后被阻断。
* 服务器不存在网站或者网站不和谐。

我曾经伪装成盗版影视站，还用cdn护着。用了一段时间后被封域名。后来我伪装成外企网站，一直用到现在。这可能说明，伪装网站上的内容也会被审核。
所以这不一定是协议的问题。

trojan 协议本身出现漏洞的可能性不大，因为这是一个相当简单的协议。它在 tls 解包后根据连接后收到的第一个包的格式判断是否是 trojan 流量并校验密码。如果不是 trojan 请求或者校验不通过，要么将流量转给 http 服务器，要么断开。
这个原理几乎与 vless 一模一样，它们的区别仅仅是认证包格式不同。
虽然 trojan-go 的协议不再扩展，但是 trojan 这个协议被 v2ray 等项目拿去扩展了。现在不仅可以用 ws 传输 trojan，也可以用 grpc 等等协议传输 trojan。
