### ISSUE TITLE
ExecStop=/etc/trojan/bin/trojan-go (code=exited, status=1/FAILURE) ,啥情况？

### ISSUE THREAD

**Issue by ghq200101** [p4gefau1t/trojan-go#466]
root@XXXXXX:~# systemctl status trojan
 trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-10-15 20:49:23 CST; 17h ago
     Docs: https://github.com/p4gefau1t/trojan-go
  Process: 3259 ExecStop=/etc/trojan/bin/trojan-go (code=exited, status=1/FAILURE)
 Main PID: 3265 (trojan-go)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/trojan.service
           └─3265 /etc/trojan/bin/trojan-go -config /etc/trojan/conf/server.json

Oct 16 04:50:19 XXXXXX trojan-go[3265]: [INFO]  2022/10/16 04:50:19 tcp connection from 127.0.0.1:16408
Oct 16 04:50:19 XXXXXX trojan-go[3265]: [INFO]  2022/10/16 04:50:19 tls connection from 127.0.0.1:16408
Oct 16 04:50:19 XXXXXX trojan-go[3265]: [ERROR] 2022/10/16 04:50:19 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | not a valid websocket handshake request: 127.0.0.1:16408
Oct 16 04:50:19 XXXXXX trojan-go[3265]: [WARN]  2022/10/16 04:50:19 redirecting connection from 127.0.0.1:16408 to 127.0.0.1:80
Oct 16 04:52:19 XXXXXX trojan-go[3265]: [INFO]  2022/10/16 04:52:19 redirection done
Oct 16 07:57:55 XXXXXX trojan-go[3265]: [INFO]  2022/10/16 07:57:55 tcp connection from 127.0.0.1:16416
Oct 16 07:57:55 XXXXXX trojan-go[3265]: [INFO]  2022/10/16 07:57:55 tls connection from 127.0.0.1:16416
Oct 16 07:57:55 XXXXXX trojan-go[3265]: [ERROR] 2022/10/16 07:57:55 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | not a valid websocket handshake request: 127.0.0.1:16416
Oct 16 07:57:55 XXXXXX trojan-go[3265]: [WARN]  2022/10/16 07:57:55 redirecting connection from 127.0.0.1:16416 to 127.0.0.1:80
Oct 16 07:59:55 XXXXXX trojan-go[3265]: [INFO]  2022/10/16 07:59:55 redirection done

啥情况？

**Comment by RealSerendipity** [comment]
Please check the privilege of user in /etc/systemd/system/trojan.service

**Comment by ghq200101** [comment]
the problem is "ExecStop=/etc/trojan/bin/trojan-go" in the trojan.service, i correct it .
