### ISSUE TITLE
Make it multilingual

### ISSUE THREAD

**Issue by miladrahimi** [p4gefau1t/trojan-go#475]
First, thanks for your great project. There are Internet limitations in countries like Iran and Russia. This project could also help countries other than China. If it was in English or multilingual, we could use it to bring freedom back to people around the world. Thanks again.

**Comment by digits122** [comment]
oh my god, didn't realize there were other countries that needed to use this too. But it seems the author has not update this project for a long time, maybe you can use some auto translatation tools for help. This project is not that complex to build

**Comment by Azadzadeh** [comment]
@miladrahimi 
https://github.com/p4gefau1t/trojan-go/pull/480

https://azadzadeh.github.io/trojan-go
