### ISSUE TITLE
纯小白 请教一下怎么让程序作为客户端使用是 在WINDOWS下 后台运行 或者作为服务运行

### ISSUE THREAD

**Issue by qnets** [p4gefau1t/trojan-go#478]
纯小白 请教一下怎么让程序作为客户端使用是 在WINDOWS下 后台运行 或者作为服务运行

**Comment by royccai** [comment]
从https://github.com/p4gefau1t/trojan-go/releases/download/v0.10.6/trojan-go-windows-amd64.zip下载trojan-go的Windows端程序；在解压目录里创建config.json文件，写入客户端配置；运行trojan-go的.exe文件
