### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by James-handsome** [p4gefau1t/trojan-go#487]
[ERROR] 2023/02/11 10:14:40 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | remote error: tls: bad certificate

这是我的配置项
`"ssl": {
    "cert": "server.cer",
    "key": "server.key",
    "sni": "www.我的域名.top",
    "alpn": [
      "http/1.1"
    ],
    "fallback_addr": "127.0.0.1",
    "fallback_port": 80,
    "fingerprint": "firefox"
  },`
我的证书在CA申请的正规证书，trojan-go 为什么老提示我证书错误 TLS 握手错误,
但是跳过证书验证就可以用，不然就压根连不上

**Comment by Cz1544252489** [comment]
同问，楼主解决了吗
