### ISSUE TITLE
Failed to parse config file open

### ISSUE THREAD

**Issue by bygreencn** [p4gefau1t/trojan-go#5]
config.json file is following:

> {
  "run_type": "client",
  "local_addr": "127.0.0.1",
  "local_port": 1080,
  "remote_addr": "dj.itu.me",
  "remote_port": 443,
  "password": [
    "1100981"
  ],
  "ssl": {
    "cert": "",
    "sni": ""
  }
}

![image](https://user-images.githubusercontent.com/22853/77223219-6bbbf280-6b95-11ea-9624-61400d795873.png)

**Comment by p4gefau1t** [comment]
Can you take a screenshot of your complete command?

可以截图一下你的完整命令吗

**Comment by p4gefau1t** [comment]
Same issue in #9
