### ISSUE TITLE
how to rejoin the telegram group

### ISSUE THREAD

**Issue by YSDYH** [p4gefau1t/trojan-go#506]
while i join the telegram group ，I  fail to pass the verify test and blocked by admin，how can i rejoin the telegram group?my telegram name is 遗失の永恒 and my phone number is139****9627

**Comment by YSDYH** [comment]
today i see the question clearly but failed to pass the test because i worried i'll blocked again before i find out the answer so i random select a choice with a mistake,can you give me one more chance,thanks

**Comment by YSDYH** [comment]
today i see the question clearly but failed to pass the test because i worried i'll blocked again before i find out the answer so i random select a choice with a mistake,can you give me one more chance,thanks

**Comment by YSDYH** [comment]
i wonder if you can add me to the group chat because the question is so difficult for me,y telegram user name is t.me/YShDYH，while i search the answer,the google recptcha take so long time befoge i can find the answer so i fail the test again .
![Screenshot_2023-05-29-16-49-42-241_org telegram messenger](https://github.com/p4gefau1t/trojan-go/assets/96826323/5558a7ce-3584-4ba5-9283-b312d2f5ac00)

**Comment by xiaowuyongzhi** [comment]
怎么样可以再次提交啊
