### ISSUE TITLE
服务器已经有 nginx 了，可以不配置 https 部署吗

### ISSUE THREAD

**Issue by WeihanLi** [p4gefau1t/trojan-go#525]
服务器已经有 nginx 了，可以不配置 ssl 吗，ssl 在 nginx 统一配置了，有没有部署文档？

**Comment by SCGabriel** [comment]
用ngx_stream_ssl_preread_module
编译nginx的时候加上  --with-stream_ssl_preread_module
用了这个nginx模块trojan和nginx可以在443端口共存
