### ISSUE TITLE
是否有计划增加限制单密码连接数量限制

### ISSUE THREAD

**Issue by xhrm** [p4gefau1t/trojan-go#53]
如题，类似于SSR一样，可以限制单个密码的同时连接数量，

**Comment by p4gefau1t** [comment]
除非修改协议，否则技术上不太可行

比较好奇ssr是怎么实现的

**Comment by xhrm** [comment]
> 除非修改协议，否则技术上不太可行
> 
> 比较好奇ssr是怎么实现的

SSR是多端口限制，Trojan是单端口吧

**Comment by p4gefau1t** [comment]
可能你想表达的是根据IP地址计数进行限制？

**Comment by xhrm** [comment]
> 可能你想表达的是根据IP地址计数进行限制？

对，password1同时使用此密码连接最大值为1或2人。
