### ISSUE TITLE
mysql对接流量统计不准确

### ISSUE THREAD

**Issue by Guccen** [p4gefau1t/trojan-go#6]
用了一下午，数据库中流量统计并不准确。

**Comment by Guccen** [comment]
好像是upload和download写反了？
我下载100M文件变上传100M了？
`[INFO]  2020/03/21 19:54:06 user 4b519de92abd521293eaa7cc0a8aedff6eb1c9a6ecc5883d29dd2eac conn to speed.hetzner.de:80 closed up: 100.00 MiB down: 427 B`

**Comment by p4gefau1t** [comment]
这个up和down我实现的时候是相对本地来说的
上传对应出站流量，下载对应入站流量
如果原版是反过来的话，我在下一个版本把它反过来

**Comment by Guccen** [comment]
原版是相反的 希望能反过来吧 便于统计 谢谢

**Comment by p4gefau1t** [comment]
好的，users表的确应该存储用户的上传和下载统计，而不是服务器的

**Comment by Guccen** [comment]
是的 我这边对接的面板数据库 其实影响也不大 就是个统计问题

**Comment by p4gefau1t** [comment]
已经把日志显示换成发送和接受避免歧义，数据库的上传和下载现在是相对用户来说的了
