### ISSUE TITLE
上游代理/绑定某个nic

### ISSUE THREAD

**Issue by shawwwn** [p4gefau1t/trojan-go#62]
首先非常作者！

请问是否支持将服务端的outbound链接接入某个上游代理或者绑定给某个network interface呢？

**Comment by p4gefau1t** [comment]
目前好像不支持这种操作，也不太好实现

不太理解这种需求的使用场景？

**Comment by shawwwn** [comment]
我想要通过chain proxy的方式提高匿名度。

目前仅能在原版trojan上能通过network namespace来实现outbound流量转发，但是这样做会破坏ssl握手，因此被认为是不安全的。

**Comment by p4gefau1t** [comment]
> 我想要通过chain proxy的方式提高匿名度。
> 
> 目前仅能在原版trojan上能通过network namespace来实现outbound流量转发，但是这样做会破坏ssl握手，因此被认为是不安全的。

我感觉，对这种需求，应该在代理链的末尾部署trojan服务器，代理链中间做简单转发或者套混淆。

**Comment by shawwwn** [comment]
一般的代理软件都会支持upstream proxy，或者能够选择出口的network interface。

真的很需要这个功能，望作者添加！

**Comment by p4gefau1t** [comment]
可以考虑，但是我还没想好用什么样的json格式来配置比较好

**Comment by p4gefau1t** [comment]
服务器已经可以使用前置代理
