### ISSUE TITLE
为什么需要独立服务器接管80端口，而trojan-go接管443端口？

### ISSUE THREAD

**Issue by snowdream** [p4gefau1t/trojan-go#65]
在文档中看到 https://p4gefau1t.github.io/trojan-go/basic/config/

```bash
Trojan-Go将会测试这个HTTP服务器是否工作正常，如果不正常，Trojan-Go会拒绝启动。
```

问题是： 为什么需要独立服务器接管80端口，而trojan-go接管443端口？
不可以都由trojan-go来接管吗？

**Comment by phlinhng** [comment]
> 在文档中看到 https://p4gefau1t.github.io/trojan-go/basic/config/
> 
> ```shell
> Trojan-Go将会测试这个HTTP服务器是否工作正常，如果不正常，Trojan-Go会拒绝启动。
> ```
> 
> 问题是： 为什么需要独立服务器接管80端口，而trojan-go接管443端口？
> 不可以都由trojan-go来接管吗？

@snowdream  trojan 本身沒有 http 服務，你需要一個 http 服務器做為 trojan-go 的後端。80 端口應該是 http 服務器要處理的。而且文檔也沒規定 http 服務器只能放在 80 端口，web server 要開什麼端口都可以。

**Comment by p4gefau1t** [comment]
楼上是正确的。80端口的含义，是让你填写一个合法的HTTP服务器用于伪装。trojan-go本身不提供任何伪装功能，因为任何形式硬编码的伪装都将成为特征。
