### ISSUE TITLE
docker 方案如何配置"Let's Encrypt自动申请和更新HTTPS证书"?

### ISSUE THREAD

**Issue by snowdream** [p4gefau1t/trojan-go#66]
我之前获取Let's Encrypt的 HTTPS 证书是通过`acme.sh`。
获取过程中需要提供阿里云的 Key 和 Secret。
https://github.com/acmesh-official/acme.sh

trojan-go 如何Let's Encrypt自动申请和更新HTTPS证书。
不需要配置类似的Key 和 Secret？

**Comment by phlinhng** [comment]
acme.sh 不一定要 dns api
