### ISSUE TITLE
建议支持自动申请cloudflare证书，letsencrypt证书申请失败率越来越高了

### ISSUE THREAD

**Issue by depfish** [p4gefau1t/trojan-go#68]
建议添加支持自动申请cloudflare证书功能

**Comment by jinwyp** [comment]
我的一键安装脚本 申请成功率很高啊
https://github.com/jinwyp/one_click_script

**Comment by EdChdX** [comment]
Let me interrupt for once. Cloudflare certificates are issued upon domain binding, and if you want to use it, you should use Flexible mode or Strict mode in Cloudflare domain SSL tab, and get yours behind Cloudflare. If you use Flexible mode, you just need to open an HTTP port on your server, while Strict need a edge certificate which can be obtained in Cloudflare domain SSL tab.

**Comment by sdksdsd23** [comment]
说明下，我只想用cloudflare签发的免费证书，而不用他作为CDN。letsencrpt 重试次数多了容易被拉黑。限制貌似也比cloudflare多，letsencrpt有效期只有3个月,cf 证书有效期是1年。

**Comment by phlinhng** [comment]
> 说明下，我只想用cloudflare签发的免费证书，而不用他作为CDN。letsencrpt 重试次数多了容易被拉黑。限制貌似也比cloudflare多，letsencrpt有效期只有3个月,cf 证书有效期是1年。

@sdksdsd23  CF 的免費證書不是 CF 給開啟 CDN 的站自動裝上的嗎？有什麼方式可以直接獲得 CF 的證書？Let's 我試過一天五次大概就會拉黑，幾天後再試就好了，問題不大。
