### ISSUE TITLE
能否实现客户端全局

### ISSUE THREAD

**Issue by d1ves** [p4gefau1t/trojan-go#69]
安全从业相关，搞事情需要用到全局～
不知道能否实现

**Comment by p4gefau1t** [comment]
如果我没理解错的话，你是希望能让浏览器等客户端都走trojan-go代理。

这个事情应该由gui或者浏览器来做。trojan-go应该只专注于代理功能。如果需要这个功能，可以使用trojan-qt5或者其他gui。
