### ISSUE TITLE
请问下必须先TLS然后在WS吗？

### ISSUE THREAD

**Issue by jzdayz** [p4gefau1t/trojan-go#73]
我本身的配置是ok的，使用websocket，可以正常访问，然后套了一个cdn，就不行了，我尝试调整cdn的模式，调整为回源，也可以访问，我在服务器上架一个简单的websocket服务器，可以通过cdn中转，可以设置为直接ws然后ws里面TLS加密之类的吗？(可否去掉最外层的SSL)

**Comment by p4gefau1t** [comment]
目前不支持。可插拔传输层已经在下面的issue中被讨论

https://github.com/p4gefau1t/trojan-go/issues/71

未来trojan-go会支持明文与传输层混淆插件交互。但是**极不推荐任何形式的明文传输，包括websocket直接连接。**
