### ISSUE TITLE
[bug] 会无限创建MySQL连接

### ISSUE THREAD

**Issue by h2y** [p4gefau1t/trojan-go#80]
trojan-go 在mySQL鉴权模式下，会无限创建与数据库的连接，导致数据库过载，拒绝新的连接。但 trojan-go 本身似乎一直在使用之前创建的连接，所以工作正常。

![QQ截图20200605111231](https://user-images.githubusercontent.com/12909077/83833006-7c542180-a71d-11ea-94fa-a1c331371cda.jpg)

已确定是 trojan-go 的原因，因为重启 trojan-go 进程后数据库连接数立即恢复正常。
用的是 master 分支当前最新编译的版本。

**Comment by p4gefau1t** [comment]
收到，正在排查原因

**Comment by h2y** [comment]
hello, 我这里再多检查一下，好像是我修改了一处代码导致的这个问题。

**Comment by h2y** [comment]
_(:з」∠)_
找到问题所在了，是我添加了一个query调用，但是没有去处理其返回值导致的。
不好意思错误的提了个issue。

ps. 你的这个项目非常好用，给你点个赞 👍
