### ISSUE TITLE
trojan-go似乎只绑定ipv6地址，没有绑定ipv4

### ISSUE THREAD

**Issue by digits122** [p4gefau1t/trojan-go#81]
分别试验了trojan和trojan-go,
trojan在同时有ipv6和ipv4情况下，会按照设置内容绑定0.0.0.0:443
trojan-go在同时有ipv6和ipv4情况下，会绑定:::443，也即ipv6端口，ipv4没有绑定，端口仍然是空的未占用状态
已经使用netstat查看，不存在其他软件占用443端口，trojan和trojan-go没有同时启动，是分别试验的，配置除了trojan-go的一些特性以外，其他都是一样的

**Comment by teddysun** [comment]
root 用户输入命令 `netstat -nxtlp` 查看端口占用情况。
通常情况下 :::443 是 ipv6 和 ipv4 都可以被访问到的。如下所示：
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name      
tcp6       0      0 :::443                  :::*                    LISTEN      1376/trojan-go
```

**Comment by digits122** [comment]
我这里使用netstat -tnlp，返回一些端口监听，输出如下下
[root@mail ~]# netstat -tnlpx
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      1392/dovecot        
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      1392/dovecot        
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      1392/dovecot        
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      11076/nginx: master 
tcp        0      0 127.0.0.1:82            0.0.0.0:*               LISTEN      11076/nginx: master 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      808/sshd            
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1269/master         
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      1392/dovecot        
tcp6       0      0 :::995                  :::*                    LISTEN      1392/dovecot        
tcp6       0      0 :::110                  :::*                    LISTEN      1392/dovecot        
tcp6       0      0 :::143                  :::*                    LISTEN      1392/dovecot        
tcp6       0      0 :::80                   :::*                    LISTEN      11076/nginx: master 
tcp6       0      0 :::22                   :::*                    LISTEN      808/sshd            
tcp6       0      0 :::443                  :::*                    LISTEN      14127/trojan-go     
tcp6       0      0 :::993                  :::*                    LISTEN      1392/dovecot 

例如nginx程序绑定ipv4会有一条 tcp 0.0.0.0:80的输出，绑定ipv6的会有一条:::80的输出，这两个输出有分别显示，二sshd，dovecot，也都是类似。而这里trojan-go只在tcp6这里有一条绑定，我认为3个冒号是仅仅ipv6的，如果是既绑定了ipv4，又绑定了ipv6，为什么trojan-go不会像nginx一样，显示出两条绑定内容而只显示了一条？

**Comment by finalwhy** [comment]
加1，我的trojan-go也是这种情况

**Comment by p4gefau1t** [comment]
Listen同时接受IPv4和IPv6的TCP连接， 这是Linux的默认行为，和trojan-go无关。尚且trojan-go做的，也仅仅是把配置文件中的地址交给go网络库处理而已。参考这里：

https://stackoverflow.com/questions/20657650/socket-listener-for-ipv6-and-ipv4

如果你需要像nginx那样严格地开启两个socket分别监听IPv4和IPv6的所有入站(0.0.0.0和::)，可以修改源码，为socket添加IPV6_V6ONLY选项。

**Comment by pifeifei** [comment]
![image](https://user-images.githubusercontent.com/45787170/165201515-ccfccd9f-5a22-4355-a2f6-079d1d56b560.png)

我 httpd 显示只绑定 ipv6 端口， 但是 192.168.0.73:88 也是可以访问的，lnmp 环境
