### ISSUE TITLE
现在ios有支持的软件么

### ISSUE THREAD

**Issue by Dante-X** [p4gefau1t/trojan-go#82]
小火箭2.1.42版本测试不行

**Comment by h31105** [comment]
你把她当成Trojan，又不是不能用…

**Comment by Dante-X** [comment]
不行,扫描添加上了,翻不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"h31105"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月6日(星期六) 晚上6:49
收件人:&nbsp;"p4gefau1t/trojan-go"<trojan-go@noreply.github.com&gt;;
抄送:&nbsp;"囹圄"<473947905@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [p4gefau1t/trojan-go] 现在ios有支持的软件么 (#82)





 
你把她当成Trojan，又不是不能用…

**Comment by h31105** [comment]
那这不是Trojan-go的问题了，请去小火箭处提issue

**Comment by TDL3** [comment]
Quantumult X 可以，但是不支持Trojan-go的特性

**Comment by ilovesuyy** [comment]
> 小火箭2.1.42版本测试不行

2.1.52版本可用，话说你都多久没更新了

**Comment by Dante-X** [comment]
> > 小火箭2.1.42版本测试不行
> 
> 2.1.52版本可用，话说你都多久没更新了

还是去年下载的,我更新试试

**Comment by Dante-X** [comment]
> > 小火箭2.1.42版本测试不行
> 
> 2.1.52版本可用，话说你都多久没更新了

更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么

**Comment by h31105** [comment]
> > > 小火箭2.1.42版本测试不行
> > 
> > 
> > 2.1.52版本可用，话说你都多久没更新了
> 
> 更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么

我真服了你了，你别用二维码，填一下服务器地址（域名)、端口和密码试试看。

**Comment by ilovesuyy** [comment]
> > > 小火箭2.1.42版本测试不行
> > 
> > 
> > 2.1.52版本可用，话说你都多久没更新了
> 
> 更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么

允许不安全这个要勾上，实测不勾就连不上，也许是个bug，因为在trojan-gfw的服务端没这个问题

**Comment by h31105** [comment]
> > > > 小火箭2.1.42版本测试不行
> > > 
> > > 
> > > 2.1.52版本可用，话说你都多久没更新了
> > 
> > 
> > 更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么
> 
> 允许不安全这个要勾上，实测不勾就连不上，也许是个bug，因为在trojan-gfw的服务端没这个问题

瞎说，勾不勾要看服务器证书和配置 情况

**Comment by Dante-X** [comment]
> > > > > 小火箭2.1.42版本测试不行
> > > > 
> > > > 
> > > > 2.1.52版本可用，话说你都多久没更新了
> > > 
> > > 
> > > 更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么
> > 
> > 
> > 允许不安全这个要勾上，实测不勾就连不上，也许是个bug，因为在trojan-gfw的服务端没这个问题
> 
> 瞎说，勾不勾要看服务器证书和配置情况（iOS小火箭v2.1.52）

先说明一下，我服务器配置了CDN流量中转(基于WebSocket over TLS/SSL)，在小火箭里添加插件配置WebSocket、ws之类的试过了都没成功

**Comment by h31105** [comment]
> > > > > > 小火箭2.1.42版本测试不行
> > > > > 
> > > > > 
> > > > > 2.1.52版本可用，话说你都多久没更新了
> > > > 
> > > > 
> > > > 更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么
> > > 
> > > 
> > > 允许不安全这个要勾上，实测不勾就连不上，也许是个bug，因为在trojan-gfw的服务端没这个问题
> > 
> > 
> > 瞎说，勾不勾要看服务器证书和配置情况（iOS小火箭v2.1.52）
> 
> 先说明一下，我服务器配置了CDN流量中转(基于WebSocket over TLS/SSL)，在小火箭里添加插件配置WebSocket、ws之类的试过了都没成功

小火箭目前还不支持trojan-go的新特性，所以。。

**Comment by Dante-X** [comment]
> > > > > > > 小火箭2.1.42版本测试不行
> > > > > > 
> > > > > > 
> > > > > > 2.1.52版本可用，话说你都多久没更新了
> > > > > 
> > > > > 
> > > > > 更新了，也不行，直接扫的trojan-qt5分享二维码的代理模式，需要什么特殊设置么
> > > > 
> > > > 
> > > > 允许不安全这个要勾上，实测不勾就连不上，也许是个bug，因为在trojan-gfw的服务端没这个问题
> > > 
> > > 
> > > 瞎说，勾不勾要看服务器证书和配置情况（iOS小火箭v2.1.52）
> > 
> > 
> > 先说明一下，我服务器配置了CDN流量中转(基于WebSocket over TLS/SSL)，在小火箭里添加插件配置WebSocket、ws之类的试过了都没成功
> 
> 小火箭目前还不支持trojan-go的新特性，所以。。

好吧😂

**Comment by rapperx755** [comment]
圈X更新的如此迅猛，竟然也不支持go的新特性，小遗憾

**Comment by wynemo** [comment]
小火箭支持trojan-go啦 选websocket

**Comment by sanyuanya** [comment]
> 
我没找到这个
