### ISSUE TITLE
deployment triggered by external PRs can cause unwanted result

### ISSUE THREAD

**Issue by DuckSoft** [p4gefau1t/trojan-go#84]
https://github.com/p4gefau1t/trojan-go/blob/b93b95f011627a90dfc72334fdf0b6d8f96acd44/.github/workflows/gh-pages.yml#L27-L31

**Comment by DuckSoft** [comment]
@Qv2ray-dev I think we can help Trojan-Go fix their automation pipelines.
Let's get moving.

**Comment by p4gefau1t** [comment]
fixed
