### ISSUE TITLE
docker使用api操作用户无法持久化保存

### ISSUE THREAD

**Issue by arrayJY** [p4gefau1t/trojan-go#86]
docker restart一下，所有的更改都丢失了。请问如何达到持久化的目的，或者是现版本未加入持久化？

**Comment by p4gefau1t** [comment]
@arrayJY 这是feature，不是bug
用户数据的存储，检索和更新等，应该由外部数据库和api客户端完成，而不是trojan-go
trojan-go所有用户信息均存放在内存中

**Comment by arrayJY** [comment]
明白了，谢谢。
