### ISSUE TITLE
Can`t open the config file(ubuntu server arm64 19.04),just like the issue #5

### ISSUE THREAD

**Issue by WaytrueDeng** [p4gefau1t/trojan-go#9]
![DeepinScreenshot_select-area_20200323095923](https://user-images.githubusercontent.com/61548208/77273009-83a68a00-6ced-11ea-89a4-de54cbbc472c.png)

**Comment by WaytrueDeng** [comment]
Adding : The same problem happend on my Arch (amd64) laptap,I just download the release file not manualy compiling.
![DeepinScreenshot_select-area_20200323101058](https://user-images.githubusercontent.com/61548208/77273694-2dd2e180-6cef-11ea-8ac0-5aba994d34a1.png)

**Comment by WaytrueDeng** [comment]
OK,After my tring ,It seems like find the reason of this problem.It is because of the loss the client config.json`s certificate file(usually we don`t need to add it when we use the trojan C++ version,because the certificate file is from the acme.sh script rather than the manual customize).
![DeepinScreenshot_select-area_20200323111149](https://user-images.githubusercontent.com/61548208/77277473-f583d100-6cf7-11ea-8c7d-c432cbb1721f.png)

When I manual download the certificate file from my own vps ,and fix the config.json it finnal works!!!!!!!!!!!!!!!!!!!!!!!!!!!!
![DeepinScreenshot_select-area_20200323111700](https://user-images.githubusercontent.com/61548208/77277552-249a4280-6cf8-11ea-98cf-4926d4cbbb65.png)

So I am wondering can you add the certificate by default just like what the C++ version doing? It will be more friendly to those guys who just use others` service rather than manually make it.

**Comment by p4gefau1t** [comment]
Thanks for the advice

**Comment by p4gefau1t** [comment]
Fixed. The lastest version will show a warning instead of an error if the cert file is not specified

已经修复，最新的版本在缺少服务器证书文件的时候只会显示警告

**Comment by WaytrueDeng** [comment]
Thanks a lot.
