### ISSUE TITLE
0.70的一个问题

### ISSUE THREAD

**Issue by kingofotaku** [p4gefau1t/trojan-go#91]
首先贴一下json

{
    "run_type": "nat",
    "local_addr": "0.0.0.0",
    "local_port": 3333,
    "remote_addr": "1234.com",
    "remote_port": 1234,
    "log_level": 1,
    "log_file": "/koolshare/log/trojan.log",
    "password": ["xxxxxxxxx"],
    "buffer_size": 32,
    "dns": [],
    "disable_http_check": false,
    "ssl": {
      "verify": false,
      "verify_hostname": true,
      "cipher": "",
      "cipher_tls13": "",
      "curves": "",
      "prefer_server_cipher": false,
      "sni": "",
      "alpn": [
        "http/1.1"
      ],
      "session_ticket": false,
      "reuse_session": true,
      "plain_http_response": "",
      "fallback_port": 0,
      "fingerprint": ""
    },
    "tcp": {
      "no_delay": true,
      "keep_alive": true,
      "prefer_ipv4": false
    },
    "mux": {
      "enabled":false,
      "concurrency": 8,
      "idle_timeout": 60
    },
    "router": {
      "enabled": false,
      "bypass": [],
      "proxy": [],
      "block": [],
      "default_policy": "proxy",
      "domain_strategy": "as_is",
      "geoip": "/mnt/sda1/geoip.dat",
      "geosite": "/mnt/sda1/geosite.dat"
    },
    "websocket": {
      "enabled": false,
      "path": "",
      "hostname": ""
    },
    "shadowsocks": {
      "enabled": false,
      "method": "AES-128-GCM",
      "password": ""
    },
    "transport_plugin": {
      "enabled": false,
      "type": "",
      "command": "",
      "plugin_option": "",
      "arg": [],
      "env": []
    },
    "forward_proxy": {
      "enabled": false,
      "proxy_addr": "",
      "proxy_port": 0,
      "username": "",
      "password": ""
    },
    "mysql": {
      "enabled": false,
      "server_addr": "localhost",
      "server_port": 3306,
      "database": "",
      "username": "",
      "password": "",
      "check_rate": 60
    },
    "redis": {
      "enabled": false,
      "server_addr": "localhost",
      "server_port": 6379,
      "password": ""
    },
    "api": {
      "enabled": false,
      "api_addr": "",
      "api_port": 0,
      "api_tls": false,
      "ssl": {
        "cert": "",
        "key": "",
        "key_password": "",
        "client_cert": []
      }
    }
  } 

服务器是机场的。我的运行环境是路由器上的华硕梅林k版固件（arm版本）问题如下：当我用`trojan -config /koolshare/ss/trojan.json >/dev/null 2>&1 & `这个命令使Trojan-go在后台运行时（该命令我是写在另一个脚本里执行的），在经过一段时间后，便会出现进程退出的情况，且有时还会出现进程还在，但却无法连接的情况，已分别尝试开启or关闭mux，均无效（已排除服务器问题）。不过因0.70有无法输出log的bug，所以暂时无法帖log上来，也不确定到底是不是bug，又或是我这边系统的问题（0.60无此问题）。

**Comment by p4gefau1t** [comment]
死锁和goroutine泄漏，0.7.1已经修复
