### ISSUE TITLE
0.7版本安卓包遇到问题

### ISSUE THREAD

**Issue by txdywy** [p4gefau1t/trojan-go#92]
cdn(cloudflare) websocket模式下

websocket failed to handshake with server | bad status

同样配置用mac 0.7 client正常
直接连服务器websocket没有问题

**Comment by peter-tank** [comment]
原来不是我配置的问题，只是没有再去测直连。
nginx(tls, proxy http://)--> trojan-go(mux, ws, transport_plugin.type: plaintext, shadowsocks: enabled)
Server报：`invalid aead payload`，关闭 aead 加密后，Server 直接把 websocket 头读成 trojan hash：`invalid hash:domain.com`

**Comment by txdywy** [comment]
0.7.2修复了
