### ISSUE TITLE
从0.7.X开始，trojan-go都无法使用。

### ISSUE THREAD

**Issue by lxhao61** [p4gefau1t/trojan-go#96]
VPS为Debian 9系统（64位）， 测试0.7.X任何版本trojan-go都无法使用。采用systemctl管理的，其状态都如下：
root@instance-1:~# systemctl status trojan-go
● trojan-go.service - Trojan-Go - An unidentifiable mechanism that helps you byp
ass GFW
   Loaded: loaded (/etc/systemd/system/trojan-go.service; enabled; vendor preset
: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-06-12 18
:58:01 UTC; 8s ago
     Docs: https://github.com/p4gefau1t/trojan-go
  Process: 1845 ExecStart=/usr/bin/trojan-go/trojan-go -config /etc/trojan-go/co
nfig.json (code=exited, status=1/FAILURE)
 Main PID: 1845 (code=exited, status=1/FAILURE)
换回之前老的版本，一切正常！

**Comment by p4gefau1t** [comment]
请自行查看日志提示并检查配置文件格式，0.7.x增加了一些新的检查。

**Comment by lxhao61** [comment]
找到原因，开启了fallback_port，但实际没有配置。谢谢！
