### ISSUE TITLE
0.72版本不支持mysql了吗？

### ISSUE THREAD

**Issue by ThereChave** [p4gefau1t/trojan-go#99]
尝试了0.4.4支持，但是切换到0.72就不支持了，一样的配置文件都不显示
buffered data has been written into the database
连接数据库了，数据库的密码也用不了

**Comment by ThereChave** [comment]
准确来说是重构之后mysql不支持
配置json：
`{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 10492,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "your_awesome_password"
    ],
	"mysql": {
        "enabled": true,
        "server_addr": "127.0.0.1",
        "server_port": **,
        "database": "***",
        "username": "***",
        "password": "*****",
        "check_rate": 60
    },
    "ssl": {
        "cert": "***",
        "key": "***",
        "sni": "***"
    }
}`

**Comment by p4gefau1t** [comment]
@ThereChave 本地没能复现，有详细日志吗

**Comment by ThereChave** [comment]
**下载的trojan-go-linux-amd64  0.72版本**
centos-release-7-4.1708.el7.centos.x86_64
**level 0日志如下：**
[WARN]  2020/06/13 14:08:40 empty fallback address
[WARN]  2020/06/13 14:08:40 empty fallback port
[INFO]  2020/06/13 14:08:40 transport server is listening on tcp: [::]:443
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/transport.NewServer:server.go:355 transport server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/api.RunService:api.go:19 api handler found TROJAN_SERVER
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/trojan.NewServer:server.go:228 trojan server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/mux.NewServer:server.go:91 mux server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/simplesocks.NewServer:server.go:92 simplesocks server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/websocket.NewServer:server.go:147 websocket server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/api.RunService:api.go:19 api handler found TROJAN_SERVER
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/trojan.NewServer:server.go:228 trojan server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/mux.NewServer:server.go:91 mux server created
[DEBUG] 2020/06/13 14:08:40 github.com/p4gefau1t/trojan-go/tunnel/simplesocks.NewServer:server.go:92 simplesocks server created

配置文件没有改变，当为0.6版是可以正常连接数据库中的密码，会出现Buffered data has been written into the database，但是0.72并没有出现该提示，数据库正常，0.6版本可以正常使用

**Comment by p4gefau1t** [comment]
无法复现。新的版本已经在mysql部分增加了调试日志，你可以试试新的版本，然后反馈一下得到的日志，注意log_level设置为0

**Comment by ThereChave** [comment]
新版本0.74已经正常，谢谢！
